### ISSUE TITLE
Laraform-vue : Wizard step doesn't work

### ISSUE THREAD

**Issue by kschnekenburger** [laraform/laraform#1]
Hi, we are currently testing your library, we are interested to use it and buy a licence, but we have a problem with Wizard.

We reproduced your exemple : https://laraform.io/docs/1.x/basics/wizard-and-tabs
But the result is inline form.

Can you help us pls ?

**Comment by kschnekenburger** [comment]
Pro component ? :)

**Comment by laraform** [comment]
Hi, yes, it is a pro component. You can check out what's included in our demo in the README.md file of the downloaded .zip file.
