### ISSUE TITLE
[BUG] Flatpickr wrapper

### ISSUE THREAD

**Issue by grantholle** [laraform/laraform#100]
### Prerequisites

* [ ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

- PHP version: 7.3.16
- Laravel version: 7.3.0
- Laraform Vue package version and type: 1.1.16 pro
- Laraform Laravel package version: N/A

### Description

I've been getting a lot of errors with the flatpickr wrapper having an undefined variable. You can see the stack trace on [Flare](https://flareapp.io/share/qm112Rmd#F1).

### Steps to Reproduce

I have a single instance of the flatpickr element. It works fine 90% of the time. It seems that it's happening when trying to close flatpickr.

**Expected behavior:**

No exception should be thrown.

**Actual behavior:** 

https://flareapp.io/share/qm112Rmd#F1

### Additional Information

Can't reproduce the issue but I think adding an additional check if `evt` is defined should solve the issue.

**Comment by laraform** [comment]
That's such a strange error, because `e` is not even being used. Steps to reproduce would be great help, but nevertheless I've removed it from the listener callback. It will be out with next patch.

**Comment by grantholle** [comment]
Yeah I think it's because the files were minified, so the source maps have the original variable names, but the production code doesn't.

**Comment by laraform** [comment]
The `e` is now removed in `1.2.2` - let's see if the update solves the problem
