### ISSUE TITLE
[IDEA] An option to append a red asterisk to required field labels

### ISSUE THREAD

**Issue by karlerss** [laraform/laraform#101]
### Prerequisites

* [x] You've described your idea in a clean format with example.

### Description

Add an option to append a (red) asterisk to required (has accepted or required rule) field labels. This could be a global config option or a per-field option or something else.

### Example

Email <span class="text-danger">*</span> [________]

--

**Comment by mike2410** [comment]
See #53 if you require a solution right now ;-)

**Comment by laraform** [comment]
Sure, it might be a default feature in the future. As for now, you can go ahead with the proposed solution ou create your own `ElementLabel` component combining these two methods:
https://laraform.io/docs/1.x/how-tos/replacing-component#replace-component
https://laraform.io/docs/1.x/how-tos/creating-element#adding-required-attribute
