### ISSUE TITLE
[IDEA] Option for removing wizard's steps topbar

### ISSUE THREAD

**Issue by tonydotgit** [laraform/laraform#102]
### Prerequisites

* [x] You've described your idea in a clean format with example.

### Description

Would be nice if you can have an option within the form class to get rid of the wizard's top bar steps. I tried empty labels already which is good as well, but I would like to get rid of the "circles" as well:

![Imgur](https://i.imgur.com/gdei4qI.png)

### Additional Information

I tried the `$wizardControls` property as `false`, but that ones does remove the "back/next" buttons (which is not what I want to).

**Comment by laraform** [comment]
Setting `.form-wizard` CSS class to `display: none` maybe? Or defining [classes](https://laraform.io/docs/1.x/reference/frontend-form#prop-classes) like:

``` js
mixins: [Laraform],
data() { 
  return {
    classes: {
      formWizard: 'd-none'
    },
    // ...
  }
}
```

**Comment by tonydotgit** [comment]
@laraform that works as "a hack", problem is if I'm "inheriting" classes (so I've a base class with a default form and later a child class which extends from that one where I just need to remove the "steps" portion).

Rn I'm overriding buttons classes (so I use the `success` color instead `primary` and so, then overriding the `$formWizard` property in the child class force me to also "copy/hardcode/re-code" parent's class classes array as well.

Again, not a bit deal rn but it would be nice to have an option, or at least a workaround method inside the `Laraform::jsonSerialize` method that works similar than other properties where it checks for the method first, so in the method we can build a "custom override" method for include parent classes styles and so. What do you think?

I mean, it's a custom scenario but I feel like implementing Laraform at high-scale as I'm doing would require inheriting very often to perofrm A/B testing on the forms.

**Comment by laraform** [comment]
Ok, I see.

If there was an `extendClasses` option which only extends the classes and could be nulled in later uses would solve the problem?

**Comment by tonydotgit** [comment]
So... you're going to merge `classes` and `extendClasses` array for deciding the final css classes to use? if so, that would totally work for me.

**Comment by laraform** [comment]
We're definitely going to have something like that in 2.0. Right now I'm just thinking out loud:)

**Comment by tonydotgit** [comment]
Totally, congratulations on the latest improvements btw. Looking good at tech and document level. Amazing job!

I hope you can open the code contributions somehow so we can help you to push some code for new features/bug-fixes. It's a complicated one due the free vs pro versions but would be a nice to have.
