### ISSUE TITLE
[BUG] Target class [Laraform\Elements\DateElement] does not exist.

### ISSUE THREAD

**Issue by ossedk** [laraform/laraform#104]
Hello,

I got Laraform up and running smoothly, - the paid version. 

But when I want to use the date input I just get: 

"Target class [Laraform\Elements\DateElement] does not exist."

If set type to any other it works.

`public function schema() {
        return [
            'client' => [
                'type' => 'select',
                'label' => 'Choose or create client.',
                'search' => true,
                'items' => $this->chooseClient()
            ],
            'start_date' => [
                'type' => 'date',
                'label' => 'Choose optional start date',
                'class' => 'col-md-6',
            ],
            'end_date' => [
                'type' => 'date',
                'label' => 'Choose optional end date',
                'class' => 'col-md-6',
            ],
            'name' => [
                'type' => 'text',
                'label' => 'Name of the project.',
                'class' => 'col-md-6',
            ],
            'description' => [
                'type' => 'textarea',
                'label' => 'Optional description for the project.',
                'class' => 'col-md-12',
            ],
        ];
    }`

**Comment by laraform** [comment]
I'm closing this as we've resolved it in email: just needed a vendor reinstall when upgrading from community to pro version.
