### ISSUE TITLE
[IDEA] add autosave and inline edit function 

### ISSUE THREAD

**Issue by dzymail** [laraform/laraform#105]
There a lot libraries has autosave and inline edit function. (Phpgrid or Vue data grid etc.)

* [ ] After the user modify the data, the modification can be saved to the database immediately.
* [ ] If the content comes from a form, double-click will enter edit mode.

Do you have plans to support these 2 functions?
thanks!

**Comment by laraform** [comment]
There are quite a few features in plan, this can also be added to the list, but I'm not sure when will be implemented.

Right now what I can do is to help you build such features if you stuck at some point. For the first one I can tell right away that it's possible by watching `data` change (maybe with debounce) and submit data to an endpoint using a custom method while leaving out validation. The second one is a bit trickier, depends on the context, but surely Laraform instances can be initalized on the fly eg. with:

``` js
Vue.extend({
  mixins: [Laraform],
  // ...
})
