### ISSUE TITLE
[QUESTION] Is there control over how null values are treated when storing data?

### ISSUE THREAD

**Issue by mike2410** [laraform/laraform#106]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 
* Laravel version: 
* Laraform Vue package version and type: 
* Laraform Laravel package version: 

### Description

Let's say I have a ListElement. For whatever reason the User deletes all entries of said Element. As the element gets submitted now the value in the data will be null.

However, when I now retrieve the Element from DB, it loads that null value into the ListElement, resulting in a vue error.

### Additional Information

If the null value in the DB would be [] instead things would work fine.

**Comment by laraform** [comment]
Have you tried like this?

``` php
protected $casts = [
  'list' => 'array'
];
```
