### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bigfella59** [laraform/laraform#107]
I have tried 2 new fresh installs of Laravel 6.x and 7.x and followed your instructions to the letter to install & setup laraform and all I get is a blank screen when I invoke 127.0.0.1:8000, it looks to me as though vue is not being loaded but cannot be sure, this looks like a great product for a new project I have but cannot move on to the pro version unless I know it functions as described...during the setup I execute
npm i axios lodash moment vue --save
and I get the following warnings....

npm WARN laraform@1.0.10 requires a peer of axios@^0.18 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

Could this be the problem?
Thank you

**Comment by adamberecz** [comment]
Is there a console error in the browser?

**Comment by bigfella59** [comment]
Thank you.
No errors in console.
Do you have a live version of your very simple example, so that I can inspect via the browser.
Do I have to install any extra composer packages such as 
composer require laravel/ui   ? 
It looks like vue is never invoked in the browser, I did a file save as in the browser and have attached those files, I hope that helps...any ideas?
[formtest_files.zip](https://github.com/laraform/laraform/files/4649342/formtest_files.zip)
Also please note. the links from your github project to your docs are broken.

**Comment by adamberecz** [comment]
The files seems work fine on my end so this is probably an issue with the Laravel instance itself. As you've said in the email you sent me today you are new to Laravel, so here's what you might be missing:
- once creating the Laravel project, make sure you run `chmod -R 777 storage bootstrap` this is usually required (or at least used to be)
- you need to run `composer install` to install all dependencies - I guess you have this
- you need to run `php artisan:key generate` to create APP_KEY which is required for the app to run

I think with these you should have your Laravel project set up. Once you can confirm that by having Laravel's welcome screen at 127.0.0.1:8000 you can move ahead and install Laraform Community version as instructed here in Github.

If none of these help check your `storage/logs` folder for log files and you'll probably have more clue what's messing up.

ps: thanks for the tip for the broken links, I'll make sure they get fixed.

**Comment by bigfella59** [comment]
I did have the the Laravel working screen working, but created a new project adding your additional suggestions, I am running on windows and using xampp, I realised that some of the files I had created were using window EOL(CR LF) instead of unix EOL(LF), I edited these files and now have some console errors being reported via chrome inspect, the log is attached...any ideas?
Thank you.
[127.0.0.1-1589899892207.log](https://github.com/laraform/laraform/files/4651252/127.0.0.1-1589899892207.log)

**Comment by bigfella59** [comment]
i thought this might be a windows/xampp issue so i published on laravel forge and get identical console errors...any ideas?

**Comment by adamberecz** [comment]
This usually happens if you are using bootstrap theme but forget to set `bs4` in `config/laraform.php`:

``` php
// ...
'theme' => 'bs4',

// ...
```

**Comment by bigfella59** [comment]
Sorry, no effect, this is a plain vanilla laravel install.
Can I assume if you install a base laravel and then add laraform following your instructions you get something that works?

**Comment by adamberecz** [comment]
Yes, absolutely. Wondering what could be messing up things in your setup. I've sent you a Zoom link in email. In the next 5-10 minutes I'll be there so if you join I'm happy to help with the setup. If you prefer you can also book a slot [here](https://calendly.com/adamberecz/30min).

**Comment by bigfella59** [comment]
Thank you Adam, the zoom call helped solve the problem, which honestly related to me having conflicting settings in my localhost file (I am an idiot!)...demo now working...great help, greatly appreciated.
Regards Bigfella59
