### ISSUE TITLE
[BUG] Custom Radio slot does not re-trigger validation in a Wizard

### ISSUE THREAD

**Issue by mikewuu** [laraform/laraform#108]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

* PHP version: N/A
* Laravel version: N/A
* Laraform Vue package version and type: 1.1.17 pro
* Laraform Laravel package version: N/A

### Description

A custom radio template does not trigger re-validation in a wizard.

### Steps to Reproduce

1. Submit form
2. See validation error
3. Select a radio, still see error

```
data: () => ({
    wizard: {
      details: {
        label: 'details',
        elements: ['checkboxgroup3'],
      },
    },
    schema: {
      checkboxgroup3: {
        type: 'radiogroup',
        rules: 'required',
        items: {
          usps: {name: 'USPS', price: '$36.71'},
          fedex: {name: 'Fedex', price: '$28.15'},
          ups: {name: 'UPS', price: '$38.97'},
        },
        slots: {
          radio: Vue.extend({
            props: ['el$', 'item', 'value'],
            template: `
                <div>
                  <label
                    :for="value"
                  >
                    <input
                      type="radio"
                      v-model="el$.model"
                      :value="value"
                      :name="value"
                      :id="value"
                    />

                    <span v-html="item.name"></span>
                    <span v-if="item.price">
                      <small class="text-muted">
                        {{ item.price }}
                      </small>
                    </span>
                  </label>
                </div>
              `,
          }),
        },
      },
    },
  })
```

**Expected behavior:**

Should re-check validation, ie. allow to re-submit form if filled

**Actual behavior:** 

Input does not pass *required* validation

![image](https://user-images.githubusercontent.com/11449462/82993979-661ed500-a03c-11ea-9e32-5f2752d6c91c.png)

**Comment by adamberecz** [comment]
I think what you're missing here is the `@change` event on input field. See example here:
https://github.com/laraform/examples/blob/master/shopify-checkout/resources/js/components/slots/ShippingMethodRadioSlot.vue

**Comment by mikewuu** [comment]
@adamberecz  That did it, thanks! Just a note, you might want to update the **Custom Radio Template** example to include `@change` https://laraform.io/docs/1.x/reference/radiogroup-element#examples
