### ISSUE TITLE
[BUG] TextElement field does not consistently re-trigger validation on mobile

### ISSUE THREAD

**Issue by tomduncs** [laraform/laraform#109]
### Prerequisites

* [X] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [X] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [X] Your issue isn't already filed.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 7.4.5
* Laravel version: 7.0
* Laraform Vue package version and type: 1.2.2
* Laraform Laravel package version: 1.2

### Description

When using Chrome browser on an Android device, if I load a form with required text fields and try to submit without filling in the fields, it correctly displays the validation error. But if I then type something in those fields it does not re-trigger the validation and the error remains. However there are certain actions which do trigger the revalidation, for example:

- when you type a space
- if you select an autocomplete word suggestion
- if you tap out of the field, then back in again and type another character. 

### Steps to Reproduce

As above, on a mobile device (tested on Android Chrome) load a form with a required TextElement field. Do not fill in the field. Attempt to submit the form, see validation error. Then fill in the field.

**Expected behavior:**

On typing in the field, validation should be re-triggered, the error should be removed, and form can be submitted.

**Actual behavior:** 

Error is not removed unless triggered by certain conditions as described above.

### Additional Information

I originally noticed this problem on my own form which is in a wizard format but can reproduce it on the Laraform website examples.

My form uses 'submit|step|change' for validateOn

**Comment by adamberecz** [comment]
Thanks for the details issue @tomduncs!

Having invalid state after `space` seems a legit case if the field has `required` rule eg. because having only "empty" character in a required input field should be an invalid value. The autocompletion is something I need to look into, but I haven't been able to reproduce the last one:
> if you tap out of the field, then back in again and type another character.
So you have an invalid field after submission (eg. empty) then you focus it, then move to an other field then come back to the empty field and nothing happens after you type a valid character?

**Comment by tomduncs** [comment]
Thanks for replying. I think you may have misunderstood, it's a bit confusing to explain, but it's kind of the opposite to how you describe it. 

So to clarify, you have an empty required field, and try to submit the form and it shows the validation error for the field - all good so far. But then if you type some text in the field, it stays in the error state, when it should become valid. The only way to remove the error state is one of the ways I described, e.g. add a space, click an autocomplete suggestion, or move out of the field, back in again and start typing again, and also (just noticed this) if you type numbers or punctuation. Very strange!

Seems like it only affects the default Gboard keyboard on Android, because when I switch to Swiftkey, it works perfectly.

**Comment by adamberecz** [comment]
Ok, now I see, I've also tested it on Android Chrome and indeed produces this bug. I have to dive into this issue and will get back with the fix.

**Comment by adamberecz** [comment]
in progress

**Comment by tomduncs** [comment]
Hi, any update on this? I have also noticed a very similar bug in Firefox (desktop) where the error state of a required text field is not removed if you select an autocomplete option. Shall I open another issue for that?

**Comment by adamberecz** [comment]
I didn't get to this issue yet - sorry for that. I'll do my best to fix both of them this week!

**Comment by adamberecz** [comment]
@tomduncs fixed both in [`1.2.4`](https://laraform.io/releases). Apparently some mobile browsers require to implement `v-model` functionality manually to work properly... 🙄

**Comment by tomduncs** [comment]
Thanks @adamberecz, testing it today. I'll close this once I've checked it.
