### ISSUE TITLE
Unable to save data on model with non numeric key

### ISSUE THREAD

**Issue by gmartinez** [laraform/laraform#11]
I have a model whose primary key is a string, having created a record in it, later I can not save modifications to it, as laraform tries to insert instead of update.

Schema goes like this;

> return [
	'guid' => [
		'type' => 'key',
		'secret' => true
	],
	'otype' => [
		'type' => 'hidden',
		'default' => 'mandm',
		'attribute' => 'type'
	],
	'name' => [
		'type' => 'text',
		'label' => 'Title',
		'rules' => 'required'
	],
	'_props->pointer' => [
		'type' => 'file',
		'drop'=> true
	]
];

The problem seems to be the code, at setKeyFromData() is trying to decode the key which was never encoded in the first place.

In the meantime I've modified ln 814 of Laraform.php from 

> $key = Hash::decode($key);

to

> $key = Hash::decode($key)==[] ? $key : Hash::decode($key);

FYI, I am not sure I get the approach of the encode/decode key feature, I tend to think it aims to protect keys, I understand you avoid it when env. is local...

**Comment by laraform** [comment]
Yes, this `Hash` library can only encode/decode numeric keys, which indeed aims to provide some level of security in production. It will not work with non-numeric keys though, but I'll come up with a solution for that in a later release, thanks! In the meantime I can recommended setting `secret` to `false` on `guid`, which should skip the encoding part.

**Comment by gmartinez** [comment]
Setting secret to false, I had already tried, does not work, the logic still enters setKeyFormData() and in there it correctly enters the if where it attempts the Hash:decode($key); which returns an empty array.

My workaround works though (!?)

**Comment by gmartinez** [comment]
I've changed my workaround, left ln 814 at Laraform.php as it was, and changed ln 28 of Support/Hash.php from;

>return (new Hashids(md5(env('APP_KEY')), 10))->decode($value)[0]

to

>return (new Hashids(md5(env('APP_KEY')), 10))->decode($value)[0] ?? $value;

**Comment by laraform** [comment]
If your fix works, it's fine, but I'll look into the issue anyway. A whole example with model and migration would help though.

**Comment by gmartinez** [comment]
Table looks like;

> CREATE TABLE `objects` (
  `guid` char(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_props` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  UNIQUE KEY `objects_guid_unique` (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Model has nothing special, looks like;

> <?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Arr;
use Laravel\Scout\Searchable;

class Obj extends Model
{
    use Searchable;
    //
    protected $connection;
    protected $table = 'objects';
    protected $primaryKey = 'guid';
    protected $keyType  = 'string';
    protected $casts = [
        '_props' => 'json',
    ];
    public $incrementing = false;
}

**Comment by laraform** [comment]
Hi! I've created a new bug report template, so if you still have the issue please resubmit accordingly: https://github.com/laraform/laraform/issues/new?assignees=&labels=bug&template=1_bugs.md&title=%5BBUG%5D

(was not able to reproduce the bug because I was thrown "Unknown column" sql error)
