### ISSUE TITLE
[QUESTION] how to translate flatpickr dates?

### ISSUE THREAD

**Issue by gabrielchavezme** [laraform/laraform#111]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.2.1
* Laravel version: 6.2.1
* Laraform Vue package version and type: pro
* Laraform Laravel package version: 1.1.17 pro

### Description

I am trying to translate the names of the months and days from flatpickr but I have not been successful.

I have tried through the Laraform setup with the timezone but it doesn't work.

Also try importing the flatpickr module into the app.js file and with the localize method I assign the name of the language (s) just as mentioned in your documentation https://flatpickr.js.org/localization/

### Additional Information

I have seen that in your local available section they need help to translate laraform, I speak Spanish natively and I would like to be able to collaborate, is there a possibility?

**Comment by adamberecz** [comment]
Importing the locales from flatpickr should be the right approach, but as the date elements are using a new flatpickr instance it won't work globally - we need to set it locally. Also as far as I can see the `locale` is currently not among the [options](https://laraform.io/docs/1.x/reference/date-element#option-options) in the flatpickr wrapper component, so the quickest way to do it right now is this:
``` vue
<script>
  import { Russian } from "flatpickr/dist/l10n/ru.js"

  export default {
    mixins: [Laraform],
    data() {
      return {
        schema: {
          date: {
            type: 'date',
          }
        }
      }
    },
    mounted() {
      this.el$('date').$refs.datepicker$.flatpickr$.set('locale', Russian)
    }
  }
</script>
```

This is something should and will be improved in the future.

**Comment by adamberecz** [comment]
Also there will be a round when we'll look for help in translation so you offer is much appreciated @gabrielchavezme , thanks!:)

**Comment by gabrielchavezme** [comment]
> Also there will be a round when we'll look for help in translation so you offer is much appreciated @gabrielchavezme , thanks!:)

This works perfect in a normal schema but when having the date inside an object it doesn't work.

I have tried the following:

`this.el$("dividends.*.dividend_payment_options. *. multiple_exhibition_date").$refs.datepicker$.flatpickr$.set ("locale", Spanish)`

And also:

`this.el$("dividends.opciones_pago_dividendos.date_varias_exhibiciones").$refs.datepicker$.flatpickr$.set ("locale", Spanish)`

Any ideas? @laraform @adamberecz
