### ISSUE TITLE
[QUESTION] Early Multi Step Form Wizard cancellation

### ISSUE THREAD

**Issue by xyNNN** [laraform/laraform#112]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.4.4
* Laravel version: 7.0.4
* Laraform Vue package version and type: 1.2.2 / pro 
* Laraform Laravel package version: 1.2.0 / pro

### Description

I’ve a multi step form wizard and I've some question (type select) in the second step. And if you select the second choice the form should be aborted due to the fact that send you can't submit the whole form. I would like to show a alternative text and remove all buttons so you can't continue.

Any ideas how to solve this? 
Thanks!

By the way. Thank you very much for this awesome product!

**Comment by adamberecz** [comment]
Here's a possible solution for it:
``` vue
<script>
  import Vue from 'vue'

  export default {
    mixins: [Laraform],
    data() {
      return {
        wizard: {
          first: {
            label: 'First',
            elements: ['a'],
          },
          second: {
            label: 'Second',
            elements: ['b', 'c'],
          },
          third: {
            label: 'Third',
            elements: ['d'],
            conditions: [
              ['b', 'yes']
            ],
          },
        },
        schema: {
          a: {
            type: 'text',
          },
          b: {
            type: 'select',
            items: {
              'yes': 'Yes',
              'no': 'No'
            }
          },
          c: {
            type: 'static',
            content: Vue.extend({
              props: ['el$'],
              template: `<a href="" class="btn btn-primary">Go somewhere else</a>`
            }),
            conditions: [
              ['b', 'no']
            ],
          },
          d: {
            type: 'text',
          },
        }
      }
    },
    mounted() {
      let b = this.el$('b')

      b.on('change', () => {
        this.wizardControls = b.value === 'yes'
      })
    } 
  }
</script>
```
> By the way. Thank you very much for this awesome product!

Glad you like it! ;)

**Comment by xyNNN** [comment]
Thanks for your possible solution. Great. I've a similar solution for this type of problem.
