### ISSUE TITLE
[IDEA] Integrate a command to generate forms

### ISSUE THREAD

**Issue by gabrielchavezme** [laraform/laraform#113]
### Prerequisites

* [x] You've described your idea in a clean format with example.

### Description

I have a project in which I need about 40 different forms, currently I have to create class by class manually and this takes unnecessary time.

### Example

Implement a very simple package in my project to generate these forms and put it on the table, I feel like it could give Laraform much more power.

### Additional Information

Repository: https://github.com/gabrielchavezme/laraform-command

**Comment by adamberecz** [comment]
Thanks for this too @gabrielchavezme it looks nice! I also have plans to add this feature in the future so when I get to the point I'll examine it more closely! I've added it to my watchlist.

**Comment by skillcraft-io** [comment]
Great work! 

I coded this exact command for my projects, as I do with any class/file I repeatedly create
