### ISSUE TITLE
[QUESTION] How to overwrite a method of a component

### ISSUE THREAD

**Issue by xyNNN** [laraform/laraform#114]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.4.4
* Laravel version: 7.0.4
* Laraform Vue package version and type: 1.2.2 / pro 
* Laraform Laravel package version: 1.2.0 / pro

### Description

I've a list element and it's prefilled with one item and the "name" property is prefilled by default with "Child 1". Now when I press the button "add" I want to prefill the second item of this list object with "Child 2" as name property. I thought about to overwrite the add method of this component in the form but I don't see any hint in the documention where and if this is possible.

At first I wanted to modify this value with the help of the event "add" but this event is called before the data is added. Instead of this solution I wanted to overwrite the method "add" to add my own behaviour, but I don't know how and if it's possible. I'm also not very familiar with Vue - so perhaps anyone have a hint for me. Thanks.

`   
    export default {
        mixins: [Laraform],
        data() {
            return {
                schema: {
                    children: {
                        schema: {
                            childrens: {
                                methods: {
                                    add(data) {
                                        console.log('Data', data);
                                    },
                                }
                            }
                        }
                    }
                },
            }
        }
    }
`

**Comment by adamberecz** [comment]
You can replace an element's component and overwrite some of its methods:
https://laraform.io/docs/1.x/how-tos/creating-element#override-existing-element

**Comment by xyNNN** [comment]
> You can replace an element's component and overwrite some of its methods:
> https://laraform.io/docs/1.x/how-tos/creating-element#override-existing-element

Okay thanks. I thought that there is another way to replace some small functionality before to override the whole element
