### ISSUE TITLE
[IDEA] Toggle To Support Checked/Unchecked Colors

### ISSUE THREAD

**Issue by skillcraft-io** [laraform/laraform#115]
I was looking into the toggle component that LaraForm uses and  I noticed that the toggle switch supports a unchecked/checked toggle color.

It would be neat to support this out of the box, without having to overwrite the core and implement the toggle/untoggled (checked/unchecked) coloring.

Just any idea, finally back at implementing this package across several project, loving the updates to docs and the package since I bought this last November.

**Comment by adamberecz** [comment]
You mean beyond this?
https://laraform.io/docs/1.x/reference/toggle-element#faster-bigger-different-color

Great, glad you're back on track! Always welcome any feedback.

**Comment by skillcraft-io** [comment]
It's good to be back on track :)

![toggle_coloring](https://user-images.githubusercontent.com/41481716/85704200-14ef1900-b6ae-11ea-91e8-bda53d56a4ba.png)

Yes, a little more than what is offered currently.

If you noticed in the above picture taken from the documentation of the Toggle button package used by laraform, there is support for a "checked" color for the handle and a unchecked color for the handle. 

Here is my form:
![unchecked](https://user-images.githubusercontent.com/41481716/85704858-b37b7a00-b6ae-11ea-9bb5-b04792d9d1b2.png)
unchecked

![checked](https://user-images.githubusercontent.com/41481716/85704865-b5453d80-b6ae-11ea-95fb-b3d8f4e393cc.png)
checked

**Comment by adamberecz** [comment]
Thanks @zhxscript I will take this into account when getting to the toggle element in 2.0.
