### ISSUE TITLE
[QUESTION] How to upload a file to a custom controller from the frontend?

### ISSUE THREAD

**Issue by gabrielchavezme** [laraform/laraform#116]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.2.1
* Laravel version:  6.2.1
* Laraform Vue package version and type: 1.1.12 pro
* Laraform Laravel package version: 1.1 pro

### Description

I have a schema of type list and in turn I have two elements; text and file

I have a custom controller for this function since I require it to be this way but the file never reaches the request, I get an empty array.

### Additional Information

**My schema**

```
schema: {
      id: {
        type: "key"
      },
      name: {
        type: "text",
        floating: "Nombre de la pagina",
        label: "Nombre o título de la pagina",
        rules: ["required"],
        placeholder: "Ingresa el nombre de la pagina",
        columns: 6
      },
      layout: {
        type: "select",
        search: true,
        columns: 6,
        label: "Tipo de pagina",
        placeholder: "Selecciona una opción",
        items: {
          1: "PDF o Word",
          2: "Contenido de texto",
          3: "PDF por secciones"
        }
      },
      content: {
        type: "trix",
        label: "Contenido",
        conditions: [["layout", 2]]
      },
      banner: {
        type: "file",
        label: "Banner de la pagina",
        conditions: [["layout", 2]],
        disk: "public",
        folder: "banner"
      },
      sections: {
        type: "list",
        label: "Contenido de la sección",
        conditions: [["layout", 3]],
        object: {
          schema: {
            section_name: {
              type: "text",
              columns: 4,
              label: "Nombre de la sección",
              placeholder: "Ingresa el nombre de la sección",
              floating: "Nombre de la sección",
              rules: ["required"]
            },
            sub_section: {
              type: "list",
              columns: 6,
              label: "Sub sección",
              object: {
                schema: {
                  name: {
                    type: "text",
                    placeholder: "Ingresa el nombre del PDF",
                    floating: "Nombre del PDF",
                    rules: ["required"],
                    columns: 6
                  },
                  file: {
                    type: "file",
                    label: false,
                    columns: 6,
                    disk: "public",
                    folder: "files",
                  }
                }
              }
            }
          }
        }
      }
    },
```

**The controller payload is:**

```
{
    "form_data": {
        "id": null,
        "name": "asasdasd",
        "layout": 3,
        "sections": [{
            "section_name": "asdas",
            "sub_section": [{
                "name": "asdasda",
                "file": []
            }]
        }]
    }
}
```
**My form:**

```
<template>
    <div id="create_page_form_container">
        <form class="laraform-bs4 form-horizontal" @submit.prevent="submit" ref="form$" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-12 col-xs-12 text-center">
                    <FormErrors v-if="formErrors && errors.length" :errors="errors" />
                </div>
            </div>
            <div class="next_step_form">
                <div class="row">
                    <div class="col-xs-12 col-md-12">
                        <button type="submit" class="btn btn-block mb-1 btn-primary waves-effect waves-light">
                            <span v-if="!loading">Guardar pagina</span>
                            <span v-if="loading" class="spinner-border spinner-border-sm" role="status"
                                aria-hidden="true"></span>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</template>
```

**Comment by adamberecz** [comment]
Based on the example schema you provided I had the files sent as binary data when submitting the form:
https://prnt.sc/t65qqz

When used the template I didn't have any fields rendered though (as there's no `FormElements` component nor any inline elements).

You sure isn't there something in the environment that messes up things? 

Btw: `disk` and `folder` options should only be defined in backend form schema's (no effect on the frontend).

**Comment by gabrielchavezme** [comment]
> Based on the example schema you provided I had the files sent as binary data when submitting the form:
> https://prnt.sc/t65qqz
> 
> When used the template I didn't have any fields rendered though (as there's no `FormElements` component nor any inline elements).
> 
> You sure isn't there something in the environment that messes up things?
> 
> Btw: `disk` and `folder` options should only be defined in backend form schema's (no effect on the frontend).

After looking for a while, I realized the error, I share it in case someone goes through the same thing.

It turns out that I need to do custom shipping and for this reason I use axios.

I was creating an array of all the data like this:

```
var data = {
        form_data: this.filtered,
        files: files
      }
```
Here was the problem since the object data returned by `this.filtered` was not being formatted.

What I did was transform that variable into the following:

```
var data = this.formData({
        key: this.key,
        data: this.filtered,
        files: files
      });
```

In this way, reuse the default `formData` method in Laraform.

This totally solved my problem.

I hope in the future to be able to help a dev with this: D
