### ISSUE TITLE
[BUG] getEntity() returns null in tests

### ISSUE THREAD

**Issue by mike2410** [laraform/laraform#117]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.2
* Laravel version: eg. 7
* Laraform Vue package version and type: latest
* Laraform Laravel package version:  latest

### Description

I use AutoProcessing in a post endpoint, however getEntity() in an after hook results to null, although saving to database seems to work fine.

### Steps to Reproduce

UserController.php

```
public function store(Request $request){
  return (new AutoProcess())->process($request, app(StaffmanagerForm::class));
}

```

FeatureTest.php

```
/* authorization etc. */

$this->post('/users', ["data" => ["firstname" => "firstname", "lastname" => "lastname", "email" => "yadda@bla.test"]]);
```

UserForm.php

```
/* Schema etc. */

public function after(){
$this->getEntity(); //is null, should be instance of user
}
```

**Expected behavior:**

$this->getEntity() should return user instance in after() hook of UserForm.php

**Actual behavior:** 

$this->getEntity() is null

### Additional Information

Setting "secret" for the id-field to false seems to solve the issue ...

**Comment by adamberecz** [comment]
This usually happens if the element list does not have an `id` field with `key` type.

**Comment by mike2410** [comment]
With "element list" you mean the schema right? Yeah as mentioned before, this field is present, however once I set "secret" to true the tests fail ... thus I'd have to toggle that flag based on whether I'm testing or not ...

**Comment by adamberecz** [comment]
Yes - I mean the `schema`. There's been an issue with this `secret` feature on production and now apperently with tests... I'll have to look into it and probably change the encoding library. If you have a workaround it's better to stick to it for now.

**Comment by mike2410** [comment]
Oh I see, is there a way to manually generate the secret value for `id `and send that with my post request?

**Comment by adamberecz** [comment]
Laraform is using [Hashids](https://hashids.org) but you might even use built in Laravel encrypt.

Encoding ID in `loaded` hook then decoding it in `before` manually might work.

**Comment by mike2410** [comment]
Might give this a shot thanks. Feel like the docs should really include a word or two about testing ;-)
