### ISSUE TITLE
[BUG]  Error in render: "TypeError: _.get is not a function"

### ISSUE THREAD

**Issue by skillcraft-io** [laraform/laraform#119]
### Prerequisites

* [X] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [X] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [X] Your issue isn't already filed.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 7.4.7
* Laravel version: 7.19
* Laraform Vue package version and type: 1.2.4
* Laraform Laravel package version: 1.2.1 Pro

### Description

An issue has appeared with the Finish button within a Wizard..it does not show and this is the error in the console:

`[Vue warn]: Error in render: "TypeError: _.get is not a function"

found in

---> <FormWizardPrevious> at src/themes/bs4/components/FormWizardPrevious.vue
       <FormWizardControls> at src/themes/bs4/components/FormWizardControls.vue
         <Laraform> at src/components/Laraform.vue
           <Root>`

### Steps to Reproduce

Create a wizard from only the back end, using BS4 Theme and the default component. I used 3 Sections and 1 field per, but i don't think it matters, several configurations yielded the same error.

**Expected behavior:**

I would have expected the finished/submit button to display on the final step to submit the form.

**Actual behavior:** 

No Button to submit and console errors :(

### Additional Information

None.

**Comment by adamberecz** [comment]
Strange @zhxscript, I'm not getting this error. Do you have `lodash` installed as peer dependency? If yes, please provide a full example to reproduce, because the issue is probably somewhere else than the wizard component. Also the exact error message with line would be helpful, because couldn't find a single `_.get` call in any wizard components directly.

**Comment by skillcraft-io** [comment]
@adamberecz - Thanks for the response..

It appears this issue is related to a conflict with CoreUI, but only when the wizard loads and only on the final page...I was able to get the wizard working by changing the order of scripts loading on a page. I will close this as this does not appear to be a Laraform issue .
