### ISSUE TITLE
Issues with file attached to entry

### ISSUE THREAD

**Issue by gmartinez** [laraform/laraform#12]
This is what I have;

1. schema;

>return [
	'guid' => [
		'type' => 'key',
		'secret' => true
	],
	'otype' => [
		'type' => 'hidden',
		'default' => 'mandm',
		'attribute' => 'type'
	],
	'name' => [
		'type' => 'text',
		'label' => 'Title',
		'rules' => 'required'
	],
	'_props->pointer' => [
		'type' => 'file',
		'drop'=> true
	]
];

Creating a new entry works ok, file gets uploaded and saved where it is expected, the problem is that the file uploaded ended up in its destiny folder not with its original file name but with a char(40) hash so in my case stick.png got saved as FgSK94lhmPcP9GLqtxmvI4Z3r3IJYr39eFCeYYuR.png

Thoughts ?

**Comment by laraform** [comment]
Yes, that's the basic behavior but you can always create a custom store logic:
https://laraform.io/docs/1.x/how-tos/uploading-files#custom-store-function

In the second example you can see the store closure receives the `$file` as the first argument, which is in fact `Illuminate\Http\UploadedFile` object and has a `getClientOriginalName()` method.

**Comment by gmartinez** [comment]
Mmm, ok, I guess you have your reasons, I guess related to the issue of overwriting files when loading to same directory, but honestly when you think about it is not very intuitive, 

IMO, it'd be better to return an error based on having a property that allows to control the behavior of overwrite (bool, false by default).

My 2cts.
