### ISSUE TITLE
[QUESTION] Apply Steps

### ISSUE THREAD

**Issue by skillcraft-io** [laraform/laraform#120]
### Prerequisites

* [X] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [X] Your question isn't already asked before.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 7.4.7
* Laravel version: Latest
* Laraform Vue package version and type: Latest Pro
* Laraform Laravel package version: Latest Pro

### Description

How can one apply a "step" to a number field?

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by adamberecz** [comment]
Do you mean `number` input type? Then [inputType](https://laraform.io/docs/1.x/reference/text-element#option-inputType) option is what you're looking for.

**Comment by skillcraft-io** [comment]
No, I know about the inputType... but that only allows whole number increases

For example:
`<input type="number" id="points" name="points" step=".25">`

The number should be .25, .50, .25,1.00 or 1.25 or 1.50, etc. (.25 increase at a time)

**Comment by adamberecz** [comment]
Yeah, now I see. I'm afraid you have to create a custom text input component to do that, but I've added this to the list of feature requests.
