### ISSUE TITLE
[BUG] Can not submit form

### ISSUE THREAD

**Issue by mohammed-alfarra** [laraform/laraform#121]
### Prerequisites

* [ X ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [ X ] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [ X ] Your issue isn't already filed.
* [ X ] You filled in the entire issue template.

### Versions

* PHP version: **7.2.5**
* Laravel version: **7.0**
* Laraform Vue package version and type: **laraform@1.2.2 community** 
* Laraform Laravel package version: **community 1.2.0**

### Steps to Reproduce

**app.js**
```
require('./bootstrap');

import Vue from 'vue'
import Laraform from 'laraform'

Vue.use(Laraform)
```

**Form**
```<?php

namespace App\Forms;

use App\Models\User\Project;

class RegisterForm extends \Laraform
{
    public $model = Project::class;

    public function schema()
    {
        return [
            'email' => [
                'type' => 'text',
                'placeholder' => 'Email address',
                'rules' => 'required|email'
            ],
            'ip' => [
                'type' => 'meta'
              ],
        ];
    }

    public function buttons()
    {
        return [[
            'label' => 'Submit'
        ]];
    }
}
```

**Route**
`Route::get('/', function () {
    return view('welcome', [
      'form' => app('App\Forms\RegisterForm')
    ]);
  });`

**Welcome blade**
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>Laravel</title>

        
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        
        <link rel="stylesheet" type="text/css" href="/css/app.css">
    </head>
    <body>
        <div id="app">
            {!! $form->render() !!}
          </div>

          <script src="/js/app.js"></script>
    </body>
</html>

**Migration**
`Schema::create('projects', function (Blueprint $table) {
            $table->id();
            $table->string('email');
            $table->timestamps();
        });`

**app.scss**
```
// Fonts
@import url('https://fonts.googleapis.com/css?family=Nunito');

// Variables
@import 'variables';

// Bootstrap
@import '~bootstrap/scss/bootstrap';

@import 'laraform/src/themes/default/scss/theme.scss';
```

**Model**
```
<?php

namespace App\Models\User;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $guarded = [];
}
```

**Issue**
![image](https://user-images.githubusercontent.com/21202883/87872632-fcc79c80-c9c2-11ea-9dba-e66ea2fcabba.png)

**Comment by adamberecz** [comment]
I think you've missed the `php artisan vendor:publish` command.

**Comment by mohammed-alfarra** [comment]
> I think you've missed the `php artisan vendor:publish` command.

I publish the vendors exactly as it came in documentation.

**Comment by adamberecz** [comment]
It seems like `validateOn` option is receiving a `null` value which usually occurs when the backend config is not published on a fresh install. Could you also copy here the `config/laraform.php` file from your project?

**Comment by mohammed-alfarra** [comment]
> It seems like `validateOn` option is receiving a `null` value which usually occurs when the backend config is not published on a fresh install. Could you also copy here the `config/laraform.php` file from your project?

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Forms' path
    |--------------------------------------------------------------------------
    |
    | Namespace where form classes can be found.
    |
    */
    'path' => 'App\\Forms',

    /*
    |--------------------------------------------------------------------------
    | Vue component
    |--------------------------------------------------------------------------
    |
    | Default Vue component.
    |
    */
    'component' => 'laraform',

    /*
    |--------------------------------------------------------------------------
    | Theme
    |--------------------------------------------------------------------------
    |
    | Default theme.
    |
    */
    'theme' => 'default',

    /*
    |--------------------------------------------------------------------------
    | Theme
    |--------------------------------------------------------------------------
    |
    | Default form layout. If `false` no layout will be used.
    |
    */
    'layout' => false,

    /*
    |--------------------------------------------------------------------------
    | Labels
    |--------------------------------------------------------------------------
    |
    | Determines if the elements which do not have a `label` option defined
    | should have a label DOM element rendered.
    |
    */
    'labels' => false,

    /*
    |--------------------------------------------------------------------------
    | Form Errors
    |--------------------------------------------------------------------------
    |
    | Determines if errors should be displayed above form.
    |
    */
    'formErrors' => true,

    /*
    |--------------------------------------------------------------------------
    | Columns
    |--------------------------------------------------------------------------
    |
    | Default column settings.
    |
    */
    'columns' => [
        'element' => 12,
        'label' => 12,
        'field' => 12
    ],

    /*
    |--------------------------------------------------------------------------
    | Locale
    |--------------------------------------------------------------------------
    |
    | Default locale.
    |
    */
    'locale' => 'en_US',

    /*
    |--------------------------------------------------------------------------
    | Validate On
    |--------------------------------------------------------------------------
    |
    | When user inputs should be validated.
    | 
    | Possible values: 
    |   submit: upon form submission
    |   change: instantly upon user input
    |   step: before moving to the next step when using Wizard
    |
    */
    'validateOn' => 'submit|change',

    /*
    |--------------------------------------------------------------------------
    | Endpoint
    |--------------------------------------------------------------------------
    |
    | Default endpoint where the form should submit.
    |
    */
    'endpoint' => '/laraform/process',

    /*
    |--------------------------------------------------------------------------
    | Method
    |--------------------------------------------------------------------------
    |
    | Default method how the form should be submitted.
    |
    */
    'method' => 'POST',

    /*
    |--------------------------------------------------------------------------
    | Elements
    |--------------------------------------------------------------------------
    |
    | A list of custom elements to be added to Laraform.
    |
    | eg. [
    |  'custom' => App\Elements\CustomElement::class,
    | ]
    |
    */
    'elements' => [],
];
```

**Comment by skillcraft-io** [comment]
Not sure if it matters, but you have assigned a model to the form, but not defined the fillable attributes on the model.. Did you try to define the fillable attributes array on your model?

**Comment by adamberecz** [comment]
I'm not able to reproduce the error, even though I tried with the exact files you've sent. The reason while you're receiving this error is most probably because `validateOn` is null in the main Laraform component, we only need to find out why. Check out the `form` prop of `<Laraform>` component. What does it have for `validateOn`? You might also copy the actual component rendered in the html before it gets mounted, because that's where it passes backend params to the frontend component. It should be something like this:

``` html
<laraform :form="{&quot;key&quot;:&quot;eyJpdiI6ImRFbHJtSy9sYUxWZk9RSStzM2M1UHc9PSIsInZhbHVlIjoia0tCb3hLcFZ2TXVPTENOVGw2MFlOaUdOUWtkdWp6L1Z5RWpUSml1YjNscz0iLCJtYWMiOiI1YWJjYzVhNjhjYWIyOGRlMTEyOGRmOGNlOGYxZjcyMDhiMjljNjAwZGM2NzIzZmU5MWJhMTkwOTgzMjk1YTU0In0=&quot;,&quot;data&quot;:[],&quot;schema&quot;:{&quot;email&quot;:{&quot;type&quot;:&quot;text&quot;,&quot;placeholder&quot;:&quot;Email address&quot;,&quot;rules&quot;:&quot;required|email&quot;,&quot;name&quot;:&quot;email&quot;,&quot;component&quot;:&quot;text-element&quot;},&quot;ip&quot;:{&quot;type&quot;:&quot;meta&quot;,&quot;name&quot;:&quot;ip&quot;,&quot;component&quot;:&quot;meta-element&quot;}},&quot;theme&quot;:&quot;default&quot;,&quot;columns&quot;:{&quot;element&quot;:12,&quot;label&quot;:12,&quot;field&quot;:12},&quot;class&quot;:null,&quot;classes&quot;:null,&quot;labels&quot;:false,&quot;layout&quot;:false,&quot;formErrors&quot;:true,&quot;buttons&quot;:[{&quot;label&quot;:&quot;Submit&quot;}],&quot;with&quot;:[],&quot;messages&quot;:[],&quot;locale&quot;:&quot;en_US&quot;,&quot;endpoint&quot;:&quot;\/laraform\/process&quot;,&quot;method&quot;:&quot;POST&quot;,&quot;validateOn&quot;:&quot;submit|change&quot;}" ></laraform>
```
You might even try to render this exact component.

**Comment by mohammed-alfarra** [comment]
> I'm not able to reproduce the error, even though I tried with the exact files you've sent. The reason while you're receiving this error is most probably because `validateOn` is null in the main Laraform component, we only need to find out why. Check out the `form` prop of `<Laraform>` component. What does it have for `validateOn`? You might also copy the actual component rendered in the html before it gets mounted, because that's where it passes backend params to the frontend component. It should be something like this:
> 
> ```
> <laraform :form="{&quot;key&quot;:&quot;eyJpdiI6ImRFbHJtSy9sYUxWZk9RSStzM2M1UHc9PSIsInZhbHVlIjoia0tCb3hLcFZ2TXVPTENOVGw2MFlOaUdOUWtkdWp6L1Z5RWpUSml1YjNscz0iLCJtYWMiOiI1YWJjYzVhNjhjYWIyOGRlMTEyOGRmOGNlOGYxZjcyMDhiMjljNjAwZGM2NzIzZmU5MWJhMTkwOTgzMjk1YTU0In0=&quot;,&quot;data&quot;:[],&quot;schema&quot;:{&quot;email&quot;:{&quot;type&quot;:&quot;text&quot;,&quot;placeholder&quot;:&quot;Email address&quot;,&quot;rules&quot;:&quot;required|email&quot;,&quot;name&quot;:&quot;email&quot;,&quot;component&quot;:&quot;text-element&quot;},&quot;ip&quot;:{&quot;type&quot;:&quot;meta&quot;,&quot;name&quot;:&quot;ip&quot;,&quot;component&quot;:&quot;meta-element&quot;}},&quot;theme&quot;:&quot;default&quot;,&quot;columns&quot;:{&quot;element&quot;:12,&quot;label&quot;:12,&quot;field&quot;:12},&quot;class&quot;:null,&quot;classes&quot;:null,&quot;labels&quot;:false,&quot;layout&quot;:false,&quot;formErrors&quot;:true,&quot;buttons&quot;:[{&quot;label&quot;:&quot;Submit&quot;}],&quot;with&quot;:[],&quot;messages&quot;:[],&quot;locale&quot;:&quot;en_US&quot;,&quot;endpoint&quot;:&quot;\/laraform\/process&quot;,&quot;method&quot;:&quot;POST&quot;,&quot;validateOn&quot;:&quot;submit|change&quot;}" ></laraform>
> ```
> 
> You might even try to render this exact component.

Yes, the problem is because I did not provide inputs in Forms/TestForm.php for the all required fields in the database table.

**Comment by adamberecz** [comment]
So you managed to resolve?

**Comment by mohammed-alfarra** [comment]
> So you managed to resolve?

Yes, it's working now

**Comment by michaelambass** [comment]
If it can help someone that has the same issue.
I got the same error, **validateOn** prop was set to "null" as @adamberecz mentioned, fixed by refreshing the Laravel config cache.

`php artisan config:clear`
