### ISSUE TITLE
[QUESTION] Not set unfilled fields to null

### ISSUE THREAD

**Issue by skillcraft-io** [laraform/laraform#122]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.4.7
* Laravel version: 7.19.1
* Laraform Vue package version and type: 1.2.4 Pro
* Laraform Laravel package version: 1.2.1 Pro

### Description

I have assigned a model to my form, however there are a few attributes on the model that are not provided to the form, mostly because they are administration type fields... The form is processed by the auto processing Laraform provides/

However, when I submit the form the fields are set to NULL in the database.

Is there a way to prevent this from happening and just leave the field alone when using the auto-processing.

### Additional Information

**Comment by adamberecz** [comment]
What you can do is to manually set them to non-null values in [`before`](https://laraform.io/docs/1.x/basics/submitting-data#before-hook) hook.

**Comment by skillcraft-io** [comment]
thanks, it works fine.

I feel this is extra coding that should not need to be done, if I don't include the field in my form, then I would expect the data to persist and not be cleared.

I see the update method inside the Laraform\Database\Handler has $emptyOnNull parameter default is set to true. This to me would be a variable that should be configurable per form use, Do you have plans to enable over riding this to be false?

**Comment by adamberecz** [comment]
That sounds like a good proposition. I'll consider it in 2.0 - thanks!
