### ISSUE TITLE
[BUG] When using 'step' for 'validateOn', changes to fields aren't re-validated

### ISSUE THREAD

**Issue by patrickdaze** [laraform/laraform#124]
### Prerequisites

* [ ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [ ] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [X] Your issue isn't already filed.
* [ ] You filled in the entire issue template.

### Versions

* PHP version: N/a (using frontend standalone)
* Laravel version: N/a (using frontend standalone)
* Laraform Vue package version and type: 1.2.5 / pro
* Laraform Laravel package version: N/a (using frontend standalone)

### Description

When using `validateOn: 'step'`, changes to fields aren't re-validated when fields are changed after the initial validation.

### Steps to Reproduce

1. Load the form
2. Fill-in the field with valid data
3. Click Next
4. Go back to previous step (Back button or clicking step title)
5. Change valid field with invalid data
6. Click Next (or click next step title)
7. _wizard switches to next step instead of re-validating form_

**Expected behavior:**

When `validateOn` is set to `step` the expected bahavior is that the form is revalidated each time the wizard goes to **any other step**. This would also include going back, forwards, skipping to another step by clicking step title, or clicking "Finish" when on the last wizard step.

**Actual behavior:** 

When clicking "Next", enter key, or clicking next stage title the data is not re-validated. The invalid field is ignored and not re-validated.

### Additional Information

**html file**
```html
...
<div id="ppFApp">
	<application-form />
</div>
...
```

**app.js**
```javascript
import Vue from 'vue';
import Laraform from '@laraform/laraform/src';
import ApplicationForm from './ApplicationForm.vue';

Vue.use(Laraform);

new Vue({
	el: '#ppFApp',
	components: {
		ApplicationForm,
	}
});
```

**ApplicationForm.vue**
```html
<script>
export default {
	mixins: [Laraform],
	data: () => ({
		validateOn: 'step',
		wizard: {
			primary: {
				label: 'Primary Contact',
				elements: ['primaryContact'],
				buttons: {
					previous: false,
				}
			},
			business: {
				label: 'Business Profile',
				elements: ['businessProfileHeader', 'businessProfile'],
			},
		},
		schema: {
			primaryContact: {
				type: 'object',
				schema: {
					header: {
						type: 'static',
						content: `
							<div class="notification is-info is-light is-radiusless">
								<h1 class="title is-4 mb-0">Primary Contact</h1>
								<p>The primary contact…</p>
							</div>`,
					},
					email: {
						type: 'text',
						label: 'Email',
						rules: 'required|email',
					},
				}
			},
			businessProfileHeader: {
				type: 'group',
				schema: {
					header: {
						type: 'static',
						content: `
							<div class="notification is-info is-light is-radiusless">
								<h1 class="title is-4 mb-0">Business Profile</h1>
								<p>This business profile is…</p>
							</div>`,
					},
				}
			},
			businessProfile: {
				type: 'object',
				schema: {
					header: {
						type: 'static',
						content: `
							<div class="notification is-info is-light is-radiusless">
								<h1 class="title is-6 mb-0">General</h1>
							</div>`,
					},
					general: {
						type: 'object',
						schema: {
							name: {
								type: 'text',
								label: 'Business Name',
							},
						},
					},
				},
			},
		},
	})
}
</script>
```

**Comment by adamberecz** [comment]
Yes indeed this is how it should work, so I'll need some time to rewrite this part. Will let you know about the update! 

Using `'change|step'` as `validateOn` is not an option I guess, however that would solve it in the meantime.

**Comment by adamberecz** [comment]
@patrickdaze update is out in `1.2.6`: https://laraform.io/releases

**Comment by patrickdaze** [comment]
Works now, thanks!
