### ISSUE TITLE
[DOCS] 'info' and 'description' not documented

### ISSUE THREAD

**Issue by dancameron** [laraform/laraform#125]
### Description

 'info' and 'description' not documented yet work for mostly all input types.

### Example

```
'name' => [
    'type' => 'text',
    'label' => 'Form Name',
    'rules' => ['required'],
    'info' => 'Get weird! This name is private.'
],
```

**Comment by adamberecz** [comment]
The `description` option is [part of the docs](https://laraform.io/docs/1.x/reference/frontend-element#option-description) however `info` is indeed unofficial because it hasn't been tested with all the elements yet.
