### ISSUE TITLE
[QUESTION] Keep File Optional with Type/Size Rules

### ISSUE THREAD

**Issue by dancameron** [laraform/laraform#126]
### Prerequisites

* [✅] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [✅] Your question isn't already asked before.
* [✅] You filled in the entire issue template.

### Versions

* PHP version: 7.x
* Laravel version: latest
* Laraform Vue package version and type: pro
* Laraform Laravel package version: latest

### Description

Struggling to find a way to set the rule for a file (upload) to be optional while keeping a rule for file type and size.

```
'rules' => 'file|mimes:png,jpg,jpeg|max:2048',
```

'required' is not included, although the form submission is prevented since "it must be a file".

**Comment by adamberecz** [comment]
Have you tried with [nullable](https://laraform.io/docs/1.x/basics/validation#rule-nullable)?

**Comment by dancameron** [comment]
I had not. Thank you.
