### ISSUE TITLE
[IDEA] Vue 3 support

### ISSUE THREAD

**Issue by karlerss** [laraform/laraform#127]
Is Vue 3 support in the roadmap?

**Comment by adamberecz** [comment]
Yes, with version 2.0 (coming 2020Q4-2021Q1) we'll have Vue 3 support. Maybe not in the first release, but soon after.

**Comment by abdul-alhasany** [comment]
@adamberecz 

Any update on this. I am trying to install laraform with vue3 but received this error:
```
Uncaught TypeError: Cannot read property 'BaseElementLayout' of undefined
```

I cloned the project and installed laraform with vue2 and it was working fine.

**Comment by adamberecz** [comment]
@kalimah-apps 2.0 is not out yet neither support for Vue 3. I'll post some updates soon, but its definitely coming in the next couple of months!
