### ISSUE TITLE
[QUESTION] How to load data into an object?

### ISSUE THREAD

**Issue by gabrielchavezme** [laraform/laraform#128]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.2.1
* Laravel version: 6.2.1
* Laraform Vue package version and type: 1.2.8
* Laraform Laravel package version: 1.2.8

### Description

Currently in the documentation it explains how to load a series of data as follows:

this.load ({
         name: 'John Doe'
})

Assuming you have a schema like this:

```
schema: {
    name: {
        type: 'text',
        label: 'Name'
    }
}
```

But how can I complete an object, something like the following:

```
schema: {
    list: {
        type: 'list',
        label: 'Data',
        object: {
            schema: {
                name: {
                    type: 'text',
                    label: 'Name'
                },
                lastname: {
                    type: 'text'.
                    label: 'Lastname'
                }
            }

        }
    }
}
```
I've been going through the documentation but couldn't find anything related to this.

### Additional Information

https://laraform.io/docs/1.x/reference/list-element
https://laraform.io/docs/1.x/reference/object-element

**Comment by J1Duran** [comment]
It would be nice if you could solve this, I have this same question.

**Comment by adamberecz** [comment]
Data should be loaded in the same format as you receive the output. So in this case: 

``` js
this.load({
  list: [
    { name: 'John', lastname: 'Doe' },
    { name: 'Jane', lastname: 'Doe' },
  ]
})
```
