### ISSUE TITLE
File deletion does not physically delete the file

### ISSUE THREAD

**Issue by gmartinez** [laraform/laraform#13]
File pointer gets deleted from database record property, but not physically from filesystem, I tried not setting prunable property and also setting it to be true, same result.

**Comment by laraform** [comment]
This should work with `prunable` set to `true` on the file element. Could you send the schema and the used disk option from config/filesystem?

**Comment by gmartinez** [comment]
Tried that already, I just did another attempt, here is the schema;

> return [
            'guid' => [
                'type' => 'key',
                'secret' => true
            ],
            'otype' => [
                'type' => 'hidden',
                'default' => 'mandm',
                'attribute' => 'type'
            ],
			'name' => [
                'type' => 'text',
                'label' => 'Title',
				'rules' => 'required'
            ],
            '_props->product' => [
				'type' => 'select',
				'label' => 'Product',
				'items' => config('_app.products'),
				'search' => true
			],
            '_props->type' => [
				'type' => 'select',
				'label' => 'Type',
				'items' => config('_app.asset_type'),
				'search' => true
			],
			'_props->category' => [
				'type' => 'select',
				'label' => 'Category',
				'items' => config('_app.asset_category'),
				'search' => true
			],
			'_props->pointer' => [
				'type' => 'file',
                'drop' => true,
                'prunable' => true
            ],
            'status' => [
                'type' => 'toggle',
                'falseValue' => 'unpublished',
                'trueValue' => 'published',
                'text' => 'Published?'
            ]
        ];

Upon removing the file and then submit the _props->pointer property gets correctly set to null, but the physical file is not deleted.

**Comment by laraform** [comment]
Did you manage to resolve it? If not please send example with model & migration.

**Comment by gmartinez** [comment]
Table looks like;

CREATE TABLE objects (
guid char(40) COLLATE utf8mb4_unicode_ci NOT NULL,
name varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
type varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
status varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
_props longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
UNIQUE KEY objects_guid_unique (guid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Model has nothing special, looks like;

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Arr;
use Laravel\Scout\Searchable;

class Obj extends Model
{
use Searchable;
//
protected $connection;
protected $table = 'objects';
protected $primaryKey = 'guid';
protected $keyType = 'string';
protected $casts = [
'_props' => 'json',
];
public $incrementing = false;
}

**Comment by laraform** [comment]
Hi! I've created a new bug report template, so if you still have the issue please resubmit accordingly: https://github.com/laraform/laraform/issues/new?assignees=&labels=bug&template=1_bugs.md&title=%5BBUG%5D

(make sure it's isolated and does not require any other dependency than Laraform & Laravel and you have a full class of everything related to it)
