### ISSUE TITLE
[QUESTION] Disable option inside select element

### ISSUE THREAD

**Issue by basvandertogt** [laraform/laraform#133]
### Prerequisites

* [X] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [X] Your question isn't already asked before.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 7.4
* Laravel version: 5.6
* Laraform Vue package version and type: 1.2.9 Pro
* Laraform Laravel package version: 1.2.2

### Description

Is there a way to add a disabled attribute to some of the options inside a select element in the backend?

```
$seminars = Seminar::where('club_id', $club)->get();

$seminarData = [];
foreach ($seminars as $seminar) {
    $seminarData[] = [
        'value' => $seminar->id,
        'label' => $seminar->name,
        'disabled' => $seminar->noSeatsAvailable
    ];
}
```

In this example disabled can be true or false.

**Comment by adamberecz** [comment]
That's not possible currently out of the box, so you need to create a custom [`option` slot](https://laraform.io/docs/1.x/reference/select-element#slot-option).

Here's a quick implementation on how you can do that:
``` vue
<script>
  import Vue from 'vue'

  export default {
    mixins: [Laraform],
    data() {
      return {
        schema: {
          select: {
            slots: {
              option: Vue.extend({
                props: ['el$', 'option', 'search'],
                template: `
                  <span v-if="option.disabled" style="opacity: 0.6; display: block" @click.stop.prevent="">{{ option.label }}</span>
                  <span v-else>{{ option.label }}</span>
                `
              })
            }
          }
        }
      }
    }
  }
</script>
```

What is important is that you have `@click.stop.prevent=""` and `style="display: block"` on the disabled option, everything else is up to you to customize / style.

**Comment by basvandertogt** [comment]
Awesome! This is exactly what i needed. Thank you.
