### ISSUE TITLE
[QUESTION] Fire Custom Rule only on Blur

### ISSUE THREAD

**Issue by skillcraft-io** [laraform/laraform#135]
I wanted to know how we can, or the best way to go about firing off a custom async rule, not based on debouncing, but essentially when the user navigates off the field.

I have an email field, part of my form, which I want to send a code after they have entered the email address so that once the code is sent, a new field shows and asks for the code just sent...

**Comment by adamberecz** [comment]
I'm afraid that's not possible with the current setups @zhxscript :/ You need create a custom version of TextElement (or an EmailElement eg.) and define a @change/@blur event on the input field.

**Comment by basvandertogt** [comment]
I need the blur event too. I have a postcode and house nr field which calls an API to fetch the address and city. Now i'm using the change event but than the API call is done multiple times (after every input). Not quite nice. Is there an other way? Something like a timeout after stop typing @adamberecz ?

**Comment by adamberecz** [comment]
I'd recommend lodash's debounce feature for this:
https://lodash.com/docs/4.17.15#debounce
