### ISSUE TITLE
[BUG] `this.on('next')` and others are not triggered

### ISSUE THREAD

**Issue by tonydotgit** [laraform/laraform#136]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.2.x
* Laravel version: 8.9.0
* Laraform Vue package version and type: 1.2.9 pro
* Laraform Laravel package version: 1.2.2 pro

### Description

I'm trying to perform some custom stuff when the use clicks the "next" button in a wizard, also when a form is invalid once performed local validations (without XHR/external requests).

The problem is, that the events that are supposed emitted either on the form or wizard are not hapening.

### Steps to Reproduce
Create your own 2-3 pages wizard with text inputs and selects and use this component:
```
<script>
export default {
  name: 'DefaultForm',

  mixins: [Laraform],

  created() {
    this.on('submit', (response) => {
      console.log('not happening on submit')
    })

    this.on('next', (response) => {
      console.log('not happening on next')
    })

    this.on('fail', (response) => {
      console.log('not happening on local validations fails, only for external validations')
    })
  },
}
</script>
```

**Expected behavior:**

I would expect that these events were triggered "on-next" (so when the next button is clicked and the wizard moves to the next page), "on-fail" (so anytime it fails, no matter if is a local or external validation), etc.

**Actual behavior:** 

"on-next" is not happening, "on-fail" only happens when the form validates remotely, it doesn't trigger for failed local validations.

### Additional Information

Events reference:
- https://laraform.io/docs/1.x/reference/frontend-wizard#event-next
- https://laraform.io/docs/1.x/reference/frontend-form#event-fail

**Comment by adamberecz** [comment]
Submit works fine on my end, when Finish button is clicked. The `next` is an event of the wizard component and `fail` indeed indicates a server response with `fail` status and not failed validation.

Here's how you can deal with `next` and `fail`:

``` vue
<script>
export default {
  name: 'DefaultForm',

  mixins: [Laraform],

  // Watch for the state of `invalid` to catch failing validators 
  watch: {
    invalid(newValue, oldValue) {
      console.log(newValue ? 'some validator fails' : 'no validator fails')
    }
  },

  created() {
    // This should work on `Finish`
    this.on('submit', (response) => {
      console.log('not happening on submit')
    })

    // This way it should work
    this.wizard$.on('next', (response) => {
      console.log('not happening on next')
    })

    // Replaced with watcher
    // this.on('fail', (response) => {
    //   console.log('not happening on local validations fails, only for external validations')
    // })
  },
}
</script>
```

**Comment by tonydotgit** [comment]
@adamberecz ok that makes sense, ty man!
