### ISSUE TITLE
[QUESTION] Displaying ImageElement drop area using inline elements

### ISSUE THREAD

**Issue by rajaneeshdwivedi** [laraform/laraform#137]
### Prerequisites

* [X] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [X] Your question isn't already asked before.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 7.3.23
* Laravel version: 8.12.3
* Laraform Vue package version and type: 2.5.22 pro
* Laraform Laravel package version: 1.2.9 pro

### Description

When using a backend-only schema, I've got the Image upload element type displaying the drop zone correctly. I need to do some custom layout so am using \<template\>\<form\>\<TextElement /\> etc. as described in the Customizing Layout → Inline Elements section of the docs. This is all fine for text elements, but when adding \<ImageElement /\>, although the element displays, it doesn't show the drop area. Not sure what I'm missing here as the docs only seem to refer to TextElement for inline elements.

### Additional Information

This is how I have it set up:
```
<template>
	<form @submit.prevent="submit">
		<TextElement
		name="username"
		:schema="schema.username"
		v-ref:elements$ 
		/>
		<ImageElement
		name="icon512"
		:schema="schema.icon512"
		v-ref:elements$ 
		/>
	</form>
</template>

<script>
  export default {
    mixins: [Laraform]
  }
</script>
```

which renders like this:
![image](https://user-images.githubusercontent.com/10547484/98233160-e2f49a00-1f5e-11eb-8157-df95e6a395e1.png)

instead of this:
![image](https://user-images.githubusercontent.com/10547484/98233269-1505fc00-1f5f-11eb-9584-a577cb5b777c.png)

**Comment by adamberecz** [comment]
Could you share the backend schema?

**Comment by rajaneeshdwivedi** [comment]
Sure:
```
public function schema()
{
	return [
		'id' => [
			'type' => 'key'
		],
		"username" => [
			"type" => "text",
			"label" => "Your name",
			"rules" => "required",
		],
		"icon512" => [
			"type" => "image",
			"drop" => "true",
			"label" => "Icon 512x512",
			"rules" => "image|mimes:png|dimensions:min_width=512,max_width=512,min_height=512,max_height=512",
		]
	];
}

```

**Comment by adamberecz** [comment]
Just add `laraform-bs4` class to `<form>` tag and it'll be fine. (or `laraform-bs3` / `lf-form` for default)

**Comment by rajaneeshdwivedi** [comment]
Sorted - thanks so much
