### ISSUE TITLE
Uploaded files not stored in database

### ISSUE THREAD

**Issue by matteopolati** [laraform/laraform#138]
### Description
First of all I want to congratulate you on the excellent work.
However the documentation is not very clear for me, especially on the subject of uploading. I've been trying for a few hours to understand how save uploaded content into db. Files does get uploaded to the local disk but not stored in db.

`exception: "Symfony\Component\Debug\Exception\FatalThrowableError"
file: "../vendor/laraform/laraform-laravel/src/Database/Handler.php"
line: 158
message: "Call to a member function save() on null"`

My issue is very similar to the one reported here https://github.com/laraform/laraform/issues/18. 

I have already tried the proposed solution without success.

Please help me.

:-)

**Comment by adamberecz** [comment]
Thanks @gongon2dotcom ! It's still a long way to go but I'm glad you like Laraform!

Based on the error message I can only think of a similar solution than at #18 . You sure ID is added to the element list? Maybe posting the full schema would help.

**Comment by matteopolati** [comment]
I've solved with a custom 'after' function that create new 'Subscriber' Model then store attachments with Laravel 'Storage' class.
Thanks anyway.
