### ISSUE TITLE
[BUG] default option not working for hidden element

### ISSUE THREAD

**Issue by basvandertogt** [laraform/laraform#139]
### Prerequisites

* [X] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [X] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [X] Your issue isn't already filed.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 7.4.5
* Laravel version: 5.6
* Laraform Vue package version and type: 1.2.8 PRO
* Laraform Laravel package version: 1.2.2

### Description

The default option for the hidden element does not work. The value keeps empty.

### Steps to Reproduce

```
'workflow_id'     => [
    'type'    => 'hidden',
    'default' => '123'
],
```
**Expected behavior:**

```
<input type="hidden" name="workflow_id" id="workflow_id" value="123">
```

**Actual behavior:** 

```
<input type="hidden" name="workflow_id" id="workflow_id" value="">
```

### Additional Information

https://laraform.io/docs/1.x/reference/hidden-element

**Comment by adamberecz** [comment]
I'm not able to reproduce this as I'm getting the correct default value. You sure nothing clears the value once the form is loaded?
