### ISSUE TITLE
[QUESTION] Table/grids views for submitted data?

### ISSUE THREAD

**Issue by jechaviz** [laraform/laraform#140]
I'm wondering if you have out of the box also view for each form. I have read the documentation, but i couldn't find it. Thank you.
Just like these https://github.com/Okipa/laravel-table
![Generate tables from Eloquent models](https://raw.githubusercontent.com/Okipa/laravel-table/master/docs/laravel-table-preview.png)
or this
https://github.com/Gustavinho/laravel-views

**Comment by adamberecz** [comment]
Right now we don't have this @jechaviz, but probably will be published as a separate package once we get there. Currently the development of the next version is in progress.

**Comment by jechaviz** [comment]
Thank you for your prompt answer.

I just want to address this package, maybe to work in an admin panel combination version 

https://github.com/tuandm/laravue
