### ISSUE TITLE
[IDEA] form.io like drag and drop schema builder?

### ISSUE THREAD

**Issue by jechaviz** [laraform/laraform#141]
Have you thought in create a drag and drop schema builder?
### Description
I'm getting this from here
https://github.com/OrchardCMS/OrchardCore/issues/2621
![formioorchard](https://user-images.githubusercontent.com/31166005/47971395-a253a480-e056-11e8-91fa-ff31c1ad8085.gif)

A play ground says more than 1000 words:
https://codepen.io/travist/pen/xVyMjo
http://formio.github.io/formio.js/app/builder

### Additional Information
There are works already related to this:
https://github.com/OrchardCMS/OrchardCore

Also Check
https://github.com/Draggable/formeo
[![formeo-demo](https://user-images.githubusercontent.com/1457540/54798148-72c3c400-4c14-11e9-9d3f-bafe1ce0c8c1.gif)](https://draggable.github.io/formeo/)

**Comment by adamberecz** [comment]
This is also in plan. First we need to have a very strong basic library, then we can move on to adding features like this. All this takes time, but I'm sure in the end it will worth it.

Btw these seem nice!

**Comment by jechaviz** [comment]
Form.io is a mature product, but it started with the visual thing (multicolumn, conditions, jsonlogic, and so on), and they works with standar json

then they later added the more fields. If you see your code, some of the models done in the  backend are easily passed as params in the front end, through json, so we can avoid to repeat our selves sending the validation logic through the api call. 

I have explored this projects js to jsonlogic and jsonlogic to js, also jsonlogic to php. 

https://github.com/jwadhams/json-logic-php/
https://github.com/krismuniz/js-to-json-logic
https://github.com/jwadhams/json-logic-js
 
Also the php arrays depend of php, but json doesn't. It would be better to write the logic of the forms in json and the parse them as php array. In this way we can store all the form in the db and render it in the front view, just like form.io does.

Also I have tought you don't need to build the drag and drop builder yourself. Form.io has its core opensourced and self-hosteable,  and they expose their created json, so the only thing, we need to build a plugin to convert their json to your json or php array. 

I have found a very amazing project that converts and query a json to convert it in another called jsonata, and it's really intuitive and fast to learn

https://jsonata.org

So in this way we can short-path the change, and start rigth away with the builder, using form-io as external compatible tool. It's really similar to your way to do the things, let's say columns, groups, validation and so on. 

____________________________

I also want to address, form-io includes api automatic creation, table view for submisions... you can create a free trial account to see their visual concepts. 

The strong point is you have it all in the backend.

https://prnt.sc/vqqg6i

Thank you for your attention

**Comment by jechaviz** [comment]
Another completly different approach is to start building the web forms from tables, like airtable.

Look at this opensource project

https://baserow.io

I'm not able to give you a gif this time, but i'll try later.

**Comment by adamberecz** [comment]
See my answer here:
https://github.com/laraform/laraform/issues/142#issuecomment-735358724

The same applies to this: everything you define in the backend is passed to the frontend Vue component as a JSON, so actually there's no need to implement the logic on the frontend too (only things you need to add on there, like subscribing to frontend events).

**Comment by jeremiahsherrill** [comment]
Do we know if there is any kind of time table on this feature.
