### ISSUE TITLE
[QUESTION]  Holistic Tutorial to get something done.

### ISSUE THREAD

**Issue by jechaviz** [laraform/laraform#143]
Could you create an **holistic** tutorial just like this example to get something done?
I was thinking in a invoice form - simple app. It needs to take care about relationships, columns design, events, ..., a lot of what your package does.

See this example:
https://www.positronx.io/laravel-traits-example/

Thank you.

**Comment by adamberecz** [comment]
Tutorials are also in plan. I know they're super useful and this will be one of the first things to do when after the never version of Laraform is release. Thanks for the input!
