### ISSUE TITLE
[IDEA] https://laravelactions.com integration?

### ISSUE THREAD

**Issue by jechaviz** [laraform/laraform#144]
From the page: https://laravelactions.com (https://github.com/lorisleiva/laravel-actions)
This package introduces a new way of organising the logic of your Laravel applications by focusing on the actions your application provide.

Similarly to how VueJS components regroup HTML, JavaScript and CSS together, Laravel Actions regroup the authorisation, validation and execution of a task in one class that can be used as an invokable controller, as a plain object, as a dispatchable job, as an event listener and as an artisan command.

![Cover picture](https://user-images.githubusercontent.com/3642397/58073806-87342680-7b9b-11e9-9669-df35fba71f6b.png)

**Comment by adamberecz** [comment]
I wasn't familiar with this, but will look into it after next release - thanks. Also there will be more opportunities to contribute to the backend package with v2, so the community will be able implement useful stuff like this even if it's out of our current roadmap.
