### ISSUE TITLE
[QUESTION] How to validate if a field is different in a list?

### ISSUE THREAD

**Issue by gabrielchavezme** [laraform/laraform#145]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.2.1
* Laravel version: 6.2.1
* Laraform Vue package version and type: 1.2.9 pro
* Laraform Laravel package version: 1.1.9 pro

### Description

When creating a list, I try to validate if the fields entered are not repeated, apparently if I do it outside a list it works without problems, but when a "different" validation is added inside a list object everything breaks.

### Additional Information

My code:

```
my_list: {
    type: 'list',
    label: 'MY LIST',
    object: {
        schema: {
            my_item_list: {
                type: "text",
                label: "MY ITEM LIST",
                columns: 3,
                rules: [
                    'different:my_list.*.my_item_list'
                ],
            },
        }
    }
}
```
The error I get is: 

> [Vue warn]: Error in nextTick: "Error: my_list.my_item_list element does not exist"

![Captura de Pantalla 2020-12-01 a la(s) 2 10 08](https://user-images.githubusercontent.com/28960114/100714218-128a9c80-337b-11eb-8bf6-53be440ef045.png)

Am I making a mistake or is it a bug in the library?

**Comment by adamberecz** [comment]
What you're looking for is [distinct](https://laraform.io/docs/1.x/basics/validation#rule-distinct) rule:

``` js
my_list: {
    type: 'list',
    label: 'MY LIST',
    object: {
        schema: {
            my_item_list: {
                type: "text",
                label: "MY ITEM LIST",
                columns: 3,
                rules: [
                    'distinct'
                ],
            },
        }
    }
}
```

**Comment by gabrielchavezme** [comment]
> What you're looking for is [distinct](https://laraform.io/docs/1.x/basics/validation#rule-distinct) rule:
> 
> ```js
> my_list: {
>     type: 'list',
>     label: 'MY LIST',
>     object: {
>         schema: {
>             my_item_list: {
>                 type: "text",
>                 label: "MY ITEM LIST",
>                 columns: 3,
>                 rules: [
>                     'distinct'
>                 ],
>             },
>         }
>     }
> }
> ```

I didn't really pay attention to the documentation and I didn't realize this rule existed.

I have tried and it was what I was looking for, thank you very much !!!
