### ISSUE TITLE
[QUESTION] Can you select all the elements of a select?

### ISSUE THREAD

**Issue by gabrielchavezme** [laraform/laraform#146]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.4
* Laravel version: 6.2.1
* Laraform Vue package version and type: 1.2.9 pro
* Laraform Laravel package version: 1.1.9 pro

### Description

I would like to be able to know if there is any native way in Laraform to select or deselect all elements of a multiselect.

It would be amazing to be able to interact with a button where you can select all the elements to save some time.

### Additional Information

When you have 5 or 10 elements it is easy to be able to select them all one by one but when you have more elements it becomes a slow and tedious process for the user.

**Comment by adamberecz** [comment]
It seems like I've overlooked this issue @gabrielchavezme, sorry. There's no out of the box options for this if that's your question but you can always access an element with [el$](https://laraform.io/docs/1.x/reference/frontend-form#method-el$) and programmatically [update](https://laraform.io/docs/1.x/reference/frontend-element#method-update) its value.

**Comment by gabrielchavezme** [comment]
> It seems like I've overlooked this issue @gabrielchavezme, sorry. There's no out of the box options for this if that's your question but you can always access an element with [el$](https://laraform.io/docs/1.x/reference/frontend-form#method-el$) and programmatically [update](https://laraform.io/docs/1.x/reference/frontend-element#method-update) its value.

It would be amazing if it could be part of the next version, it would add some important functionality in the select.

Thank you very much @adamberecz , the package is great.
