### ISSUE TITLE
Cannot disable submit button via backend form

### ISSUE THREAD

**Issue by JonathanMMann** [laraform/laraform#147]
### Description
I'm expecting to be able to add a disabled field to my button on the backend form. However, when I do this I receive a frontend JS error: this.button.disabled.call is not a function

### Steps to reproduce
*Provide steps to reproduce this issue*
1. Create a form
2. Add a button function
3. Add a disabled field to the button

### Code
  public function buttons() {
    return [[
      'label' => 'Submit',
      'class' => 'btn-primary',
      'disabled' => true
    ]];
  }

### Your environment
* Brave 1.16.76
* Operating System: Mac OS Catalina

**Comment by adamberecz** [comment]
This is because [`disabled`](https://laraform.io/docs/1.x/reference/frontend-button#option-disabled) expects a function on the frontend, not a `boolean` value.
