### ISSUE TITLE
[QUESTION] Validation: recommended way of requiring at least one of multiple fields being filled

### ISSUE THREAD

**Issue by rajaneeshdwivedi** [laraform/laraform#148]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.3.23
* Laravel version: 8.12.3
* Laraform Vue package version and type: 2.5.22 pro
* Laraform Laravel package version: 1.2.9 pro

### Description

There's a section in my form with multiple social media URLs and the intention is to ensure that at least one is filled. I haven't seen this case being mentioned in the docs. I thought about using custom/conditional rules on each field being required if all of the others in the group are empty. Was wondering if there's a neater or recommended way of achieving this.

### Additional Information

I guess a similar situation could arise if requiring that EITHER a landline phone number OR a mobile phone number be provided.

**Comment by adamberecz** [comment]
Yeah, right now you can use conditional rules. I'll save a note for myself to come up with something more handy for this use case in the future.
