### ISSUE TITLE
[BUG] Failed custom backend rule inserts a new record anyway

### ISSUE THREAD

**Issue by rajaneeshdwivedi** [laraform/laraform#150]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.3.23
* Laravel version: 8.12.3
* Laraform Vue package version and type: 2.5.22 pro
* Laraform Laravel package version: 1.2.9 pro

### Description

I've created a custom rule on the backend (without any frontend validation), as-per the [Uppercase example](https://laraform.io/docs/1.x/how-tos/creating-rule#creating-backend-rule) in the docs. The validation fails properly and in before(), $this->isInvalid() returns true. However, the processing then goes on to insert the record.

Is this the expected behaviour? Are we meant to manually 'abort' the rest of the form processing?

### Steps to Reproduce

Happy to prepare a minimal example if required.

**Expected behavior:**

I would expect the record to not be inserted or updated.

**Actual behavior:** 

The record is inserted / updated.

### Additional Information

No additional information

**Comment by adamberecz** [comment]
This is not the expected behavior if `isInvalid()` returns true. If you could create a minimal example that would be helpful!

**Comment by rajaneeshdwivedi** [comment]
My mistake - turns out I was doing some additional processing further downstream which was saving the entity. Backend rule alone working just fine.
