### ISSUE TITLE
[QUESTION] How to use multiple-namespaces for different forms

### ISSUE THREAD

**Issue by tonydotgit** [laraform/laraform#151]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.3.x
* Laravel version: 8.24.x
* Laraform Vue package version and type: 1.2.9 pro
* Laraform Laravel package version: 1.2.2 pro

### Description

How to tell laraform's backend to dynamically handle forms from different namespaces?
I know that I can define the namespaces where the forms are stored `'path' => 'App\\Forms',` however I've forms within sub-namespaces: `\App\Forms\MX\Form11` & `\App\Forms\US\Form1`.

**Comment by adamberecz** [comment]
If you check out `vendor/laraform/laraform-laravel/src/Process/AutoProcess.php@12` you can see that the `config.path` is used along with `$request->key` to retrieve a backend form:
```php
12 |      $form = app(config('laraform.path') . '\\' . decrypt($request->key));
```

Now Laraform's `getFormKey()` is what creates the `$request->key`, which looks like this:
```php
public function getFormKey()
{
  return encrypt((new \ReflectionClass($this))->getShortName());
}
```

What you can do is create a new Laraform base class that overrides this method and adds an extra part to the path:
``` php
<?php

namespace App\Forms;

use \Laraform\Laraform as LaraformBase;

class Laraform extends LaraformBase
{
  public function getFormKey()
  {
    $reflection = new \ReflectionClass($this);
    $namespace = explode('\\', $reflection->getNamespaceName());
    return encrypt(end($namespace) . '\\' . $reflection->getShortName());
  }
}
```

Then you can extend this in your sub-namespaced forms:
``` php
<?php

namespace App\Forms\US;

// Use this instead of \Laraform
use App\Forms\Laraform;

class TestForm extends Laraform
{
  public function schema()
  {
    return [
      'text' => [
        'type' => 'text',
      ],
    ];
  }

  public function buttons() {
    return [
      [
        'label' => 'Submit'
      ]
    ];
  }

  public function before() {
    dd('it works');
  }
}
```

**Comment by tonydotgit** [comment]
@adamberecz sorry. for the late reply, that works for me. Thank you!
