### ISSUE TITLE
[QUESTION] Change child field inside list element on change by sibling field

### ISSUE THREAD

**Issue by basvandertogt** [laraform/laraform#153]
### Prerequisites

* [X] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [X] Your question isn't already asked before.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 7.4
* Laravel version: 7.0
* Laraform Vue package version and type: 1.2.8
* Laraform Laravel package version: 1.2.2

### Description

I have a list element with an object wit 3 fields. When "is_computed" is set "strokes" value should be set to 0.
Ho can i accomplish this?

### Additional Information

```
'holes'                  => [
    'type'   => 'list',
    'label'  => 'Holes',
    'object' => [
        'schema' => [
            'number'      => [
                'type'      => 'text',
                'label'     => 'Hole',
                'inputType' => 'number',
                'disabled'  => true,
                'rules'     => ['required'],
                'columns'   => 2
            ],
            'strokes'     => [
                'type'       => 'text',
                'label'      => 'Slagen',
                'inputType'  => 'number',
                'rules'      => ['required'],
                'columns'    => 3
            ],
            'is_computed' => [
                'type'    => 'checkbox',
                'label'   => 'Niet gespeeld',
                'columns' => 3
            ],
        ]
    ]
],
```

**Comment by adamberecz** [comment]
You need to use a [frontend component](https://laraform.io/docs/1.x/basics/rendering#attach-frontend-component-optional) and [manually update](https://laraform.io/docs/1.x/basics/updating-data#updating-element-data) the `strokes` to `0` when `is_computed` is checked.
