### ISSUE TITLE
[QUESTION] Disable wizard step "click"

### ISSUE THREAD

**Issue by tonydotgit** [laraform/laraform#154]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.x
* Laravel version: 8.x
* Laraform Vue package version and type: 1.2.9/ pro
* Laraform Laravel package version: 1.2.3 / pro

### Description

```<?php
namespace App\Forms;

class WizardForm extends \Laraform
{
  public $component = 'wizatd-form';
  
  public function wizard() {
    return [
      'personal_details' => [
        'label' => 'Personal details',
        'elements' => ['firstname', 'lastname'],
        'buttons' => [
          'previous' => false
        ]
      ],
      'contact_details' => [
        'label' => 'Contact details',
        'elements' => ['email', 'phone'],
        'buttons' => [
          'previous' => false
        ]
      ]
    ];
  }
  ```

I was able to remove the back button from the form, however the wizard step's label is still clickable so anyone can jump to the previous step through it.  How I could disable it?

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by tonydotgit** [comment]
Not resolved yet*

**Comment by adamberecz** [comment]
Not the most beautiful solution, but it does the work:

``` js
mounted() {
  let wizard$ = this.wizard$

  wizard$.on('next', (a,b) => {
    this.$nextTick(() => {
      wizard$.previous$.$el.querySelector('a').addEventListener('click', () => {
        wizard$.lastEnabled$.select()
      })
    })
  })
}
```

**Comment by tonydotgit** [comment]
@adamberecz tysm, that works for me!
