### ISSUE TITLE
[BUG/feature request] Condition ['field_x', ['a','b']] resolution if field_x value is array

### ISSUE THREAD

**Issue by karlerss** [laraform/laraform#156]
### Prerequisites

* [ ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [ ] You filled in the entire issue template.

### Versions

* PHP version: 7.4.1
* Laravel version: 7
* Laraform Vue package version and type: 1.2.11 PRO
* Laraform Laravel package version: 1.2.3

### Description

Condition ['field_x', ['a','b']] if field_x value is array not working as expected.

### Steps to Reproduce

```
return [
    'field_x' => [
        'type' => 'checkboxgroup',
        'items' => [
            'a' => 'A',
            'b' => 'B',
            'c' => 'C',
        ]
    ],
    'field_y' => [
        'type' => 'text',
        'conditions' => [
            ['field_x', ['a', 'b']]
        ]
    ],
];
```

**Expected behavior:**

I would expect the condition to evaluate to true if field_x value is either `['a'], ['b'] or ['a','b']`. Alternatively introduce new operator such as `['field_x', 'in', ['a', 'b']]` to not break compatibility.

**Actual behavior:** 

Per condition.js:41 when field_x is `['a']` then it is checked as `['a', 'b'].indexOf(['a'])`. I don't think it makes sense.

### Additional Information
Adding this to condition.js would create "expected" behavior:
```
else if(_.isArray(actual)){
    return actual.filter(e => expected.includes(e)).length > 0;
}
```

**Comment by adamberecz** [comment]
Added a fix for this in the latest [release](https://laraform.io/releases) @karlerss - thanks for bringing up this issue and recommending a solution!
