### ISSUE TITLE
[BUG] Wizard steps are marked as enabled and completed when data is sent from the backend

### ISSUE THREAD

**Issue by tonydotgit** [laraform/laraform#159]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.4
* Laravel version: 8.x
* Laraform Vue package version and type: 1.2.11/pro
* Laraform Laravel package version: 1.2.3/pro

### Description

If data is passed (for example for prefil the form fields with some default values), then this is triggered:
```
      // load data if available
      if (this.form.data && !_.isEmpty(this.form.data)) {
        this.load(this.form.data)
      }
```

Then:
```
      load(data) {
        if (!_.isEmpty(this.wizard$)) {
          this.wizard$.enableAllSteps(). // I think this should not be happening, so the user MUST fill each step first, otherwise the user is allowed to jump across steps without even having fill the previous ones. This basically breaks the default "steps" behavior.
        }
        ...
```

and `enableAllSteps` maks the steps as completed without perform any sort of validation:
```
      /**
       * Enables all steps.
       *
       * @public
       * @returns {void}
       */
      enableAllSteps() {
        _.each(this.steps$, (step$) => {
          step$.enable()
          step$.complete()
        })
      },
```

And this is how the `complete()` method looks like within the wizard step mixin:

```
      /**
       * Completes the step.
       *
       * @public
       * @returns {void}
       */
      complete() {
        if (this.completed) {
          return
        }

        this.completed = true

        this.fire('complete')
      },
```

### Steps to Reproduce

Just pass any data through the backend for a field present within the form:

```
$form->setData(['name' => 'Anonymous']);
```

**Expected behavior:**

Do not mark any step as completed, also do not enable steps as they should be enabled based on user progress.

![Imgur](https://i.imgur.com/g8mpaq4.png)

**Actual behavior:** 

All the steps are enabled and marked as completed.

![Imgur](https://i.imgur.com/kD2nwzL.png)

### Additional Information

- - -

**Comment by adamberecz** [comment]
There are various things you can do about this depending on your use case.

When `loading` data to a form with steps it assumes that it should be editable - that's why all the steps are enabled (I've made a note that this should be an optional feature in the future).

Right now what you can do is
a) define `default` values for certain elements to have initial values
b) you might also use the `update` method of the form on the frontend, which enables you to load a complete set of data without enabling the steps
c) at last you can [`disable`](https://laraform.io/docs/1.x/reference/frontend-wizard-step#method-disable) enabled steps on the frontend once the form is loaded.

**Comment by tonydotgit** [comment]
@adamberecz I think hardcoding here is not a solution, b/c even when you might be right about enabling all the steps, it doesnt make sense to mark them as completed as it is doing rn b/c I can fill just one field but not all of them so it doesn’t necessarily means that the steps are completed.

in addition, I feel like enabling all the steps should be optional (through a parameter or something), imagine a checkout process where the last step is the summary (no fields, only labels printing stuff) and I depend on previous steps’ values for filling this out, then the functionality is broken as I am not prefilling the full form from the backend, I am just prefilling 2 or 3 fields (in most cases just hidden fields that can be used for tracking purposes).

What do you think?

**Comment by adamberecz** [comment]
You're right, this is a valid use case where enabling all the steps doesn't make sense. It's actually possible using the `update` method on the frontend, but yes, you can only `load` data relying only on the backend and that enables all the steps. There's an alternative way of passing data to the frontend using `->with()` method:
``` php
  return view('checkout', [
    'form' => $form->with(['variable' => 'value'])
  ]);
```

Then you can access it on the frontend with `this.form.with.variable`. If setting default values for each field is not an option, this way you can manually load an initial value using `update` method and avoid enabling all the steps.

**Comment by tonydotgit** [comment]
@adamberecz I'm going to try that one, btw what about the steps marked as completed even when they are not, is that a valid issue?

**Comment by tonydotgit** [comment]
@adamberecz for my personal use-case I ended up overriding the `load()` method just removing the `this.wizard$.enableAllSteps()` portion, it does make the thing for my use-case, but I still feel like this should be fixed at either form/wizard config level or somewhere else (enabling steps might be ok, but marking them as completed should not be a thing imho).

**Comment by tonydotgit** [comment]
I am still waiting for confirmation. that marking all steps as completed is not a bug.

**Comment by adamberecz** [comment]
It wasn't a bug, but I've added two new options in the latest [release](https://laraform.io/releases):

[`$completeStepsOnLoad`](https://laraform.io/docs/1.x/reference/frontend-form#prop-completeStepsOnLoad) - if you set this to `false` it will not complete the steps when you load data, but they will be completed.
[`$enableStepsOnLoad`](https://laraform.io/docs/1.x/reference/frontend-form#prop-enableStepsOnLoad) - if you set this to `false` the steps will not even be enabled.

Thanks for the detailed use case!

**Comment by tonydotgit** [comment]
Got it, tyvm @adamberecz
