### ISSUE TITLE
[BUG] Form not submitted when using async-rule

### ISSUE THREAD

**Issue by basvandertogt** [laraform/laraform#161]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.2.1
* Laravel version: 7
* Laraform Vue package version and type: 1.2.11 pro
* Laraform Laravel package version: 1.2 pro

### Description

I implemented a unique async rule as described here: https://laraform.io/docs/1.x/basics/validation#async-rules
The validation is working but the form is not submitted. There are no errors on the console. The form is just not submitted.

### Steps to Reproduce

Enabled and disabled the async rule. The form is sent when the async rule is disabled.

**Expected behavior:**

Submitting the form.

**Actual behavior:** 

Form is not submitted.

### Additional Information

Screencast: https://www.loom.com/share/9b13f42bf1ba49988c82454a7a198153

**Comment by adamberecz** [comment]
It's hard to tell without a reproducible example - the form submits on my end with the same sequence of steps. Generally the form does not submit if it has any invalid fields. It might be the unique or something else, maybe on the last step. If you can't resolve this let me know if you can jump on a call and I'll try to help.

**Comment by basvandertogt** [comment]
@adamberecz A call would be very helpful. When do you have time?
