### ISSUE TITLE
[QUESTION] Is a BS5 theme coming?

### ISSUE THREAD

**Issue by tonydotgit** [laraform/laraform#162]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 8.0
* Laravel version: 8.32.1
* Laraform Vue package version and type: 1.2.12 / pro
* Laraform Laravel package version: 1.2.4 / pro-->

### Description

Bootstrap 5 stable has been released, I wonder if a BS5 version is coming anytime soon for Laraform. The reason why I ask is that we are in the middle of refreshing our website image and we are evaluating the pros and cons of BS4 vs BS5.

### Additional Information

References: https://blog.getbootstrap.com/2021/05/05/bootstrap-5/

**Comment by adamberecz** [comment]
Bootstrap 5 is almost identical to Bootstrap 4 in terms of form elements. I'll make sure it gets added in a couple of weeks at most. Let me know if you need that more urgently and I'll try to find the time for it sooner.

**Comment by tonydotgit** [comment]
@adamberecz I appreciate it, not very urgent tbh so do not change your schedule just for this, it can wait for whenever you have an space in your queue for sure.

Tyvm!

**Comment by tonydotgit** [comment]
Just commenting here to follow up.
