### ISSUE TITLE
[DOCS] vue runtime

### ISSUE THREAD

**Issue by ekomurz** [laraform/laraform#163]
### Prerequisites

* [ ] You've provided enough information to spot the issue.
* [x] You filled in the entire issue template.

### Versions

Current version of documentation
(on a basic 8.x Laravel setup, with laravel-mix etc.. installed)

### Description

At this point in the documentation https://laraform.io/docs/1.x/installation , the suggestion is done to include Vue into app.js using this instruction `import Vue from 'vue'`

This lead to a blank screen with no output, with the console refering to runtime version of Vue.js
I changed this into 
`import Vue from 'vue/dist/vue.js'`

### Additional Information

It might be an idea to point to this in the documentation ?

**Comment by Bert210** [comment]
I had the same problem.
I changed
```js
import Vue from 'vue'
```

to

```js
import Vue from 'vue/dist/vue.esm'
```

Doesn't fix the problem but it should help get it running.
