### ISSUE TITLE
[BUG] Can't install in PHP 8

### ISSUE THREAD

**Issue by luilliarcec** [laraform/laraform#164]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [ ] You filled in the entire issue template.

### Versions

* PHP version: 8.0
* Laravel version: 8.42.1
* Laraform Vue package version and type: 1.2.2 / community (node_modules/@laraform/package.json)
* Laraform Laravel package version: -

### Description

`composer require laraform/laraform-laravel` 

```
Using version ^1.2 for laraform/laraform-laravel
./composer.json has been updated
Running composer update laraform/laraform-laravel
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - hashids/hashids 3.0.0 requires php ^7.1.3 -> your php version (8.0.3) does not satisfy that requirement.
    - laraform/laraform-laravel 1.2.0 requires hashids/hashids ^3.0 -> satisfiable by hashids/hashids[3.0.0].
    - Root composer.json requires laraform/laraform-laravel ^1.2 -> satisfiable by laraform/laraform-laravel[1.2.0].
```

### Steps to Reproduce

`composer require laraform/laraform-laravel`

**Comment by adamberecz** [comment]
Just rolled out a patch with hashids 4.0 dependency. Please update to `1.2.1` and it should install fine.

**Comment by luilliarcec** [comment]
I know it is not a bug, but this message may represent something for you.


```
Class Laraform\Contracts\Database\Relationship located in ./vendor/laraform/laraform-laravel/src/Contracts/Database/_Relationship.php does not comply with psr-4 autoloading standard. Skipping.
```

It should be noted that it has now been installed correctly.
