### ISSUE TITLE
Can you help see why my form is not loading?

### ISSUE THREAD

**Issue by graffxdesign** [laraform/laraform#167]
### Description
I have installed Larform and followed the documents for the TestForm.

It is loading on the HTML but not rendering on the page.

Is this a common issue or can you please point me as to where to look to fix this problem.

Here is the output of HTML but again it is not showing on the page.
`<laraform :form="{&quot;key&quot;:&quot;eyJpdiI6IkFtODNNbkZjdGZUeDZpV3BIYjkxZ0E9PSIsInZhbHVlIjoicjVYcHBObVBSUlRMYXBXVHg0ejlpdz09IiwibWFjIjoiZjJmOWZjNjVkNzU4ZGY5M2VmOTk4NGVjNmEyOTcwMWI3MjNlYmMxY2RiYTc3ZTQ0MDRjZGQ5ODg3NzM1NTE1MyJ9&quot;,&quot;data&quot;:[],&quot;schema&quot;:{&quot;hello_world&quot;:{&quot;type&quot;:&quot;text&quot;,&quot;label&quot;:&quot;Hello&quot;,&quot;default&quot;:&quot;World&quot;,&quot;name&quot;:&quot;hello_world&quot;,&quot;component&quot;:&quot;text-element&quot;}},&quot;theme&quot;:&quot;bs4&quot;,&quot;columns&quot;:{&quot;element&quot;:12,&quot;label&quot;:12,&quot;field&quot;:12},&quot;class&quot;:null,&quot;classes&quot;:null,&quot;labels&quot;:false,&quot;layout&quot;:false,&quot;formErrors&quot;:true,&quot;enableStepsOnLoad&quot;:true,&quot;completeStepsOnLoad&quot;:true,&quot;buttons&quot;:[{&quot;label&quot;:&quot;Submit&quot;}],&quot;tabs&quot;:null,&quot;wizard&quot;:null,&quot;wizardControls&quot;:true,&quot;with&quot;:[],&quot;messages&quot;:[],&quot;multilingual&quot;:false,&quot;locale&quot;:&quot;en_US&quot;,&quot;language&quot;:&quot;en&quot;,&quot;languages&quot;:{&quot;en&quot;:{&quot;code&quot;:&quot;en&quot;,&quot;label&quot;:&quot;English&quot;}},&quot;endpoint&quot;:&quot;\/laraform\/process&quot;,&quot;method&quot;:&quot;POST&quot;,&quot;timezone&quot;:null,&quot;userTimezone&quot;:null,&quot;validateOn&quot;:&quot;submit|change|step&quot;}"></laraform>`

**Comment by adamberecz** [comment]
What is that you see on the website? Is there any console errors?

This seems like an issue of not having the Vue or the Laraform frontend package installed correctly. I've just sent you an email about it.
