### ISSUE TITLE
[QUESTION] Form is not rendered on frontend side

### ISSUE THREAD

**Issue by NikitaMakovey** [laraform/laraform#169]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [X] Your question isn't already asked before.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 7.4
* Laravel version: 8
* Laraform Vue package version and type: 1.2.12 / pro (node_modules/@laraform/package.json)
* Laraform Laravel package version: 1.2 / pro (vendor/laraform/laraform-laravel/composer.json)

### Description

There is a problem with the form rendering by the back-end configuration (Form class with schema & buttons). 

Frontend only rendering works correctly.

Vue component:

```
<script>
    export default {
        mixins: [Laraform],
        created() {
            alert('The form is created')
        }
    }
</script>
```

Form class:

```
<?php


namespace App\Forms;


class TestForm extends \Laraform\Laraform
{
    public $component = 'test-form';

    public function schema() {
        return [
            'hello_world' => [
                'type' => 'text',
                'label' => 'Hello',
                'default' => 'World'
            ]
        ];
    }

    public function buttons() {
        return [
            [
                'label' => 'Submit'
            ]
        ];
    }
}
```

That's what I see in HTML DOM after mounted:

```
<form data-v-e53e2e2c="" class="lf-form">
    <!----> 
    <!----> 
    <!----> 
    <!----> 
    <div class="row"></div> 
    <!----> 
    <!---->
</form>
```

My index.html content:
```
<div id="app">
    {!! $form->render() !!}
</div>
```

### Additional Information

`vue-cli`

**Comment by adamberecz** [comment]
Hi @NikitaMakovey ! Did you manage to solve this? If not, are there any console errors?

**Comment by NikitaMakovey** [comment]
Hello @adamberecz ! No console errors. Now I use frontend-only rendering but I need to use both of this. Do you have any ideas about it? Maybe vue-cli issue, but I see prepared <laraform> tag before mounted in #app div

**Comment by adamberecz** [comment]
I'm not really sure how you can render backend code in a vue-cli app (?), but if you can create a test repo I'll look into it.
