### ISSUE TITLE
Tailwind CSS Theme Support

### ISSUE THREAD

**Issue by daugaard47** [laraform/laraform#17]
I'm trying to use this in a current project and was wondering if you have a theme that supports Tailwind CSS rather BS4? 
Looking for a solution so I don't have to manually create it all.

**Comment by laraform** [comment]
Hey Chris, currently we support Bootstrap 3 / 4. Tailwind is something we will eventually implement, but right now you can create it on your own. Here's some resource: https://laraform.io/docs/1.x/how-tos/creating-theme and I'd also recommend checking out `@laraform/src/component` & `@laraform/src/themes` to understand the structure better.
