### ISSUE TITLE
[BUG] List conditions are not working

### ISSUE THREAD

**Issue by NikitaMakovey** [laraform/laraform#170]
### Prerequisites

* [X] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [X] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [X] Your issue isn't already filed.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 7.4
* Laravel version: 8
* Laraform Vue package version and type: 1.2.12 / pro (node_modules/@laraform/package.json)

### Description

I need to use a few kinds of conditions in my application.

N.1 (works correctly):
```
"conditions": [
    ["list.*.field", "value"]
]
```

N.2 (does not work):
```
"conditions": [
    ["list1.*.list2.*.field", "value"]
]
```
How to fix it?

**Comment by adamberecz** [comment]
Install `1.2.13` [patch](https://laraform.io/releases) for fix.
