### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by favoriabs** [laraform/laraform#172]
### Prerequisites

* [X] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [X] Your question isn't already asked before.
* [ ] You filled in the entire issue template.

### Versions

* PHP version:  7.3.30 
* Laravel version: 8.5.1 
* Laraform Vue package version and type: 1.2.12 / pro (node_modules/@laraform/package.json) 
* Laraform Laravel package version: 1.2 / pro(vendor/laraform/laraform-laravel/composer.json) 

### Description

How difficult will it be to integrate a framework like vuetify while using Laraform, especially because the theme object uses classes as properties.

**Comment by adamberecz** [comment]
It would be difficult. I wouldn't recommend using Laraform with Vuetify at the moment.

**Comment by favoriabs** [comment]
Thank you @adamberecz
