### ISSUE TITLE
Unable to install -- Axios Dependency Resolution [BUG]

### ISSUE THREAD

**Issue by PunchRockgroin** [laraform/laraform#173]
### Prerequisites

* [X] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [X] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [X] Your issue isn't already filed.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 8.0.5
* Laravel version: 8.60
* Laraform Vue package version and type: 1.2.13  (Pro)
* Laraform Laravel package version: 1.2.1 (Pro)

### Description

Cannot install 

### Steps to Reproduce

1. Download and install latest Laravel 
2. npm install @laraform/laraform from root

**Expected behavior:**

Vue package installation success

**Actual behavior:** 

npm install @laraform/laraform --save fails with peer dependency issue

### Additional Information
Log message:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: axios@0.21.4
npm ERR! node_modules/axios
npm ERR!   dev axios@"^0.21.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer axios@"^0.18" from @laraform/laraform@1.2.13
npm ERR! node_modules/@laraform/laraform
npm ERR!   @laraform/laraform@"^1.2.13" from the root project

**Comment by adamberecz** [comment]
Not sure why npm is doing this because `^` should allow higher minors. This could be an issue with some versions of Node.js, so either try updating or changing it to a different version temporarily or using:
```
npm install @laraform/laraform --save --legacy-peer-deps
```
or
```
npm install @laraform/laraform --save --force
```

If `--legacy-peer-deps` work you might set it globally:
```
npm install --save --legacy-peer-deps
```

**Comment by PunchRockgroin** [comment]
Sorry for the delay...

I used the flags there to get the install working so I could proceed.

Just to add more info that the dev machine I'm testing this on is Laravel Homestead which my local is tagged v12.3.2 and shows Node at v14.17.0.

So I removed Node/NPM as outlined here https://github.com/laravel/homestead/blob/ab76761f480a6ab0a0bd74e09dcc4cac86fb9906/resources/after.sh and updated npm using 

`/usr/bin/npm install -g npm`

Which brought Node to 16.9.1 and NPM to 7.24.0.

No luck -- still shows the same message. However, using the legacy-peer-deps flag allows install and I haven't seen issues, but I also haven't deployed this app to production yet.

Thanks!

**Comment by anoshiri** [comment]
I have the same issue and I'm running the following software versions

PHP 8.0.3
NPM 7.17.0
Laravel ^8.40
Vue 3.0.5

I get the following error when I run "npm i laraform --save"

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: axios@0.21.4
npm ERR! node_modules/axios
npm ERR!   dev axios@"^0.21" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer axios@"^0.18" from laraform@1.2.2
npm ERR! node_modules/laraform
npm ERR!   laraform@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See ~\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~\2021-09-27T09_32_43_669Z-debug.log

**Comment by adamberecz** [comment]
I've updated axios dependency version to `^21.0` to match latest Laravel. It should throw an error anymore with the latest install.
