### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ArtDepartmentMJ** [laraform/laraform#175]
### Prerequisites

* [X] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [X] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [X] Your issue isn't already filed.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 8.0.7
* Laravel version: 8.61.0
* Laraform Vue package version and type: 1.2.2 / community
* Laraform Laravel package version: 1.2.1 / community

### Description

Factory class is not PHP 8 compatible.
I can see that the fix on Laraform\Elements\Factory has been applied in SC however when installing from fresh following the documentation it throws the following error: Required parameter $options follows optional parameter $name

### Steps to Reproduce

Fresh install of Laravel 8
Install Laraform as per documentation
Follow the FirstForm steps

**Expected behavior:**

For the form field to display

**Actual behavior:** 

Throws the following ErrorException:

Required parameter $options follows optional parameter $name

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

This is an easy fix, just give the optional parameter a type or provide a defaut value for the final required parameter

````
public function make($schema, string $name = null, $options)
````

````
public function make($schema, string $name = null, $options = [])

````

**Comment by adamberecz** [comment]
This was fixed in `1.2.2` - please update.
