### ISSUE TITLE
[BUG] Enter key on Wizard setup goes backwards rather than forward

### ISSUE THREAD

**Issue by Shamunr** [laraform/laraform#176]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 8.0.3
* Laravel version: 8.62.0
* Laraform Vue package version and type: 1.2.13 pro (I believe?  We have a license)
* Laraform Laravel package version: 1.2.5 pro (As above, we have a license)

### Description

When using the Wizard, if you press enter to submit the form as one would expect to do, it will instead go back to the previous step.

### Steps to Reproduce

The issue can be reproduced using the examples on the website:

https://laraform.io/examples
On the shopify checkout example, proceed to the last step.  Click on "Save my information for faster checkout" and then press enter on keyboard.  It will go to the previous step for shipping options.

https://laraform.io/docs/1.x/basics/wizard-and-tabs
On the first example, enter some information into the form.  Press enter and it will proceed to the next step.  Again, enter information in this step and press enter.  You will be taken back to the first step.  If you click the buttons to proceed, if you go to the last step it will also go back 1 step rather than submit.

**Expected behavior:**

When pressing the enter key, it will attempt to proceed or submit.

**Actual behavior:** 

The form/wizard will go to the previous step

**Comment by adamberecz** [comment]
Hi @Shamunr , I've published a patch for this in `1.2.15`. Please update your frontend package.
