### ISSUE TITLE
[BUG] Slider not working to be updated

### ISSUE THREAD

**Issue by NikitaMakovey** [laraform/laraform#177]
### Prerequisites

* [X] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [X] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [X] Your issue isn't already filed.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 7.4
* Laravel version: 8.21
* Laraform Vue package version and type: pro
* Laraform Laravel package version: pro

### Description

```
element.update(value);
```
doesn't work for `slider` element

**Comment by adamberecz** [comment]
Hi @NikitaMakovey . On my end it does. Please provide a more detailed example that produces the bug.
