### ISSUE TITLE
[QUESTION] how to create a loading for wizard?

### ISSUE THREAD

**Issue by gabrielchavezme** [laraform/laraform#178]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.2.1
* Laravel version: 6.2.1
* Laraform Vue package version and type: 1.1.1
* Laraform Laravel package version: 1.1.1

### Description

In the documentation [https://laraform.io/docs/1.x/basics/buttons#add-loading-state](https://laraform.io/docs/1.x/basics/buttons#add-loading-state) it is possible to install a custom component to add a loading status.

However, in the Wizard version it is not possible, or I did not find documentation about it.

Is this possible without writing so much extra code? It would be great for the user experience.

### Additional Information

It would be great if there is information about it.

**Comment by gabrielchavezme** [comment]
up? :(

**Comment by adamberecz** [comment]
You can do that by replacing the FormWizardComponent with something similar:

``` vue
<template>
  <button
    v-if="visible"
    :disabled="disabled"
    :class="[
      theme.classes.formWizardControlFinish,
      form$.submitting ? 'is-loading' : '',
    ]"
  	@click.prevent="finish"
  >{{ label }}</button>
</template>

<script>
  import FormWizardFinish from '@laraform/laraform/src/components/FormWizardFinish'

  export default {
    mixins: [FormWizardFinish],
  }
</script>
```

The key is that you have access to `form$` (which is the root form instance) so you can determine when it is in a loading state.

Here's how to replace a component:
https://laraform.io/docs/1.x/how-tos/replacing-component
