### ISSUE TITLE
How to send dinamic data from controller, to use in acfter function

### ISSUE THREAD

**Issue by josecienty** [laraform/laraform#179]
If you send the variable in the constructor, it shows an error

Example:
`$form = app('App\Form\TestForm', compact('var'))`

and show the error message,in to use __construct in the Form

Can send var from Controller and use in to Form?

**Comment by adamberecz** [comment]
Hi @josecienty! You can, but you need an extra step and cannot pass it directly to the constructor.

What you need to do is to create the form like this:
``` php
<?php

namespace App\Forms;

class TestForm extends \Laraform
{
  public $var;

  public function schema()
  {
    if ($this->var == null) {
      return [];
    }

    return [
      'field' => [
          'type' => 'text',
          'label' => $this->var,
      ],
    ];
  }
}
```

Then this:
``` php
$form = app('App\Forms\TestForm');

$form->var = 'Field';
$form->schema = $form->schema();
$form->setElements();

return view('index', [
  'form' => $form,
]);
```

It's important that anytime the `schema` changes you call:
```php
$form->schema = $form->schema();
$form->setElements();
```
