### ISSUE TITLE
URL File Uploads does not get saved to database

### ISSUE THREAD

**Issue by vincentvankekerix** [laraform/laraform#18]
First of all, Laraform is a cool product!

When trying to upload a file (or image or avatar) with the default Laraform component, the URL does not get saved to the database. The actual file, however, does get uploaded to the local disk. When checking the console after submitting the form, the server responds with status 500 and the following error:

```
exception: "Symfony\Component\Debug\Exception\FatalThrowableError"
file: "/Users/vincent/Code/forms/vendor/laraform/laraform-laravel/src/Database/Handler.php"
line: 158
message: "Call to a member function save() on null"
```

Since I encountered this problem before, I retried it in a default Laravel project. No modifications, nothing special, just the out of the box setup. Am I missing something obvious here, or would you happen to know what's going on here? The used endpoint for the form processing is also the default ```/laraform/process```.

Thanks, Vincent

### Your environment
* Browser name and version: Chrome 78.0.3904.108
* Operating System: macOS 10.15.1

**Comment by laraform** [comment]
Hi Vincent,

Thank you, I appreciate a lot and I'm glad you like it!

Could you please help me by sending the exact code (with any dependencies it might rely on: migrations, models, etc.) which produces this error?

**Comment by vincentvankekerix** [comment]
Thanks for the quick reply!
I just whipped up a test form for this specific error with just two fields, so I could single out the problem. The form has been created using the backend rendering method.

### ```App\Forms\TestForm.php```
```
<?php

namespace App\Forms;

use Laraform;

class TestForm extends Laraform
{
    public $endpoint = '/laraform/process';

    public $model = \App\TestForm::class;

    public $schema = [
        'name' => [
            'type' => 'text',
            'label' => 'Name',
            'rules' => 'required'
        ],
        'photo' => [
            'type' => 'image',
            'label' => 'Photo',
            'rules' => 'nullable'
        ]
    ];

    public $buttons = [
        0 => [
            'label' => 'Submit',
            'class' => 'btn-primary'
        ]
    ];
}
```

### ```App\TestForm.php```
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class TestForm extends Model
{
    protected $fillable = ['name', 'photo'];
}
```

### The migration
```
    public function up()
    {
        Schema::create('test_forms', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->string('photo')->nullable();
            $table->timestamps();
        });
    }
```

The frontend uses the default ```laraform``` component. Also files like ```filesystems.php``` are unchanged in this example. The error is still there, but like I wrote, the actual file is uploaded succesfully to the local disk. It just won't persist to the database.

Let me know if you'd need any more info!

**Comment by laraform** [comment]
Thank you for the detailed example! I've managed to look into it and realized that the documentation wasn't clear about that you must have an `id` element (or the equivalent primary key) when using files. This is because files are only processed after all the data is saved and they get updated, which makes possible custom store functions, etc.

So the only thing you need to do is to update your schema like:

### `App\Forms\TestForm.php`

``` php
<?php

namespace App\Forms;

use Laraform;

class TestForm extends Laraform
{
    public $endpoint = '/laraform/process';

    public $model = \App\TestForm::class;

    public $schema = [
        'id' => [
            'type' => 'key',
        ],
        'name' => [
            'type' => 'text',
            'label' => 'Name',
            'rules' => 'required'
        ],
        'photo' => [
            'type' => 'image',
            'label' => 'Photo',
            'rules' => 'nullable'
        ]
    ];

    public $buttons = [
        0 => [
            'label' => 'Submit',
            'class' => 'btn-primary'
        ]
    ];
}
```

**Comment by vincentvankekerix** [comment]
That does the trick, thanks a lot for your help!
