### ISSUE TITLE
[QUESTION]I find similar FormButton etc compoenent files and rule files aren't exist in community version

### ISSUE THREAD

**Issue by wanghuazi** [laraform/laraform#180]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [ ] Your question isn't already asked before.
* [ ] You filled in the entire issue template.

### Versions

* PHP version: 
* Laravel version: 
* Laraform Vue package version and type: 
* Laraform Laravel package version: 

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by adamberecz** [comment]
Hi @wanghuazi. File & file rules are not part of the community version. Please see the Feature Comparison here:
https://github.com/laraform/laraform#feature-comparison

**Comment by wanghuazi** [comment]
How do I custom rules?
