### ISSUE TITLE
[BUG] validation rule "before" and "before_or_equal" for date elements not working as expected

### ISSUE THREAD

**Issue by anwsonwsymous** [laraform/laraform#183]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 8.1
* Laravel version: v9.0
* Laraform Vue package version and type: 1.2.14
* Laraform Laravel package version: 1.2.5

### Description

Validation rules `before` and `before_or_equal` in Vue are wrong.

### Steps to Reproduce

1. Create date element with rules `before:today` or `before_or_equal:today`
2. Select date "2001-03-16" 

**Expected behavior:**

Validation passed successfully.

**Actual behavior:** 

Got error: `The Date of birth must be a date before today` 

### Additional Information

You are using this code to for rule `before`
```js
return moment(actual).format('X') < moment(other).format('X')
```
and this one for `before_or_equal`
```js
return moment(actual).format('X') <= moment(other).format('X')
```
This is wrong because you are comparing 2 strings not integers or dates.
```
984686400 is less than 1648670400
'984686400' is not less than '1648670400'
```

You can fix it with:
1. wrapping in `parseInt()` function
```js
// validation 'before'
return parseInt(moment(actual).format('X')) < parseInt(moment(other).format('X'))
// validation 'before_or_equal'
return parseInt(moment(actual).format('X')) <= parseInt(moment(other).format('X'))
```
2. using methods provided by `moment` `isBefore(date)` and `isSameOrBefore(date)`
```js
// validation 'before'
return moment(actual).isBefore(other)
// validation 'before_or_equal'
return moment(actual).isSameOrBefore(other)
```

**Comment by adamberecz** [comment]
Thanks @anwsonwsymous - published the fix in `1.2.16`:
https://laraform.io/releases
