### ISSUE TITLE
[QUESTION] Does full version comes with uncompress version of JS code ? 

### ISSUE THREAD

**Issue by monaye** [laraform/laraform#187]
* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.

Hello, this looks great, and wanted to know if the full version comes with uncompress version of JS code. 
I would like to keep the option to modify/extend the code as needed for my project.

**Comment by adamberecz** [comment]
Hi @monaye, yes the full version comes with the uncompress source.
