### ISSUE TITLE
[BUG] Trouble initiating laraform with laravel-pug (pugjs)

### ISSUE THREAD

**Issue by sebszocinski** [laraform/laraform#188]
Is there another way to initiate Laraform without a `:form` prop? we use pugjs to template our front-end and when we pass through an object to an attribute to use as a vue prop we get a duplicate prop of `form="[object Object]"` which breaks Vue / Laraform.

**Comment by adamberecz** [comment]
If you are using it through `$form->render()` yes, it will have a form prop, but you can simply use the `<Laraform>` component and pass through whatever prop you want:
https://laraform.io/docs/1.x/how-tos/using-only-frontend#create-form-component
