### ISSUE TITLE
[BUG] Problem with conditional validation of uploads

### ISSUE THREAD

**Issue by vincentvankekerix** [laraform/laraform#19]
### Prerequisites

* [X] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [X] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration).
* [X] Your issue isn't already filed.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 7.3.12
* Laravel version: 6.6.0
* Laraform Vue package version: 1.1.7
* Laraform Laravel package version: 1.1.6

### Description

My form has an image field that is required. It also has a condition that the image field is only shown when the 'Photo Required' toggle is true. However, when the condition is false (the 'Photo Required' toggle is set to false), the image field is hidden on the form, but generates an error when submitting the form to the database:

```
exception: "ErrorException"
file: "/Users/vincent/Code/esbforms/vendor/laraform/laraform-laravel/src/Elements/FileElement.php"
line: 280
message: "Undefined index: photo"
```

I also tried to add a conditional rule to the image field, but this didn't change the outcome and generated the same error.

### Steps to Reproduce

**Expected behavior:**

The image field should be ignored by the FileElement handler when it's render condition is false.

**Actual behavior:** 

Laraform's FileElement handler tries to upload a file based on an index that's undefined, because it is left out of the form submit due to the condition of the field (at least, that's what I think).

### Migration
```
$table->bigIncrements('id');
$table->string('name');
$table->boolean('photo_required')->default(0);
$table->string('photo')->nullable();
$table->timestamps();
```

### Model
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class TestForm extends Model
{
    protected $guarded = [''];
}
```

### Form Class
```
<?php

namespace App\Forms;

use Laraform;

class TestForm extends Laraform
{
    public $endpoint = '/laraform/process';

    public $model = \App\TestForm::class;

    public $schema = [
        'name' => [
            'type' => 'text',
            'label' => 'Name',
            'rules' => 'required'
        ],
        'photo_required' => [
            'type' => 'toggle',
            'label' => 'Photo Required?',
        ],
        'photo' => [
            'type' => 'image',
            'label' => 'Photo',
            'rules' => 'required',
            'conditions' => [
                0 => ['photo_required', true]
            ]
        ]
    ];

    public $buttons = [
        0 => [
            'label' => 'Submit',
            'class' => 'btn-primary'
        ]
    ];
}
```

**Comment by laraform** [comment]
Thanks for reporting this issue. A missing presence checker caused the bug, which is now fixed and rolled out with 1.1.7 backend patch: https://laraform.io/releases.
