### ISSUE TITLE
[BUG] PHP 8.1: HasMany::hasKey throws error

### ISSUE THREAD

**Issue by karlerss** [laraform/laraform#193]
* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [ ] You filled in the entire issue template.

### Versions

* PHP version: 8.1
* Laravel version: 9
* Laraform Vue package version and type: n/a
* Laraform Laravel package version: 1.2.5

### Steps to Reproduce

**Expected behavior:**

No error

**Actual behavior:** 

Error:

laraform\\laraform-laravel\\src\\Database\\Relationships\\HasMany.php:153
array_key_exists(): Argument #2 ($array) must be of type array, App\\Models\\*** given

### Additional Information

There's a "@todo: replace array_key_exists with isset" in the method docblock. This fixes the error:
```
if(!is_array($value)){
    return isset($value->{$this->primaryKey});
}
```

**Comment by karlerss** [comment]
This is still relevant. Also in the paid product.

**Comment by KamranBiglari** [comment]
@adamberecz 
Hi, this issue exists. Would you please patch it?
