### ISSUE TITLE
Maintenance Mode / Laraform Future / Vue.js 3

### ISSUE THREAD

**Issue by adamberecz** [laraform/laraform#197]
Laraform has now entered maintenance mode: it will no longer ship new features, but will continue to receive critical bug fixes and security updates until the end of 2023 following the trajectory of Vue.js 2.

Laraform was created when Vue.js 3 wasn't on the horizon while intending to follow up its updates. Along the road it became clear that the frontend part was doing the heavy lifting and making it an independent frontend tool would benefit a wider range of developers. Therefore Laraform in its current form will not reach 2.0 or support for Vue.js 3. It's successor is Vueform which is what Laraform used under the hood as the frontend lib, but improved since. We have plans to add backend support, including Laravel, but it's not in the near future. Using Vueform with Laravel is still possible, only that you have to take care of two things, that Laraform did for you on the backend:
- passing form options (schema, tabs, etc) defined on the backend to the frontend (eg. as a JSON)
- handle the submitted data.

If you're interested using Vueform head here: https://vueform.com

If you'd like to participate in porting Laraform's backend features to Vueform reach out to me at adam@vueform.com.

**Comment by HeadStudios** [comment]
So I'm guessing this means no support on Issues. Damn :(
