### ISSUE TITLE
Web interface for creating forms

### ISSUE THREAD

**Issue by mhphilip** [laraform/laraform#2]
### Feature request
If I would like a (web) user to be able to create a form themselves, do you have any boilerplate code on how to build a Laravel web interface for this? 

E.g like what form.io provides as a “drag-and-drop form builder” is what I am also looking for. 

Or should I have to build the logic for such a web interface myself, that effectively generates the schema data needed for your forms?

(PS I’m willing to pay for such a feature)

**Comment by laraform** [comment]
Hi @mhphilip! It's a nice idea, in fact it's part of our mid-term development roadmap, but not the short-term unfortunately. If you decide to give it a shot feel free to reach out to me at adam@laraform.io if any questions arise.

**Comment by mhphilip** [comment]
Thank you for your quick response. I'll watch the repository for updates!

One other question: If I want to use LaraForm in a VueJS PWA; will it be able to function in "offline mode" as well? 

I know I'll have to build the logic to store the form-submissions offline and resync when connectivity is back up, but I wondered if e.g. the rendering of a form works when offline. Can I somehow locally save the form's schema and render based on these?

And what about conditional logic would that require connectivity?

Thanks again!

**Comment by laraform** [comment]
Working offline should not be a problem as Laraform does not connect to any external source except when submitting data. 

The form's `schema` can passed to the form component via `form` prop, which is an object, eg.:

``` 
<laraform :form="{ schema: mySchemaVariable }"></laraform>
```

Also if you save the schema locally this way you can build up a form dynamically:

``` js
// app.js

var storedSchema = {
  hello_world: {
    type: 'text',
    label: 'Hello',
    default: 'World',
  }
}

var MyForm = Vue.component('my-form', {
  mixins: [
    Laraform
  ],
  data: () => ({
    schema: storedSchema
  })
})

var app = new Vue({
    el: '#app',
    components: {
      MyForm,
    }
})
```

``` html
<!-- index.html -->

<my-form></my-form>
```

This is pretty much how I would do it and replace the `storedSchema` with the stored value.

Conditional logic does not require connectivity! Also if you load the data it will apply the conditions accordingly.

Hope this answers your questions!
