### ISSUE TITLE
[BUG] - Unknown custom element: <trix-editor>

### ISSUE THREAD

**Issue by skillcraft-io** [laraform/laraform#20]
* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration).
* [x ] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

* PHP version: PHP 7.2.24
* Laravel version:  v6.9.0
* Laraform Vue package version: 1.1.8
* Laraform Laravel package version: 1.1.8

### Description
[Vue warn]: Error in beforeMount hook: "ReferenceError: Vue is not defined"

ReferenceError: Vue is not defined

After installing and compiling Laraform into my environment, and use a "trix" form type, this error exists. However, the Trix input still operates.

### Steps to Reproduce

Install Laravel with  Laraform Pro Package
Install and compile laraform into app.js
Build a form and try load page

**Expected behavior:**
Generate form without any console error

**Actual behavior:** 

Console Error occurs:

```
<Trix> at src/components/wrappers/Trix.vue
       <BaseElementLayout> at src/themes/bs3/components/BaseElementLayout.vue
         <TrixElement> at src/themes/default/components/elements/TrixElement.vue
           <FormElements> at src/themes/bs3/components/FormElements.vue
             <ProductCreateForm> at resources/backend/assets/js/components/Laraform/ProductCreateForm.vue
               <Root>
```

### Additional Information

1.) If set Vue to use bootstrap vuejs instead, the Trix error does not occur.
2.) In Both cases: ReferenceError: Vue is not defined exists
3.) In the error output, BS3 is mentioned, but I am using bs4 as default theme

This is my Backend form:

```
class CustomForm extends Laraform
{

    /**
     * Form Schema
     * 
     * @return array
     */
    public function schema()
    {
        return [
            'email' => [
                'type' => 'trix',
                'label' => 'E-mail Address',
                'rules' => ['required','email']
            ],
        ];
    }
}
```

**Comment by laraform** [comment]
Hi @zhxscript! Please provide some further details according to the issue template, so that I can look into it (eg. form schema).

**Comment by skillcraft-io** [comment]
> Hi @zhxscript! Please provide some further details according to the issue template, so that I can look into it (eg. form schema).

Please see bug report, I have updated with more information :)

**Comment by laraform** [comment]
I'm not able to reproduce the error based on the provided example. Please provide the full `app.js` or create a repo that produces the error.

**Comment by skillcraft-io** [comment]
@laraform 

I created a repository and sent the invite to that repository. I tested and seems even in the latest versions it is present.

Let me know! 
thanks

**Comment by laraform** [comment]
Found the problem. Earlier versions of Laravel set Vue as global and Trix was relying on it:
`Vue.config.ignoredElements = ['trix-editor']`
Now I've moved it to the installer so it does not require the global Vue object anymore. Rolled out a new release (1.1.10) which has the fix, so after an update it should work.
