### ISSUE TITLE
[BUG] Form not showing after install

### ISSUE THREAD

**Issue by HeadStudios** [laraform/laraform#200]
### Prerequisites

* [X] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [X] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [X] Your issue isn't already filed.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 8.2
* Laravel version: 9
* Laraform Vue package version and type: not sure
* Laraform Laravel package version: latest

### Description

When embedding form as per tutorial the following is rendered in HTML:
`<laraform :form="{&quot;key&quot;:&quot;eyJpdiI6Ims0N1VNZmQ4RGpaaU13ZWxGZUdIOXc9PSIsInZhbHVlIjoibjM5US8vZitMZlFDeUdQMXpZaVM3eU1NVVprZE5ZWG9rOTR2WnZvUjlxdz0iLCJtYWMiOiI0MmQzNGQ3YTg4ZjVmMDZmMTVkODgxNTA4YTA0MDcwOGYwZThlZjg2ZDdlZjA5ZjhlNDc0ZGI4YzY1ZjNlMzVkIiwidGFnIjoiIn0=&quot;,&quot;data&quot;:[],&quot;schema&quot;:{&quot;hello_world&quot;:{&quot;type&quot;:&quot;text&quot;,&quot;label&quot;:&quot;Hello&quot;,&quot;default&quot;:&quot;World&quot;,&quot;name&quot;:&quot;hello_world&quot;,&quot;component&quot;:&quot;text-element&quot;}},&quot;theme&quot;:&quot;default&quot;,&quot;columns&quot;:{&quot;element&quot;:12,&quot;label&quot;:12,&quot;field&quot;:12},&quot;class&quot;:null,&quot;classes&quot;:null,&quot;labels&quot;:false,&quot;layout&quot;:false,&quot;formErrors&quot;:true,&quot;buttons&quot;:null,&quot;with&quot;:[],&quot;messages&quot;:[],&quot;locale&quot;:&quot;en_US&quot;,&quot;endpoint&quot;:&quot;\/laraform\/process&quot;,&quot;method&quot;:&quot;POST&quot;,&quot;validateOn&quot;:&quot;submit|change&quot;}" ></laraform>`

### Steps to Reproduce

Just followed instructions to install in my Laravel

**Expected behavior:**

Should show!

**Actual behavior:** 

Form is not showing - also require issue on code

### Additional Information

Video for context: 
https://share.getcloudapp.com/NQuWLmjl

**Comment by adamberecz** [comment]
It seems like you're missing the frontend part completely at least it wasn't shown at the video - which is nice btw.

Make sure all these steps are completed:
https://github.com/laraform/laraform#usage

And here's a more detailed setup guide specifically for Laravel + Vite:
https://laraform.io/docs/1.x/installation#setup

**Comment by HeadStudios** [comment]
Thank you so much! Closing this thread.

**Comment by HeadStudios** [comment]
Running npm run build after following instructions and adding the following to my app.js file:

```js
require('./bootstrap');

import Vue from 'vue'
import Laraform from 'laraform'

Vue.use(Laraform)

const app = new Vue({
  el: '#app',
})
```

Returns the following error:
```
✓ 78 modules transformed.
'default' is not exported by node_modules/vue/dist/vue.esm-bundler.js, imported by resources/js/app.js
file: /home/forge/dev1.rrdevours.monster/resources/js/app.js:3:7
1: require('./bootstrap');
2: 
3: import Vue from 'vue'
          ^
4: import Laraform from 'laraform'
error during build:
Error: 'default' is not exported by node_modules/vue/dist/vue.esm-bundler.js, imported by resources/js/app.js
    at error (/home/forge/dev1.rrdevours.monster/node_modules/rollup/dist/shared/rollup.js:198:30)
    at Module.error (/home/forge/dev1.rrdevours.monster/node_modules/rollup/dist/shared/rollup.js:12543:16)
    at Module.traceVariable (/home/forge/dev1.rrdevours.monster/node_modules/rollup/dist/shared/rollup.js:12902:29)
    at ModuleScope.findVariable (/home/forge/dev1.rrdevours.monster/node_modules/rollup/dist/shared/rollup.js:11554:39)
    at MemberExpression.bind (/home/forge/dev1.rrdevours.monster/node_modules/rollup/dist/shared/rollup.js:8715:49)
    at CallExpression.bind (/home/forge/dev1.rrdevours.monster/node_modules/rollup/dist/shared/rollup.js:5383:23)
    at CallExpression.bind (/home/forge/dev1.rrdevours.monster/node_modules/rollup/dist/shared/rollup.js:9049:15)
    at ExpressionStatement.bind (/home/forge/dev1.rrdevours.monster/node_modules/rollup/dist/shared/rollup.js:5383:23)
    at Program.bind (/home/forge/dev1.rrdevours.monster/node_modules/rollup/dist/shared/rollup.js:5379:73)
    at Module.bindReferences (/home/forge/dev1.rrdevours.monster/node_modules/rollup/dist/shared/rollup.js:12539:18)
```

Do you ahve any comments on this and by the way I have "vue": "^3.2.47", in package.json.

Thank you!

**Comment by HeadStudios** [comment]
Nvm, I changed code to following from ChatGPT's suggestion:

```js
require('./bootstrap');

import { createApp } from 'vue'
import Laraform from 'laraform'

const app = createApp({})
app.use(Laraform)
app.mount('#app')
```

and it has compiled. On to the next step.
