### ISSUE TITLE
[QUESTION] Javascript File Size

### ISSUE THREAD

**Issue by romeosemper** [laraform/laraform#23]
### Prerequisites

* [X ] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [X ] Your question isn't already asked before.
* [X ] You filled in the entire issue template.

### Versions

* PHP version: 7.4
* Laravel version: 6.6
* Laraform Vue package version: 1.1.8 (Pro)
* Laraform Laravel package version: 1.1.8 (Pro)

### Description

First, I'd like to say, that this is a gread project. 
I was completly impressed while reading about the features in the documentation!

Unfortunatly, at the moment i cannot really use it because of the filesize. At least not on a publically available website.

Is there a way to reduce the filesize or to split it in multiple files?

Even in minified production mode laraforms adds more than 1 MB to the Javascript file size.
That is just to much for any production website.

I've tried codesplitting, but if you directly import Laraforms only in the form files, you get an error (Failed to mount component: template or render function not defined.)
As soon as I follow the documentation and import it globally it works, but then the Filesize problem is back ;)

**Comment by laraform** [comment]
Hi! I'm glad you like Laraform, thank you for sharing! 

Codesplitting is an undocumented feature of Laraform, but you can play around with it yourself. Include `essentials` or `core` from `@laraform/laraform/src` and add elements, validator rules, themes and locale manually by using [configuration methods](https://laraform.io/docs/1.x/basics/configuration#configuration-methods). The official documentation on this feature will come in the future.

**Comment by tanthammar** [comment]
I tested different imports one with `core` and one with `essentials` from `@laraform/laraform/src` and executed `npm run prod`and I got a **6.19 MiB** big file. 

That is not acceptable in any application.

Then I tried the standard import and got 
````
/js/laraform.js   5.16 MiB       3  [emitted]  [big]  /js/laraform
````


This is my laraform.js
```js
// https://laraform.io/docs/usage
import Laraform from '@laraform/laraform' // <- Premium package

Laraform.config({
    endpoints: {
      process: '/laraform/process',
  
      // Only required for full version
      elements: {
        trix: {
          attachment: '/laraform/trix-attachment'
        }
      },
      validators: {
        active_url: '/laraform/validator/active_url',
        exists: '/laraform/validator/exists',
        unique: '/laraform/validator/unique',
      },
    }
  })
Vue.use(Laraform)

```

Can you please assist on how to compile with better file size.
I would appreciate an example :)

**Comment by laraform** [comment]
Try this:
```
import Laraform from '@laraform/laraform/dist/essentials'
```
or:
```
import Laraform from '@laraform/laraform/dist/core'
```
and add elements, validator rules, themes and locale manually.

These should be much lighter. The full version is large because it includes all the dependencies, which might be heavy sometimes (even though we tried to used the lightest ones).

If you check out `dist` folder you can see the minified versions are:
`full`: 769 kb
`essentials`: 385 kb
`core`: 21 kb
These can be reduced even further with gzip.

**Comment by laraform** [comment]
I'm closing this for now.
