### ISSUE TITLE
[QUESTION] Authorization / Autoprocessing

### ISSUE THREAD

**Issue by romeosemper** [laraform/laraform#24]
### Prerequisites

* [X] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [X] Your question isn't already asked before.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 7.4
* Laravel version: 6.6
* Laraform Vue package version: 1.1.8 (Pro)
* Laraform Laravel package version: 1.1.8 (Pro)

### Description

Is there a way of authorizing form processing in the backend?
Otherwise any (even non registered) users could use and save all forms defined in the backend.

Of course you can manually process all forms and perform authorization logic there, but it would be much easier if there would be a built in way.
I saw there is an Authorization property in the Laraform Class and even a Authorization folder in the source, so i guess there mus be a way.
If there is, i guess its missing in the documentation

**Comment by laraform** [comment]
Yes, that's an unofficial feature because it needs some wider testing and extension. You can play around with it to see if it can do the job for you, but maybe implementing it for yourself is just an easier way as you have full control.

**Comment by romeosemper** [comment]
Ah okay thanks for the answer.

Maybe there should be a swich in the settings to enable or disable autoprocessing.
Of course you can overwrite the routes in the routes file, but unless you do, the autoprocessing could lead to security issues.

**Comment by laraform** [comment]
Thanks, noted.
