### ISSUE TITLE
[QUESTION] Adding fields to data after validation such as a slug

### ISSUE THREAD

**Issue by RicLeP** [laraform/laraform#25]
### Prerequisites

* [X] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [X] Your question isn't already asked before.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 7.3.9
* Laravel version: 6.6.2
* Laraform Vue package version: 1.0.5
* Laraform Laravel package version: 1.0.4

### Description

I want to add additional generated fields to the form’s data such as creating a slug when the model is saved.

I tried the following in my form class but the slug field is never added to the SQL

```php
public function boot() {
	$this->on('validated', function() {
		$this->data['slug'] = Str::slug($this->data['title']);
	});
}
```

Is it possible to do this, and if so how? I’d prefer to handle this server side not in Vue.

**Comment by laraform** [comment]
Simply adding a new `$data` param won't make it added to the SQL. You need to have an element for that, because query is built up based on that.

So I'd recommend adding `slug` as a `hidden` element, then setting it on the `before()`:
```
public function before() {
  $this->data['slug'] = Str::slug($this->data['title']);
}
```

**Comment by RicLeP** [comment]
Just to add to @laraform’s answer, if using a custom end-point and not auto-processing then the `validating()` method works

```php
public function validating() {
	$this->data['slug'] = Str::slug($this->data['title']);
}
```
