### ISSUE TITLE
[IDEA] Allow use of named routes for Form $endpoint

### ISSUE THREAD

**Issue by RicLeP** [laraform/laraform#26]
### Versions

- PHP version: 7.3.9
- Laravel version: 6.6.2
- Laraform Vue package version: 1.0.5
- Laraform Laravel package version: 1.0.4

### Description

Currently the endpoint needs to be specified as a string making this brittle if the route URLs are changed. If would be useful to have a `setEndpoint` method on the Forms class allowing us to use the route methods to return the URL string such as `route('some.route.name)`

**Comment by robsonrk** [comment]
I agree!

Like as schema where you can declare as variable or function
```
public $endpoint = '/custom-endpoint';
// or
public function endpoint()
{
    return route('custom.endpoint');
}
```

**Comment by romeosemper** [comment]
Not 100% sure if thats what you mean, but for me overwriting the getEndpoint method works:

`public function getEndpoint()
    {
        return route('YOUR_ROUTE_NAME');
    }`

**Comment by RicLeP** [comment]
@romeosemper that’s exactly it! I somehow missed this method when looking for it!
