### ISSUE TITLE
Events and Custom Submit ignored

### ISSUE THREAD

**Issue by yespbs** [laraform/laraform#27]
### Description
*Tell us what happens and what should happen*
I am trying to add a submit event hook as well write a custom submit logic as per doc https://laraform.io/docs/events-and-hooks and https://laraform.io/docs/submission#custom-submission-logic. But when custom submit handler just ignored, any event when attached throws error.
I have a licensed full version and developing a PWA with stored schema. Everything else ( render, validation, submit to backend etc) works just fine

### Steps to reproduce
*Provide steps to reproduce this issue*
1. Use Vue Cli and PWA setup
2. yarn serve

### Demo
*Provide a link to a screencast showing the issue*
![Screenshot (2)](https://user-images.githubusercontent.com/478293/70603411-82f55680-1c1c-11ea-8913-b51e99caf632.png)
![Screenshot (3)](https://user-images.githubusercontent.com/478293/70603531-c3ed6b00-1c1c-11ea-9cd9-6b43fe188f12.png)
![Screenshot (4)](https://user-images.githubusercontent.com/478293/70603535-c4860180-1c1c-11ea-825d-22ab6471f82e.png)
![Screenshot (5)](https://user-images.githubusercontent.com/478293/70603539-c51e9800-1c1c-11ea-8a7d-f61cdbeb820d.png)

### Your environment
* Browser name and version: Chrome Version 78.0.3904.108 (Official Build) (64-bit)

* Operating System: Windows 10 Home

**Comment by yespbs** [comment]
I added a sample PWA app with both normal component and async component. Both fails on Vue CLI 4.
The sample included premium package in premium branch

https://github.com/yespbs/laraform-pwa

Please help me with your suggestions

**Comment by yespbs** [comment]
any updates?

**Comment by laraform** [comment]
I've installed the https://github.com/yespbs/laraform-pwa repo but I only get a "Welcome to Your Vue.js App" screen. Please provide a working example for the repo with clear steps to initialize or provide the codes (not screenshots) to reproduce the bug according to the issue template.

**Comment by yespbs** [comment]
on install there should be 3 menu items on top of page. last 2 are using
laraform and issue should display on console.

the github branch premium requires a premium key to install

**Comment by laraform** [comment]
Ok, now I can see that you are trying to create a wrapper around Laraform component. The right way to do it is this in `MyFirstForm`:
```
<template>
  <laraform :form="storedSchema" ref="form$"></laraform>
</template>
<script>
  export default {
    name: 'MyFirstForm',
    data: () => ({
      storedSchema: {
        schema: {
          hello_world: {
            type: 'text',
            label: 'Hello',
            default: 'World',
          },
        },  
        buttons: [
          {
            label: 'Submit',
            class: 'btn-primary',
            disabled() {
              // this.form$ is the root Laraform component
              return this.form$.disabled
            }
          },
          {
            label: 'Reset',
            class: 'btn-light',
            prevent: true,
            onClick() {
              this.form$.reset()
            } 
          }
        ]
      }  
    }),
    mounted() {
      this.$refs.form$.on('submit', () => {
        alert('Submission process started')
      })
    },
    methods: {
      submit() {
        // implement custom solution
        console.log('custom submit logic')
      }
    }
  }
</script>
```

- You don't need to add Laraform as a mixin to the wrapper
- The `<laraform>` component should be referenced with `ref` and that's how you can access its `.on` method.

**Comment by yespbs** [comment]
That works! great

in my CLI 3 setup the PWA is working fine and I found the beforeMount and mounted is best hook to dynamically change the form schema. Only important knowledge is using the ref, I tried that but not exactly as guided here. 

Thanks very much
