### ISSUE TITLE
optional integration of buefy.org components

### ISSUE THREAD

**Issue by lsmith77** [laraform/laraform#3]
### Description
what do you think about adding optional support for buefy.org components?

**Comment by laraform** [comment]
We'll definitely have it one day along with other CSS framework options. Would you be interested in contributing to this one? If you do so, reach out to me at adam@laraform.io.

**Comment by lsmith77** [comment]
I certainly could see myself contribute to, but likely will not have time to lead the way. I will experiment a bit more with the current solution and buefy. There is an outside chance I will prioritize it over other tasks.

But its good to know that this is something you are open to.

**Comment by laraform** [comment]
Let me know if you are there and we'll arrange something to have the full source. It's easier to experiment with that.
