### ISSUE TITLE
[QUESTION] Populating a select box from Eloquent relationship

### ISSUE THREAD

**Issue by RicLeP** [laraform/laraform#30]
PHP version: 7.3.9
    Laravel version: 6.6.2
    Laraform Vue package version: 1.0.5
    Laraform Laravel package version: 1.0.4

### Description

I’ve a one to many relationship between two models - Entries and Schools. Schools can have many Entries and Entries can have one School.

How can I create a select box on an Entry that lists all the Schools as options (and can I show a subset if required)?

I can’t see this in the docs and the examples are client side for VueJS.

Thanks

**Comment by RicLeP** [comment]
Okay, had a chance to look at this and this works. I don’t know if it’s the recommended method.

```php
public function schema() {
	return [
		...
		'school_id' => [
			'type' => 'select',
			'label' => 'School',
			'items' => School::all()->pluck('name', 'id')->toArray()
		],
		...
	];
}
```

**Comment by laraform** [comment]
This should work in some cases but as we are missing a complete example it's hard to tell. Check out this https://laraform.io/docs/1.x/basics/relationships or provide a full example with form, model, migrations, etc. please.

**Comment by laraform** [comment]
I'm closing this now but you'd like to provide further example feel free to reopen.
