### ISSUE TITLE
[QUESTION] Field label translation

### ISSUE THREAD

**Issue by fredol** [laraform/laraform#32]
### Prerequisites

* [X ] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [X ] Your question isn't already asked before.
* [X ] You filled in the entire issue template.

### Versions

* PHP version: 7.3.12
* Laravel version: 6.7
* Laraform Vue package version: 1.1.8
* Laraform Laravel package version: 1.1.8

### Description

Hi all

How do I manage labels translation? I use the package for a multilingual project (3 languages) and need to display fields label in user language.

Thanks for your help

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by laraform** [comment]
Hi, I'd recommend this approach:

```
data() {
  return {
    name: {
      type: 'text',
      label: this.myTranslationMethod('label.name')
    }
  }
}
```
