### ISSUE TITLE
[BUG] Unique rule frontend validation

### ISSUE THREAD

**Issue by thomasilmer** [laraform/laraform#33]
### Prerequisites

* [X] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [X] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration).
* [X] Your issue isn't already filed.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 7.3.3
* Laravel version: 6.9.0
* Laraform Vue package version: 1.1.8
* Laraform Laravel package version: 1.1.8

### Description

When defining a unique rule for an input with name "email" like this: "unique:user_invites,email", the request made by the frontend to the unique validation endpoint is this: 
['params' => ['users', FILLED_EMAIL_VALUE], 'value' => FILLED_EMAIL_VALUE]

I would expect the request to be:
['params' => ['users', 'email'], 'value' => FILLED_EMAIL_VALUE]

### Steps to Reproduce

Make a form extending Laraform and include an input in the schema with a 'unique' rule. When you type in this input and wait for the ajax request to be sent, you will see that the request params are changed when sent back to the backend.

**Expected behavior:**

Request to unique validator should be:
['params' => ['users', 'email'], 'value' => FILLED_EMAIL_VALUE]

**Actual behavior:** 

Request to unique validator is:
['params' => ['users', FILLED_EMAIL_VALUE], 'value' => FILLED_EMAIL_VALUE]

### Additional Information

It seems like the frontend fills every parameter defined in the 'unique' rule with a Vue data property.

I have read https://github.com/laraform/laraform/issues/22, but this seems to be a seperate issue.

**Comment by laraform** [comment]
Hi @thomasilmer. Could you provide a schema as an example? Thank you!

**Comment by laraform** [comment]
So, I've looked into it and the thing is that as described in #22 this rule works differently than 
the Laravel version for security reasons. It wouldn't be wise to expose table and column names to the frontend, even if it was more convenient.

So the params you are passing to the unique rule (like `unique:param1,param2`) are transformed to form values if they are found. This also reflects to your email:

> there seems to be no way to get the current model’s ID to set as ignored in the ‘unique’ rule.

Also the `ValidatorController.php` file in backend package is just a leftover and should not be used. You should implement your own version of unique/exists validation rule, even as suggested here: https://github.com/laraform/laraform/issues/22#issuecomment-562821874

Hope this helps, but feel free to reopen.
