### ISSUE TITLE
[BUG] Usage of Select within List

### ISSUE THREAD

**Issue by romeosemper** [laraform/laraform#34]
### Prerequisites

* [X] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [X] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration).
* [X] Your issue isn't already filed.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 7.4 
* Laravel version: 6.7
* Laraform Vue package version: 1.1.8
* Laraform Laravel package version: 1.1.8

### Description

When using a select element within a list as the element (at least in async mode), it produces a vue warning:
Invalid prop: type check failed for prop "name". Expected String with value "0", got Number with value 0.

### Steps to Reproduce

I just changed the async select example from the docs and added a list wrapper:
`
schema: {
                mylist:{
                    type:'list',
                    element:{
                        type: 'select',
                        search: true,
                        items: {},
                        slots: {
                            noOptions: Vue.extend({
                                props: ['el$'],
                                template: "<span>Start typing...</span>"
                            })
                        },
                        options: {
                            'internal-search': false
                        },
                        created() {
                            this.on('searchChange', (searchQuery) => {
                                this.loading = true
                                if (this.timeout) {
                                    clearTimeout(this.timeout)
                                }
                                this.timeout = setTimeout(() => {
                                    if (!searchQuery) {
                                        this.loading = false
                                        return
                                    }
                                    this.items = {
                                        searchQuery: searchQuery,
                                        [searchQuery + '1']: searchQuery + '1',
                                        [searchQuery + '2']: searchQuery + '2',
                                    }
                                    this.loading = false
                                }, 400)
                            })
                        }
                    }
                }
            }
`

Sorry for the codestyle, somehow github seems to remove my formatting. 

**Expected behavior:**

Not getting a Vue Warn

**Actual behavior:** 

Get a Vue Warn

### Additional Information

It still seems to work okay, but you get an additional Vue Warn whenever opening the select box.
Trace:

`
[Vue warn]: Invalid prop: type check failed for prop "name". Expected String with value "0", got Number with value 0.

found in

---> <VueMultiselect> at node_modules/vue-multiselect/src/Multiselect.vue
       <BaseElementLayout> at node_modules/@laraform/laraform/src/themes/bs3/components/BaseElementLayout.vue
         <SelectElement> at node_modules/@laraform/laraform/src/themes/default/components/elements/SelectElement.vue
           <MultiElementLayout> at node_modules/@laraform/laraform/src/themes/default/components/NestedElementLayout.vue
             <ListElement> at node_modules/@laraform/laraform/src/themes/default/components/elements/ListElement.vue
               <FormElements> at node_modules/@laraform/laraform/src/themes/bs3/components/FormElements.vue
                 <Laraform> at node_modules/@laraform/laraform/src/components/Laraform.vue
`

**Comment by laraform** [comment]
Fixed in 1.1.9, please upgrade:
`npm install @laraform/laraform --save`
