### ISSUE TITLE
[BUG] Call to undefined method Illuminate\Support\Facades\Auth::extend()

### ISSUE THREAD

**Issue by skillcraft-io** [laraform/laraform#35]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

* PHP version: PHP 7.2.24
* Laravel version: v6.9.0
* Laraform Vue package version: 1.1.8
* Laraform Laravel package version: 1.1.8

### Description

When latest version of Passport is installed this error occurs. Downgrading passport to less then 8.0 (7.5.1 works) resolved this issue.

### Steps to Reproduce

Install Laravel with Latest Passport and Laraform Pro Package
Install and compile laraform into app.js
Build a form and try load page

**Expected behavior:**

The form should load

**Actual behavior:** 

Error Output:

Symfony\Component\Debug\Exception\FatalThrowableError
Call to undefined method Illuminate\Support\Facades\Auth::extend()

**Comment by laraform** [comment]
Fixed in 1.1.9, please upgrade:
`composer require laraform/laraform-laravel`

**Comment by paligiannis** [comment]
Seems like I have the same issue again
PHP 7.4
LARAVEL 8.23
laraform/laraform-laravel": "^1.2
