### ISSUE TITLE
[BUG] Class constructor Rule cannot be invoked without 'new'"

### ISSUE THREAD

**Issue by skillcraft-io** [laraform/laraform#36]
### Prerequisites
* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions
* PHP version: 7.2.24
* Laravel version: 6.9
* Laraform Vue package version: 1.1.8
* Laraform Laravel package version: 1.1.8

### Description

When creating a new unique Async rule, the rule cannot be invoked and throws a error in the console. I tried globally registering and just registering on the component, with out difference in result.

`
[Vue warn]: Error in mounted hook: "TypeError: Class constructor Rule cannot be invoked without 'new'"
`

### Steps to Reproduce

Create new Async Rule
Register Rule Globally
Apply Rule on a Text Field
Compile & run the form, watch console.

**Expected behavior:**

I would expect the console not to throw an error and my async rule to be run on field input.

**Actual behavior:** 

Console throws and error and the rule is never applied/run.

### Additional Information
I tried to implement the document uppercase custom rule and the same console error occurs.

**Comment by laraform** [comment]
Hi, I've looked into it and didn't notice the error you've described. Please provide example codes to see where things go wrong. As a reference I have this working with **async**:

``` js
// resources/js/rules/Uppercase.js

import Rule from '@laraform/laraform/src/utils/validation/rules/rule'

export default class Uppercase extends Rule {
  get message() {
    return 'The :attribute should only contain uppercase letters'
  }

  get async() {
    return true
  }

  async validate(value) {
    var response = await axios.get('/uppercase?value=' + value)

    return response.data.valid
  }
}
```

``` js
// resources/js/app.js

import Laraform from '@laraform/laraform/src'
import Uppercase from './rules/Uppercase'

Laraform.rule('uppercase', Uppercase)

Vue.use(Laraform)

const app = new Vue({
  el: '#app',
})
```

```php
<?php

// routes/web.php

Route::get('/uppercase', function (Illuminate\Http\Request $request) {
  return [
    'valid' => ctype_upper($request->value),
  ];
});
```

``` php
<?php

// app\Forms\TestForm.php

namespace App\Forms;

use Laraform;

class TestForm extends Laraform
{
    public function schema()
    {
        return [
            'name' => [
                'type' => 'text',
                'rules' => 'uppercase'
            ],
        ];
    }
}
```
