### ISSUE TITLE
[BUG] General error: 1364 Field 'name' doesn't have a default value

### ISSUE THREAD

**Issue by gabrielchavezme** [laraform/laraform#38]
### Prerequisites

* [x ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [ x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration).
* [ x] Your issue isn't already filed.
* [x ] You filled in the entire issue template.

### Versions

* PHP version: 7.3
* Laravel version: 6.9
* Laraform Vue package version: 1.1.8
* Laraform Laravel package version: 1.1.8

### Description

I am creating a contact form, where the user can add or remove contacts in their profile. When I save the data I get the following error:

SQLSTATE [HY000]: General error: 1364 Field 'name' doesn't have a default value (SQL: insert into `users` (` id`, `updated_at`,` created_at`) values (?, 2019-12-28 10:08:03, 2019-12-28 10:08:03))

### Steps to Reproduce

Illuminate\Database\QueryException

### App\Forms\ContactosDeConfianza
```
    public $model = User::class;
    public $endpoint = "/laraform/process";

    public $buttons = [
        [
            'label' => 'Guardar',
            'class' => 'btn-primary',
            'type' => 'submit'
        ],
    
    ];

    public function schema()
    {
        return [
            'id' => [
                'type' => 'key',
                
            ],
            'contacts' => [
                'type' => 'list',
                'label' => false,
                'object' => [
                    'label' => 'Contacto',
                    'schema' => [
                        
                        'name' => [
                            'label' => false,
                            'type' => 'text',
                            'placeholder' => 'Nombre completo',
                            'floating' => 'Nombre completo',
                            'rules' => 'required',
                            
                            'name' => 'name',
                        ],
                        'curp' => [
                            'label' => false,
                            'type' => 'text',
                            'max' => 16,
                            'placeholder' => 'CURP',
                            'floating' => 'CURP',
                            'rules' => 'required',
                            
                        ],

                    ],
                ],
            ],

        ];
    }

```

### Model User

```
    public function contacts()
    {
        return $this->hasMany(Contact::class);
    }
```

### Model Contact
```
protected $fillable = ['name', 'curp', 'user_id'];
    protected $table = 'contacts';

    public function user()
    {
        return $this->belongsTo(User::class);
    }
```
### Migration 
```
Schema::create('contacts', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('user_id')->unsigned();
            $table->string('name');
            $table->string('curp');

});
```

### Final Error

SQLSTATE[HY000]: General error: 1364 Field 'name' doesn't have a default value (SQL: insert into `users` (`id`, `updated_at`, `created_at`) values (?, 2019-12-28 10:08:03, 2019-12-28 10:08:03))

**Comment by laraform** [comment]
This doesn't have anything to do with Laraform, you're getting this error because you are trying to create a new record in `users` table without inserting `name` which does not have a default value.
