### ISSUE TITLE
Event to modify field after submit and before save (backend)...

### ISSUE THREAD

**Issue by gmartinez** [laraform/laraform#4]
Hi, testing laraform, I want to know if it is possible to modify a value after being submitted but before saved, so for instance I have first and last name, I'd like the concatenated value of these two to be the value for fullname existing property.

I tried getting and setting the data in the saving() event, data obtained after modification seems to work but concatenated data is not persisted.

´public function saving() {

    $_data = $this->getElements()->getData();
    $_data['name'] = $_data['firstname'].' '.$_data['lastname'];
    $this->getElements()->setData($_data);
    // dd($this->getElements()->getData());  <<< shows field name modified correctly

}´

**Comment by laraform** [comment]
Hi, you can use **before()** hook in you form class:

``` php
<?php

namespace App\Forms;

use Laraform;

class MyForm extends Laraform
{
  public $schema = [
    'firstname' => [
      'type' => 'text',
    ],
    'lastname' => [
      'type' => 'text',
    ],
  ];

  public function before() {
    $this->setData(array_merge($this->data, [
      'name' => $this->data['firstname'] . ' ' . $this->data['lastname']
   ])); 
  }
}
```

**Comment by gmartinez** [comment]
That worked beautifully, thanks !
