### ISSUE TITLE
[QUESTION] - Hide or Disable Form On Submit

### ISSUE THREAD

**Issue by skillcraft-io** [laraform/laraform#40]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.2
* Laravel version: 6.6
* Laraform Vue package version: 1.1.8 (Pro)
* Laraform Laravel package version: 1.1.8 (Pro)

### Description

When my form is submitted, I would like to replace the form with a Spinner or shad the fields and maybe display a text.

1.) When a form gets submitted, is there a way to either "shade" the entire form or form each form fields, until a response event is received?

2.) Display a "Spinner" on submission, could be any one of these.
    1.) Could be on the button
    2.) Above/Below form
    3.) Replaces the Form

### Additional Information
Not Right now

**Comment by laraform** [comment]
You can achieve that by using custom template:
https://laraform.io/docs/1.x/basics/customizing-layout#form-layout

`submitting` is an available prop on the main Laraform component:
https://laraform.io/docs/1.x/reference/frontend-form#prop-submitting

Buttons have a `disabled` property which should return `false` to disable the button:
https://laraform.io/docs/1.x/reference/frontend-button#option-disabled
You can play around the CSS after that to add the spinner.

**Comment by laraform** [comment]
Closing this down but feel free to reopen if you still have question.
