### ISSUE TITLE
[QUESTION] Do you think charging hundreds of dollars a year for a new product while in [beta] is ethical?

### ISSUE THREAD

**Issue by defenestrator** [laraform/laraform#42]
Because, if so, you're...like...wrong. 

Poor form, so to speak.
Sure, delete this. But have a moment of reflection first, please.

**Comment by skillcraft-io** [comment]
Why would this be unethical?

Time is money and a developer has every right to charge for his time already invested and for future time commitment.

There is a community version your welcome to use if your not willing to financially support this project.
