### ISSUE TITLE
[QUESTION] Binding Vue attributes/form events with Laravel rendering?

### ISSUE THREAD

**Issue by oletas** [laraform/laraform#44]
* [X] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [X] Your question isn't already asked before.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 7.4.1
* Laravel version: 6.9.0
* Laraform Vue package version: 1.1.8
* Laraform Laravel package version: 1.1.8

### Description

First, we're loving LaraForm, and have a paid version. :)

Question is how to get the v-bind, v-on:my-event="triggerEvent", etc attributes added to the LaraForm component when using backend style rendering with $myForm->render() ?

### Additional Information

I figure we're just missing an obvious setting -- but for now are working around it by overriding render() in our Laravel Form classes, a lot like this -- simplified/compacted for brevity:

```php
// MyForm.php

public $attributes = [
    'v-bind:settings="settings"',
    'v-on:my-event="triggerEvent"',
];

public function render()
    {
    $model = $this->storePath ? "store-path=\"{$this->storePath}\"" : '';
    $form = ":form=\"{$this->toProp()}\"";
    $attributes = implode(' ', $this->attributes);

    return "<{$this->getComponent()} $form $model $attributes></{$this->getComponent()}>";
    }
```

**Comment by laraform** [comment]
Awesome, thank you for supporting the project ❤️ I'm glad you like it!

Yes, currently that's exactly how you can do that and I took a note to add this feature.

I'm closing this now, but feel free to reopen if you'd like to add anything.
