### ISSUE TITLE
[QUESTION] - Dynamic Lists

### ISSUE THREAD

**Issue by skillcraft-io** [laraform/laraform#45]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.2.24
* Laravel version: Latest
* Laraform Vue package version: 1.1.8
* Laraform Laravel package version: 1.1.8

### Description

Is it possible to provide the "item" options to a dropdown/checkbox from a controller?

The project I am using Laraform with calls to a 3rd party API, and included in the response is a list of dropdown/checkbox options. 

Now, this list may be different on each call, so I would want to load the items array from a controller and load the form from the blade template using the render command.

**Comment by laraform** [comment]
The `schema` property is public and can be modified, but you need to call `setElements()` after:

``` php
$form = app('App\Forms\MyForm');

$form->schema['mySelect']['items']['foo'] = 'bar';

$form->setElements();
```

This should work even if you are using `schema()` method.

**Comment by skillcraft-io** [comment]
@laraform 

Thank you, this work perfectly and is exactly what I need to accomplish what I wanted to do..

Is this in the documentation anywhere? I scoured the docs pretty heavily since purchasing and don't recall seeing this setElements().

**Comment by laraform** [comment]
Great! No, because there's no section about modifying schema on the flight. That's definitely something needs to be improved and I'm already thinking about other use cases. Thanks for bringing this up @zhxscript !
