### ISSUE TITLE
[BUG] Datetime picker switching days and months on submission when using english date format

### ISSUE THREAD

**Issue by IllesAprod** [laraform/laraform#46]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

* PHP version:  7.4.0
* Laravel version:  6.2.1
* Laraform Vue package version and type:  1.1.8 pro 
* Laraform Laravel package version: not used 

### Description

Datetime picker switching the day and month attribute upon submission

### Steps to Reproduce

Using only the javascript package. Create a Form:

```
    export default {
        name: "App",
        mixins: [Laraform],

        data() {
            return {
                schema: {
                    datetime: {
                        type: "datetime",
                        label: "Start Date",
                        default: '01.06.2020 16:00',
                        format: "d.m.Y H:i",
                        dataFormat: "DD.MM.YYYY HH:mm",
                    }
                },
                buttons: [
                    {
                        label: "Save",
                        class: "btn btn-primary",
                        onClick() {
                            return this.form$.submit();
                        }
                    }
                ]
            }
        }
    }
```
Open console -> network
Click on submit

**Expected behavior:**
Request data should be 01.06.2020 16:00

**Actual behavior:** 
Request data is: 06.01.2020 16:00

![image](https://user-images.githubusercontent.com/10177368/72518293-4dfca500-3855-11ea-8174-76059dd83307.png)

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by laraform** [comment]
Based on the example you provided I'm getting the right request data. 

<img width="156" alt="Képernyőfotó 2020-01-27 - 9 17 42" src="https://user-images.githubusercontent.com/45842259/73159071-e4e32000-40e5-11ea-9fbf-4115a9ac0985.png">
<img width="317" alt="Képernyőfotó 2020-01-27 - 9 16 14" src="https://user-images.githubusercontent.com/45842259/73158996-bb29f900-40e5-11ea-8e16-1fca4baa564c.png">

Could you double check you're having the latest update?
