### ISSUE TITLE
[DOCS] Examples produce errors

### ISSUE THREAD

**Issue by mike2410** [laraform/laraform#47]
### Prerequisites

* [ x] You've provided enough information to spot the issue.
* [x ] You filled in the entire issue template.

### Description

SimpleLoginForm.php
`  public function buttons() {
    return [[
      "label": "Login",
      "class": "btn-primary"
    ]];
  }`

":" should be "=>"

SimpleLoginForm.php
`  "title" => [
        "type" => "html",
        "html" => "<h5>Log in to your account</h5>"
      ],`  

Produced an error on my side, sth. about <html-element> not existing.

login.blade.php
`  {{ $loginForm->render() }} `  

Should be {!! !!}?

### Additional Information

Found at [https://laraform.io/examples](https://laraform.io/examples)
Using premium versions "@laraform/laraform": "^1.1.10", "laraform/laraform-laravel": "^1.1", on laravel 6

**Comment by laraform** [comment]
Thanks, fixed. Welcome @mike2410!

**Comment by mike2410** [comment]
Thank you, glad I could help. As I recall there might be quite some more instances of {{ }} being used in the docs instead of {!! !!} ;-)
