### ISSUE TITLE
[IDEA] Google Recaptcha

### ISSUE THREAD

**Issue by skillcraft-io** [laraform/laraform#48]
### Prerequisites

* [x] You've described your idea in a clean format with example.

### Description

Adding a field type for Google/Any Recaptcha would be awesome. 
All sorts of forms use a captcha system to help prevent spam.

What you think?

### Example

No sure how it would work/look like. But I would image you are familar with form captchas :)

**Comment by skillcraft-io** [comment]
Interesting, this was driving me nuts, so I dug and I was able to implement Google Recaptcha using vue-recaptcha package. I am not sure if its the best way, as I am just not a strong frontend developer, but it works. Essentially I added the captcha and on the events a set a hidden field with the valud returned from verify. When the form is submitted, it is verified via a server call.

https://prnt.sc/qs0lqy

What you think about implementing this as part of the pro package?

**Comment by laraform** [comment]
Looks nice @zhxscript! When contributions will open up I'll sure expect to see this as part of the pro! I'll get back with the details as soon as I have them.

**Comment by laraform** [comment]
Closing this for now.
