### ISSUE TITLE
[IDEA] min and max for List

### ISSUE THREAD

**Issue by mike2410** [laraform/laraform#49]
### Prerequisites

* [x ] You've described your idea in a clean format with example.

### Description

It would be very useful if it were possible to regulate the amount of repetitions allowed. Something like this:

### Example

```
        'appointment_suggesstions' => [
            "type" => "list",
            "label" => "Suggest an Appointment",
            "initial" => 1,
            "min" => 1,
            "max" => 3
             ...
             ]
```
### Additional Information

Enable/disable remove and add button respectively.

**Comment by laraform** [comment]
Until it gets implemented use min/max/between rules to limit the number of list elements. Closing this for now but took note of the request.
