### ISSUE TITLE
[QUESTION] Manually Setting Errors

### ISSUE THREAD

**Issue by skillcraft-io** [laraform/laraform#50]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.2.24
* Laravel version: 6.12
* Laraform Vue package version and type: 1.1.9 Pro
* Laraform Laravel package version: 1.1.10 Pro

### Description

In my custom component I have a custom form layout. When I submit the form to the server, I am trying to get the fields to display the errors returned from the post, rather then display the errors above the form, like in the image below. I do not see in the docs anywhere that explains how to do this.

### Additional Information

Here is an image of my form.
https://prnt.sc/qr301t

I just want to be able to set each fields error if contained in the response from the server.

**Comment by skillcraft-io** [comment]
Nevermind, I figured a way to accomplish this

**Comment by skillcraft-io** [comment]
I am reopening this because the way I accomplished this was with a custom form, and it works fine.

But I cant get it to work for the wizard I built.. this is my Wizard Form Component

`<template>
    <div>
        <error-messages :errors="cleanedErrorMessages" v-if="validationErrors"></error-messages>
        <success-messages :success="validationSuccess" v-if="success"></success-messages>
        <form
                :class="formClass"
                @submit.prevent="submit"
                ref="form$"
                v-if="displayForm"
        >

            <FormWizard
                    v-if="hasWizard"
                    :steps="wizard"
                    :elements$="elements$"
                    @submit="handleSubmit"
                    ref="wizard$"
            />


            <FormElements
                    :schema="schema"
                    ref="elements$"
            />

            <FormWizardControls
                    v-if="hasWizard"
                    :wizard$="wizard$"
            />

            <FormButtons
                    v-if="!hasWizard"
                    :buttons="buttons"
            />
        </form>
    </div>
</template>`

The Wizard Works great, my problem is sometimes there is a server side error and i want to assign it to a specific field and not have a ABOVE form error displayed..

Hows this possible, I cant find anything in the docs

**Comment by laraform** [comment]
That's currently not possible unless with some hacky solutions as we discussed in an other channel. Closing this for now, but will keep that in mind.

**Comment by JanCusters** [comment]
@ zhxscript can you show me an example of how you achieved this with a custom form? I'm struggling to get it to work :/
