### ISSUE TITLE
[BUG]  Call to undefined method Illuminate\Support\Facades\DB::extend()

### ISSUE THREAD

**Issue by gabrielchavezme** [laraform/laraform#52]
Based on bug #37, update laraform to the latest version and follow the problem.

In my controller I have removed the variable:

`$form = resolve('App\Forms\ConfidenceContacts');`

And stop the error, apparently it is a dependency error when the global helper resolve () is called.

I attach errors uploaded to flare for a more detailed debug: https://flareapp.io/share/o7AnOJ5p#F85

I tried to solve the error but I could not, apparently butt wall.

**Comment by laraform** [comment]
Answered and reopened #37, closing this for now.
