### ISSUE TITLE
[QUESTION] Highlight required fields

### ISSUE THREAD

**Issue by mike2410** [laraform/laraform#53]
### Prerequisites

* [x ] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [ x] Your question isn't already asked before.
* [x ] You filled in the entire issue template.

### Versions

* PHP version: 
* Laravel version: 
* Laraform Vue package version and type: 
* Laraform Laravel package version: 

### Description

Is there any way to highlight fields which are required before any validation takes place? 

### Additional Information

You know, the classic * or something.

**Comment by laraform** [comment]
Hi! As fields don't have a "required" property but being required via validation rules, you have to take care of inserting the extra * by yourself or adding a class that will distinguish them.

**Comment by mike2410** [comment]
Thanks for the heads up! Well I supposed one could trigger validate as soon as the form loads since this would by default then mark all the required ones; however that does not sound pretty ;-) Any other idea how this could be achieved without having to changed every component used?

**Comment by laraform** [comment]
Maybe adding a simple `*` after the label? Or even a `<sup>*</sup>`.

Triggering validation on load might be achieved:

``` vue
mounted() {
  this.validate()
}
```

... but it will also display errors for all validation rules.

**Comment by mike2410** [comment]
Thanks for getting back to me! So as of now, there is no way to determine whether fields are required on initial without changing core files (or overriding every component I'd need this for), right? Or where would you add the <sup>*</sup> you suggested?

**Comment by laraform** [comment]
Manually you can add `*` directly to the label, like this:

``` js
name: {
  type: 'text',
  label: 'Name <sup>*</sup>'
}
```

There might be a way to check on load if any of the fields has `required` validation rules:

``` js
mounted() {
  _.each(this.elements$, (element$) => {
    _.each(element$.Validators, (Validator) => {
      if (Validator.Rule.name == 'required') {
        element$.label += '<sup>*</sup>'
      }
    })
  })
}
```
To make this work with nested elements it need some more advanced logic, but you get the idea.

**Comment by mike2410** [comment]
ah i see, thanks for you effort! i suppose there's no built-in function to do this recursively?
cheers!

**Comment by laraform** [comment]
No, I'm afraid there's no, but nested elements have a `children$` property - you can build up from that.
