### ISSUE TITLE
[BUG] Numeric Max Rule not validating properly

### ISSUE THREAD

**Issue by skillcraft-io** [laraform/laraform#54]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.2.24
* Laravel version: 6.10
* Laraform Vue package version and type: 1.1.10 PRO
* Laraform Laravel package version: 1.1.9 PRO

### Description
I have a form that has a Numeric Field, InputType Float (To allow for decimals). However the MAX rule does not properly validate with the decimals.

### Steps to Reproduce

Create a new form:

- type: Text
- inputType: float
-rule: required & max:1

Render the form and enter 1.01 in to the field

**Expected behavior:**

The value 1.01 SHOULD be considered invalid.

**Actual behavior:** 

The form will not correctly validate the value exceeds max until 1 is whole @ 2.

### Additional Information
 None at this time.

**Comment by laraform** [comment]
In order to validate a field as a number you should add `numeric` rule too, eg:
```
rules: 'required|numeric|max:1'
```

Anyway there was indeed a bug in the validating algorithm which is now fixed in 1.1.11, thanks for reporting.
