### ISSUE TITLE
[IDEA] Changing Trix File Response Requirement

### ISSUE THREAD

**Issue by skillcraft-io** [laraform/laraform#55]
### Prerequisites

* [x] You've described your idea in a clean format with example.

### Description

So mostly anytime I write an API Response my response generally is an object, containing a message, maybe some data for the request to parse or other useful items, However, when using TRIX and the image uploade, the editor adds in the image via  **response.data**. 
I feel it could be either configurable or set to accept the image from the response on a specific key, like image or src etc, allowing for other response data to be included.

Not that it would be to hard to make a dedicated endpoint for just images, but it took me quite a bit to figure out why the image was not properly being added to the editor when i reloaded the content in a new page. It drove me nuts because I already had a trix editor installed and working, externally from Laraforms, but wanted to bring all my forms to Laraforms, as it is worthy of being including in my SaaS Platform I am building :)

Also adding a little information on image handling in the docs would have saved me some time here tonite :)

### Example

Currently this is what happens inside @laraform/laraform/src/components/wrappers/Trix.vue

```
 return e.attachment.setAttributes({
            url: response.data,
            href: response.data,
          })
```
Maybe changing it to something like this:

```
 return e.attachment.setAttributes({
            url: response.data.url,
            href: response.data.href,
          })
```

**Comment by laraform** [comment]
Thanks @zhxscript for reporting, was replaced as proposed in 1.1.11, please update.
