### ISSUE TITLE
[BUG] Default Laravel project layout is assumed (hardcoded App\Http\Controllers\Controller)

### ISSUE THREAD

**Issue by pzmarzly** [laraform/laraform#56]
### Prerequisites

* [X] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [X] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [X] Your issue isn't already filed.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 7.3.11-0ubuntu0.19.10.2
* Laravel version: latest ATM
* Laraform Vue package version and type: 1.0.5 community
* Laraform Laravel package version: 1.0.4 community

### Description

In the file `vendor/laraform/laraform-laravel/src/Controllers/FormController.php` line 6, there is a hardcoded path: `use App\Http\Controllers\Controller;`. If you don't have your base controller in that path, Laravel will work just fine, but Laraform will not.

### Steps to Reproduce

- Create new Laravel app.
- Move `App\Http\Controllers\Controller` somewhere else (maybe `App\Base\Controller`) and update all references across the project
- Install Laraform.
- Send a POST request to `/laraform/process`.

**Expected behavior:**

There should be a field in `config/laraform.php` that would allow to set path to the base controller.

**Actual behavior:** 

You get `Class 'App\Http\Controllers\Controller' not found` exception (error 500), due to that hardcoded path.

**Comment by laraform** [comment]
Thanks for reporting @pzmarzly, fixed in 1.1.10, please update.

Finally the base controller was replaced by `Illuminate\Routing\Controller`.
