### ISSUE TITLE
[DOCS] Typographical error on backend configuration page

### ISSUE THREAD

**Issue by blhylton** [laraform/laraform#57]
### Prerequisites

* [ X ] You've provided enough information to spot the issue.
* [ X ] You filled in the entire issue template.

### Versions

N/A

### Description

https://laraform.io/docs/1.x/basics/configuration#configuration

> After publishing Laraform's **asses**...

The first sentence under the top heading, emphasis mine.

### Additional Information

N/A

**Comment by laraform** [comment]
Thanks, corrected.
