### ISSUE TITLE
[DOCS]Need options fixed

### ISSUE THREAD

**Issue by yespbs** [laraform/laraform#59]
### Prerequisites

* [ X] You've provided enough information to spot the issue.
* [ X] You filled in the entire issue template.

### Description
1. 
	https://laraform.io/docs/1.x/reference/radiogroup-element#options
	default should be string as radiogroup can select only one

### Additional Information

Any additional information that might be needed to understand the idea.

**Comment by laraform** [comment]
Thanks @yespbs, fixed.
