### ISSUE TITLE
[BUG] Toggle: Default values throw error in vue

### ISSUE THREAD

**Issue by mike2410** [laraform/laraform#61]
### Prerequisites

* [ x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [ x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [ x] Your issue isn't already filed.
* [x ] You filled in the entire issue template.

### Versions

* PHP version: 7.4
* Laravel version: 6.0
* Laraform Vue package version and type: 1.1.10|pro
* Laraform Laravel package version: 1.1.9|pro

### Description

Repopulating a toggle from database fails when creating a form at the backend, since boolean seems to cause problem with vue loading the value.

### Steps to Reproduce
SignupForm.php

```
                'accept' => [
                    'type' => 'toggle'
                ],

```
**Expected behavior:**

Should repopulate toggles when retrieved via ->load

**Actual behavior:** 

Vue throws error because it doesnt seem to be able to retrieve boolean from db.

### Additional Information

Explicitly setting true/false to 0/1 seems to fix this:
```
                'accept' => [
                    'type' => 'toggle',
                    "trueValue" => 1,
                    "falseValue" => 0
                ],
```

**Comment by karlerss** [comment]
Would adding:
```
protected $casts = [
    'accept' => 'boolean',
];
```
to the model fix your problem?

**Comment by mike2410** [comment]
will try and let you know, thanks for your suggestion!
