### ISSUE TITLE
[IDEA] Server Errors Return with field name

### ISSUE THREAD

**Issue by skillcraft-io** [laraform/laraform#63]
### Prerequisites

* [x] You've described your idea in a clean format with example.

### Versions

Pro Version

### Description

I think it would ideal if the errors array returned the field name when the error is generated via backend.  Instead of the current numeric array key that is not useful.

### Example

Current Response Is:
`messages: ["The email must be an integer."]
0: "The email must be an integer."` <-- Expanded in browser console

Suggested response
`messages: ['field_name'=>"The email must be an integer."]
field_name: "The email must be an integer."`

Could Also be:
`Suggested response
`messages: ['field_name'=>["The email must be an integer."]]
field_name:[0: "The email must be an integer."]` to return multiple errors if present

### Additional Information

No Additional Information Atm

**Comment by mike2410** [comment]
+1, I really think we should be able determine which elements failed how. I mean what use is the backend side validation otherwise ...
