### ISSUE TITLE
[DOCS] Add example of using string with conditions

### ISSUE THREAD

**Issue by grantholle** [laraform/laraform#64]
### Prerequisites

* [X] You've provided enough information to spot the issue.
* [X] You filled in the entire issue template.

### Description

In the [Binding Conditions](https://laraform.io/docs/conditions#binding-conditions) section, it says

> Each condition can be either an array, a function or a string.

But only provides examples using an array or function. It would be helpful what a string condition looks like.

**Comment by laraform** [comment]
Hi @grantholle, in fact it's in the docs but under the name of "Global Function":
https://laraform.io/docs/1.x/basics/conditions#global-function

**Comment by grantholle** [comment]
I see, thanks!
