### ISSUE TITLE
[QUESTION] Remove Unrequired Div Tags

### ISSUE THREAD

**Issue by skillcraft-io** [laraform/laraform#66]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 
* Laravel version: 
* Laraform Vue package version and type: 
* Laraform Laravel package version: 

### Description

How can one go about removing the div tags the form seems to be placing on every element. 
There also seems to be that the entire form fields are wrapped in a global **row div**

![remove_unneeded_divs_2](https://user-images.githubusercontent.com/41481716/75396413-6afbad80-58c2-11ea-8bd2-fd19d436568c.png)

These extra divs are playing with the alignment of my form  here is a side by side of what I am trying to produce:

![designer_comparison](https://user-images.githubusercontent.com/41481716/75396670-1147b300-58c3-11ea-8f86-4f33bbf13732.png)

I cannot seem to get this checkbox in place, and as you can see Ill be adding the forgot password text as well..

### Additional Information

Is there a way to set a particular form to use a specific Layout (rather then the default Layout)? I don't seem to see anything in the documents about layouts, just overriding elements, which is not really what i need to do, as you can see, I have gotten them to render fine.

**Comment by laraform** [comment]
Have you tried setting `label` to `false` on checkbox element? Also having the Checkbox and Forgotten password in a group with 6-6 `columns` might solve the second problem:

``` php
'bottom' => [
  'remember_me' => [
    'type' => 'checkbox',
    'text' => 'Remember me',
    'label' => false,
    'columns' => 6
  ],
  'forgotten' => [
    'type' => 'static',
    'content' => '<a href="">Forgot password?</a>',
    'label' => false,
    'columns' => 6
  ]
]
```

If that doesn't work out you can replace the `BaseLayoutElement` with something else globally, after `Vue.use(Laraform)` in `app.js`:

``` js
import Laraform from '@laraform/laraform/src'
import BaseLayout from './components/BaseLayout.vue'

Vue.use(Laraform)

laraform.themes.bs4.components.BaseElementLayout = BaseLayout
```

Unfortunately currently that's the only way to replace the layout on the flight. Or you can extend a `bs4` theme and set up a custom one which has a different `BaseLayoutElement` then make the form use that one. Here's more info on that:
https://laraform.io/docs/1.x/how-tos/creating-theme
