### ISSUE TITLE
[QUESTION] How to pass data from backend to fronted

### ISSUE THREAD

**Issue by mike2410** [laraform/laraform#68]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 
* Laravel version: 
* Laraform Vue package version and type: 
* Laraform Laravel package version: 

### Description

Is there a best way on how to pass data from backend to frontend (php -> vue)?
E. g. I'd like to pass messages for a dialog which appears upon form submission to the vue component, handling translation etc. in php

I found abusing some (unused) public props works, however I wonder whether there is a cleaner way.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by laraform** [comment]
I think what you are looking for is the `with()` method:

``` php
$form = app('App\Forms\YourForm')->with([
  'dialog_messages' => [
    // ...
  ]
]);
```

After that, in you component you can reach it with:

``` js
export default {
  mixins: [Laraform],
  // ...
  created() {
    console.log(this.dialog_messages)
  }
}
```

Be careful not to override general properties like `messages` as everything you pass over with `with()` method will be directly set as `data`.

**Comment by mike2410** [comment]
Oh sweet, that'll do nicely; thanks for helping out so quickly!
