### ISSUE TITLE
Define slots on the backend

### ISSUE THREAD

**Issue by sebabal** [laraform/laraform#7]
Hi is it possible to define slots on the backend? I am trying to modify some radio input groups as in the example at https://laraform.io/docs/1.x/reference/radiogroup-element

**Comment by laraform** [comment]
Hi! Nope, but you can define a Vue component for your form, then define the slot there for the element. https://laraform.io/docs/1.x/basics/rendering#attach-frontend-component-optional

**Comment by sebabal** [comment]
Got it thanks.
