### ISSUE TITLE
[QUESTION] Testing: Recommended approach

### ISSUE THREAD

**Issue by mike2410** [laraform/laraform#71]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 
* Laravel version: 
* Laraform Vue package version and type: 
* Laraform Laravel package version: 

### Description

Normally I test features hitting the endpoints with the corresponding verb and the payload:
$this->post('/some/endpoint/', ["my" => "data"]);

However, with auto processing this approach seems to fall flat (I don't want to disable it and handle every request in the specific controller)

### Additional Information

I'm curious how you'd approach this with auto processing in mind, any suggestion greatly appreciated!

**Comment by laraform** [comment]
What I can recommend is to set up a custom `FormController` in your project and just copy paste what we have at `vendor/laraform/laraform-laravel/src/Controllers/FormController.php@process` then set that as the default endpoint. That way you'll have full control over the flow while keeping auto-processing.

**Comment by mike2410** [comment]
Thanks for the reply Adam, so essentially just create the controller in question and copy what autoprocessing would to the respective action? Those the process method mentioned contain all the code autoprocessing would execute or do I need further dependencies to get the same result?

**Comment by laraform** [comment]
Yes, we're going to have a trait for that in the next version, but right now copy paste should work.

**Comment by skillcraft-io** [comment]
> Yes, we're going to have a trait for that in the next version, but right now copy paste should work.

I love traits and love when packages make life easy and implement traits, cannot wait

**Comment by mike2410** [comment]
... did this make it into any of the new releases btw? :-)

**Comment by laraform** [comment]
Not yet, but will soon! :)

**Comment by laraform** [comment]
Traits are out @mike2410 & @zhxscript ! :)

https://laraform.io/docs/1.x/basics/submitting-data#processing-traits

**Comment by mike2410** [comment]
sweet, great job on the update btw @laraform :)
