### ISSUE TITLE
[QUESTION] Migrations: Recommended approach

### ISSUE THREAD

**Issue by mike2410** [laraform/laraform#73]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 
* Laravel version: 
* Laraform Vue package version and type: 
* Laraform Laravel package version: 

### Description

Is there any way to create a database migration based on the schema of a form, respectively the persisted fields?

Manually reproducing the entire structure in the migration file seems kinda dirty, so how could this be handled?

**Comment by laraform** [comment]
No, there's no such feature. I'm afraid you're going to have to do it manually or write a script for that.

**Comment by skillcraft-io** [comment]
I am working to something similar, I have not had alot of time to perfect this, but this is something I am considering.

You could define your fields inside a function within your model and call the function. Of course I suppose the function could live anywhere, but I like it in the model.

Something like this, of course how you build the array is your call, this is just a general idea, non-tested.

`public static function modelFields(){ 
return [
 [
'name' => 'name'
'db_properties => [Define the DB Field Properties here],
'form_rules => [Define Laraform Rules Here]
]
];
}`

Then in your migration call the above and process the array for needed information. Building the migration file from the model array.

Inside your LaraForm form file, call the same array and process for the required info and or add form specific information and build the form fields.

if you try this, do let me know how it worked :)

**Comment by mike2410** [comment]
Thanks for your suggestion @zhxscript 
I ended up creating an instance of the form and retrieving its schema via via app($form)->schema()
I then filtered out the non-persisting fields and setup a mapping for each respective data type.
