### ISSUE TITLE
[BUG] Front-end timezone handling not working.

### ISSUE THREAD

**Issue by karlerss** [laraform/laraform#74]
### Prerequisites

* [ ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

* Laraform Vue package version and type: 1.1.13/ pro

### Description

If userTimezone is set, dateTime component throws TypeError: moment.tz is not a function.

### Steps to Reproduce

1. Set userTimezone in laraform.php.
1. Use dateTime component

**Expected behavior:**

Timezones are handled as described in documentation.

**Actual behavior:** 

Above error is thrown.

### Additional Information

As a workaround this seems to work:

```
import * as moment from 'moment-timezone';

if(!window.moment?.tz){
    window.moment = moment;
}
```

**Comment by laraform** [comment]
@karlerss thanks for reporting. That's correct, this is required for using the timezone feature. I've added to the [docs](https://laraform.io/docs/1.x/reference/datetime-element#converting-timezone).
