### ISSUE TITLE
[BUG] (Reoccurred) Call to undefined method Illuminate\Support\Facades\Auth::extend()

### ISSUE THREAD

**Issue by skillcraft-io** [laraform/laraform#75]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.3
* Laravel version:  7.2.2
* Laraform Vue package version and type: 1.1.13 Pro
* Laraform Laravel package version: 1.1.14 Pro

### Description

I install upgraded from L6 to L 7 as well as Passport to 8.4 and forms do not load and throw an error that was previously patched.

### Steps to Reproduce

Install Laravel with Latest Passport and Laraform Pro Package
Install and compile laraform into app.js
Build a form and try load page

**Expected behavior:**

A form should render

**Actual behavior:** 

Symfony\Component\Debug\Exception\FatalThrowableError
Call to undefined method Illuminate\Support\Facades\Auth::extend()

**Comment by laraform** [comment]
Fixed in 1.1.15, please update

**Comment by skillcraft-io** [comment]
@laraform - Awesome thanks!
