### ISSUE TITLE
[QUESTION] Accessing Failed Validation Rules

### ISSUE THREAD

**Issue by mike2410** [laraform/laraform#76]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 
* Laravel version: 
* Laraform Vue package version and type: 
* Laraform Laravel package version: 

### Description

Is there any to access the failedRules property on the the validator instance?

### Additional Information
 GetErrors only gives me the failing messages in an ordered array, however I also need to know which Rules failed on which inputs.

**Comment by skillcraft-io** [comment]
I have suggested  for the backend validations to return field name instead of the ordered array here

https://github.com/laraform/laraform/issues/63

**Comment by mike2410** [comment]
Thanks for mentioning, I commented on the issue as well.

Kinda sorta got there reflecting to the private validator instance, this seems everything but a pretty solution though.

I feel like the validator should be least accessible if no other interface is provided to make use of it.

**Comment by laraform** [comment]
What's the use case @mike2410 ? The user should not be able to submit an invalid form, so backend validation is just an extra protection layer in case the user somehow manages to bypass the frontend validation. That's why no interface is provided and the error messages are just simply listed. If some fields rely on solely backend validation it means that the user will only know about an error after submitting the form, which could've been avoided using async validator. But let's see the use case and maybe something will come up that I haven't thought about.

**Comment by mike2410** [comment]
So I have this elaborate form for authenticated users (think like some sort of profile, which wants to know a LOT).

Since there are a lot of different fields, I want (validly filled) to be persisted, regardless of there being invalid fields present.

Now, say user entered 30 / 100 fields validly yesterday. He submits the form, the data is persisted, however after submission we tell him: to complete your profile, you need to fill out those remaining fields
.
Sure, if it were a one off thing now, and we can assume the user will just fix the remaining fields right now we're good with fronted validation telling him what was not filled out (correctly).

However, if said user should return tomorrow to finish his data entry, I want to able to tell him upfront which fields are as of yet not correctly filled out
.
I want to able to maintain the ... "validation state", without having to check data outside the validation rules which come out of the box.

Were the validator accessible, this would be trivial: load the form, load the data which was persisted already, manually validate on the backend and thus receive which fileds are filled out and have that information returned to the as he comes back to the form.

**Comment by skillcraft-io** [comment]
@mike2410 - I do certainly agree that sometimes knowing which exact field is a problem coming from the back-end, I do a lot of forms that send data via API and to make async calls on each field to validate is not feasible, and is not a wise use of resources, but anyways

I was reading the above, but does running

`this.validate()`

when the form loads work for your use case?

This would run all the validation rules on load and anything required empty/not filled out should be noted as required.

I have not tried this, if I have time this weekend, I might explore this.

**Comment by mike2410** [comment]
Thanks for your thoughts @zhxscript! So what you suggest is (on the backend): instantiate the form, load the the existing data for the form, then validate the form, render the form and output it in the view?

**Comment by skillcraft-io** [comment]
@mike2410 

What I am proposing is running the form validation when the form is created. If you setData/load data into the form before rendering it, the _this.validate_  will run your rules you set on the form and mark invalid fields.


Placing this in your vue component will run all you validation rules, and flag fields not passing.

`mounted() {
      this.validate();
}`

I tested this on a form in my project this morning, it work to my understanding of what you want to do, which is mark fields the user still needs to enter within a form.

My form has a Email and Password Field, I used setData on the email field only and rendered the form:

`
$form = app('App\Forms\LoginForm');
$form->setData([
 'email' => 'zhxscript@outlook.com'
 ]);
`

In my component, 

` mounted() {
    this.validate();
}
`

When the Form renders

![login_laraform](https://user-images.githubusercontent.com/41481716/77823381-1ae65580-70d1-11ea-9aae-a5617711bd30.png)

The above shows the login email passes validation, but the password does not and was flagged

A secondary test I did was to use invalid data based on my rules and the result was expected:
![larafomr_login2](https://user-images.githubusercontent.com/41481716/77823436-9c3de800-70d1-11ea-845b-f6748032bfa6.png)

**Comment by mike2410** [comment]
Thanks @zhxscript for your effort, really appreciate it.

And sure, this approach would work, were the feedback only needed on the client side.

However, I want to be able to determine which user has as of now not completed their profile, and sent those a Notification or sth. ala "Hey btw, please provide for facebook account!"

You see, all the rules which constitute a valid data set already defined through the rules provided via the form; so why not leverage those instead of duplicating the whole logic?

**Comment by beadm** [comment]
So if I understand correctly having access to `Illuminate\Validation\Validator` instance would solve the problem?

**Comment by laraform** [comment]
Having access to `Illuminate\Validation\Validator` would solve the problem @mike2410 ?

**Comment by mike2410** [comment]
Yeah, it is pretty much is what getErrors uses anyway, right? @laraform

**Comment by laraform** [comment]
I've added `getValidator` method to main Laraform class to the latest release (1.1.15). You can use it to access the underlying `Illuminate\Validation\Validator` instance.

**Comment by skillcraft-io** [comment]
@laraform Great Work! thanks!

**Comment by mike2410** [comment]
awesome, thanks @laraform 
I hope I could illustrate why it is a sensible thing to access rather then just me being annoying ;-)

**Comment by laraform** [comment]
@mike2410 no, definitely not annoyed by receiving useful feedback based on a real life use case :)

**Comment by mike2410** [comment]
@laraform alright, glad it came across the right way. I mean maybe you could argue that the issue goes beyond the scope of the problem laraform tries solve, but then again, I feel like data entry and processing without duplication it's greates use after all :-)
Anyway, thanks @zhxscript @laraform this can obviously be closed.
