### ISSUE TITLE
[QUESTION] How to prefill data from url (GET) variables?

### ISSUE THREAD

**Issue by tonydotgit** [laraform/laraform#78]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.4
* Laravel version: 7.4.0
* Laraform Vue package version and type: 1.0.8 / community
* Laraform Laravel package version: 1.0.4 / community

### Description

I would like to know if it's possible to prefill forms with get parameters `test.com?email=test@example.com`.

**Comment by laraform** [comment]
At the moment this is not possible, but you can write your custom logic on the frontend that parses query params and update element values when the form is mounted.
