### ISSUE TITLE
[QUESTION] How to put custom backend validations?

### ISSUE THREAD

**Issue by tonydotgit** [laraform/laraform#79]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.4
* Laravel version: 7.4.0
* Laraform Vue package version and type: 1.0.8 / community
* Laraform Laravel package version: 1.0.4 / community

### Description

I'm trying to find a way on how to tell the Form class (in the backend) to use a custom validation (custom Rule class). So far, I see how the frontend works but the backend itself is not very clear in the documentation.

Also, it's kinda weird that the first page sells Laraform as "two-side validation" (Define your validation rules once and have them working on both frontend and backend.) and here is kinda weird, I'm not able to get this feature working on my end (basically I've to type the validations on my Laraform based class and also on my custom FormRequest class).

### Additional Information

My FormRequest class looks like this :
```php
<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

use App\Rules\AlphaSpaceRule;

class MyFormRequest extends FormRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return [
            'firstName' => ['required', new AlphaSpaceRule(), 'max:50'],
            'lastName' => ['required', new AlphaSpaceRule(), 'max:50'],
        ];
    }
}
```

And this is is my Laraform class:
```php
<?php

namespace App\Forms;

use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use Laraform\Laraform;

use App\Rules\AlphaSpaceRule;

class DefaultForm extends Laraform
{
    public $endpoint = '/submit';

    public $component = "default-form";
    public $class = "default-form";
    public $labels = false;
    public $formErrors = false;
    public $columns = [
        'element' => 12,
        'label' => 12,
        'field' => 12
    ];

    public function schema()
    {
        return [
            'firstName' => [
                'type' => 'text',
                'placeholder' => 'First Name',
                'floating' => 'First Name',
                'rules' => ['required', new AlphaSpaceRule(), 'max:50'], // Here my custom validation doesn't work
            ],
            'lastName' => [
                'type' => 'text',
                'placeholder' => 'Last Name',
                'floating' => 'Last Name',
                'rules' => ['required', new AlphaSpaceRule(), 'max:50'], // Here my custom validation doesn't work
            ],
        ];
    }
}
```

Any idea what I'm doing wrong here or how I could get this custom rule validated and also how to avoid to write the validations twice?

**Comment by laraform** [comment]
If you are using [auto-processing](https://laraform.io/docs/1.x/basics/submitting-data#auto-processing) feature you don't have to create separate form requests, so this is how two-sided validation works.  If you are using custom endpoint as I can see you have to take care of processing the form manually, but you can still rely on the form's `validate()` method to do that without writing form requests. Please refer to [Manual processing](https://laraform.io/docs/1.x/basics/submitting-data#processing-without-model) for this one.

Custom validation rules works if you **register** the rule on both backend and frontend. On the frontend refer to [our docs](https://laraform.io/docs/validation#custom-rule) on the backend you can learn about it at [Laravel's docs](https://laravel.com/docs/7.x/validation#using-extensions).

Also you can have different validation rules for the backend and frontend if you decide to go that way: https://laraform.io/docs/1.x/basics/validation#frontend-and-backend-rules

Hope this helps!

**Comment by tonydotgit** [comment]
@laraform ty for your response Adam,

So here is what I found:
Having this `'rules' => ['required', new AlphaSpaceRule(), 'max:50'],` causes this exception:
`message: "array_key_exists(): The first argument should be either a string or an integer"`.

If I switch that portion to this `'rules' => ['required', 'AlphaSpaceRule', 'max:50'],` causes this: `message: "Method Illuminate\Validation\Validator::validateAlphaSpaceRule does not exist."`.

Any advice on how to make it work in the backend? I'm relying on the form's `->validate()` method as you suggested:

```php
        $form->setData($request->data);
        $form->validate();
        if ($form->isInvalid()) {
            return response()->json($form->getErrors(), 400);
        }
        return response()->json([], 200);
```

> Custom validation rules works if you register the rule on both backend and frontend.

TY for this, I was missing to build the front-end side as well, might do later after getting the backend portion working.

**Comment by tonydotgit** [comment]
@laraform ignore my previous comment, I forgot to extend the Laravel's validator. It might be the final piece.

**Comment by tonydotgit** [comment]
@laraform ok so far I cannot make it work, not sure if I'm picking the right "Validator" class here.

```php
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Validator;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Validator::extend('noone', function ($attribute, $value, $parameters, $validator) {
            return preg_match('/^[a-zA-Z0-9-]+$/', $value) ? true : false;
        });
    }
}
```

The error returned is this: `message: "Method Illuminate\Validation\Validator::validateNoone does not exist."`

I'm curious if I've to tell the Form itself to extend the Laraform's Validator instead the default from Laravel, or what I might be doing wrong?

**Comment by tonydotgit** [comment]
@laraform so I made some progress here, the validator is registered properly, the problem is that laraform don't recognize it.

If I use `noone` outside of the form (like the following sample in a controller) it works:
```php
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

...

public function index(Request $request)
{
        $validator = Validator::make($request->all(), ['testvar' => 'noone']);
        if ($validator->fails()) {
            return response()->json($validator->errors(), 400);
        }

        return response()->json([], 200);
}
```

Any idea what it could be? I'm trying to find out myself in the package in the meantime hopefully I can find it and send you a PR back.

**Comment by laraform** [comment]
It seems that as the validator is being registered with the facade is not recognized when Laraform manually using Laravel's validator library. Until this gets fixed, I'd recommend separating the `backend` and `frontend` rules and using the validator class directly on the backend:

``` php
'rules' => [
  'frontend' => ['required', 'noone', 'max:50'],
  'backend' => ['required', new Noone, 'max:50']
]
``` 

Make sure you update to the latest backend package as that has patch for this one too.

**Comment by tonydotgit** [comment]
@laraform tyvm man, going to take a look

**Comment by tonydotgit** [comment]
@laraform this workaround worked for now, tyvm Adam!

**Comment by basvandertogt** [comment]
Can you describe what you did step by step to get the custom validation to work? I can't get it with this info.

**Comment by tonydotgit** [comment]
@basvandertogt just modified the schema to separate front and backend validations:

```php
    public function schema()
    {
        return [
            'firstName' => [
                'type' => 'text',
                'placeholder' => 'First Name',
                'floating' => 'First Name',
                'rules' => [
                    'backend' => ['required', new AlphaSpaceRule(), 'max:50'],
                    'frontend' => ['required', 'max:50'],
                ]
            ],
...
```

**Comment by basvandertogt** [comment]
@TonnyORG thank you for your reply! Where did you put the AlphaSpaceRule() class?
