### ISSUE TITLE
Overriding an element issue

### ISSUE THREAD

**Issue by sebabal** [laraform/laraform#8]
I am having some trouble overriding an element. I have followed pretty much the example at https://laraform.io/docs/style-and-theme#overriding-components trying to override the radio element extending the bs4 theme but I am getting the following error:

> Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "trix-toolbar" has already been used with this registry

Any ideas?

**Comment by laraform** [comment]
It's hard to tell without seeing the code, but something is attempting to register "trix-toolbar" which is already registered by Laraform (maybe Polymer, if you are using it). If you are not planning to use Trix and Address element with Laraform the quickest way is to import '@laraform/laraform/dist/essentials' instead of '@laraform/laraform'.

**Comment by sebabal** [comment]
Thanks was able to override elements, components, etc. Getting the hang of it and it is pretty easy to extend/customize, good job!

By the way according to your docs the extendTheme function is imported via:

`import { extendTheme } from '@laraform/laraform/src/utils'`

but it was not working I had to actually import like this in order for it to work:

`import utils from '@laraform/laraform/src/utils'`

and then call the extend function:

`export default utils.extendTheme...`

Cheers

**Comment by redetly** [comment]
У меня почему то трикс загружается 2 раза
`import Laraform from '@laraform/laraform'
import ProductWarningsForm from "./components/forms/ProductWarningsForm"
import MultiTagElement from './components/elements/MyMultiTagsElement'

Vue.use(Laraform);
Vue.component('MyMultiTagsElement', MultiTagElement)
const ProductWarnings = new Vue({
    el: '#product-warnings',
    components: {
        ProductWarningsForm
    }
});
`
Нигде второй раз трикс не подключался.
Из-за чего может выйти такая ошибка?
