### ISSUE TITLE
[BUG] Empty labels showing in the front-end up even with $labels = false

### ISSUE THREAD

**Issue by tonydotgit** [laraform/laraform#80]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.4
* Laravel version: 7.4.0
* Laraform Vue package version and type: 1.0.8 / community
* Laraform Laravel package version: 1.0.4 / community### Description

### Steps to Reproduce

Create a form class:
```php
<?php

namespace App\Forms;

use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use Laraform\Laraform;

use App\Rules\AlphaSpaceRule;
use App\Rules\AlphaNumericDashRule;
use App\Rules\PhoneNumberRule;

class DefaultForm extends Laraform
{
    public $component = "default-form";
    public $class = "default-form";

    // Hiding labels by default
    public $labels = false; // $labels is false here, they should not show up, should they?

    public $formErrors = false;
    public $columns = [
        'element' => 12,
        'label' => 12,
        'field' => 12
    ];

    public function schema()
    {
        return [
            'title' => [
                'type' => 'static',
                'content' => '<h5>Hello!</h5>',
            ],

            'firstName' => [
                'type' => 'text',
                'placeholder' => 'First Name',
                'floating' => 'First Name',
                'rules' => ['required', 'alpha_space', 'max:50'],
            ],
        ];
    }

    public function buttons()
    {
        return [[
            "label" => "Login",
            "class" => "btn-primary w-100"
        ]];
    }

    public function after()
    {
        // if (Auth::attempt(Arr::only($this->data, ['email', 'password']), $this->data["remember"])) {
        //     return $this->success("You are authenticated!");
        // }

        return $this->fail("Authentication failed");
    }
}
```

**Expected behavior:**

Label container (div) and the label element itself should not be rendered at all.

**Actual behavior:** 

Label container (the parent div that contains the label) and element shows up.

![Imgur](https://i.imgur.com/mitenCr.png)

![Imgur](https://i.imgur.com/3q3wiei.png)

**Comment by laraform** [comment]
Please refresh to latest version which was just published. This should be fixed.

**Comment by tonydotgit** [comment]
This has been fixed, thank you @laraform
