### ISSUE TITLE
[QUESTION] Frontend Only Rendering

### ISSUE THREAD

**Issue by mikewuu** [laraform/laraform#82]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: _not installed_
* Laravel version: _not installed_
* Laraform Vue package version and type: 1.0.9 (community)
* Laraform Laravel package version: _not installed_

### Description

Trying to render a form only using the community edition js lib but I'm running into a `Failed to mount component: template or render function not defined.` error.

```js
<script>
import Laraform from "laraform/dist/laraform";
export default {
  mixins: [Laraform],
  data: () => ({
    schema: {
      name: {
        type: "text"
      }
    }
  })
};
</script>
```
### Additional Information

Here's an example Code Sandbox

https://codesandbox.io/s/laraform-render-fobkh

**Comment by laraform** [comment]
Just leave out the `import` and it'll work.

Laraform is a global mixin which becomes available after installing it with `Vue.use(Laraform)`. The object you're importing here is the installer itself, that's why you're receiving this error.

**Comment by mikewuu** [comment]
Thanks, seems to work as a global mixin, but it's still not rendering:

`"TypeError: Cannot create property 'inject' on string 'Localized'"`

and a few others:

```
[Vue warn]: Error in mounted hook: "TypeError: Cannot read property '$refs' of undefined"
found in
---> <Laraform> at /components/TextInputForm.vue

       <App> at /App.vue

         <Root>
```

Here's the sandbox updated;

https://codesandbox.io/s/laraform-render-fobkh

**Comment by laraform** [comment]
I've tested locally and it works with the provided code, so the issue must be with compiling the code or something in the CodeSandbox environment.

**Comment by mikewuu** [comment]
Alright, thanks for checking it out.
