### ISSUE TITLE
[BUG] Date field's placeholder doesn't work on mobile

### ISSUE THREAD

**Issue by tonydotgit** [laraform/laraform#83]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.4
* Laravel version: 7.4
* Laraform Vue package version and type: 1.1.15 (paid version)
* Laraform Laravel package version: 1.1.16 (paid version)

### Description

The date picker doesn't show placeholder on render on mobile devices. It does after you click the date picker and delete the selected date, but not once rendered the first time.

### Steps to Reproduce

Here is how my wizard method looks like:
```php
    public function wizard()
    {
        return [
            'step1' => [
                'label' => 'Step 1',
                'elements' => [
                    'step1F1',
                ],
                'buttons' => ['previous' => false],
            ],
        ];
    }
}
```

and here is how my schema looks like:
```php
    public function schema()
    {
        return [
            'step1F1' => [
                'type' => 'date',
                'placeholder' => 'Step 1 Field 1',
                'floating' => 'Step 1 Field 1',
                'format' => 'Y-m-d',
            ],
        ];
}
```

**Expected behavior:**

The placeholder should display once the form is rendered.

**Actual behavior:** 

Date format is displayed instead (this only happens on the mobile view).

![Imgur](https://i.imgur.com/6BkbMBA.png)

**Comment by laraform** [comment]
That's in fact a [flatpickr feature](https://flatpickr.js.org/mobile-support/). Just add `options.disableMobile = true`:

``` php
 public function schema()
    {
        return [
            'step1F1' => [
                'type' => 'datetime',
                'placeholder' => 'Step 1 Field 1',
                'floating' => 'Step 1 Field 1',
                'format' => 'Y-m-d',
                'options' => [
                  'disableMobile' => true
                ]
            ],
        ];
    }
```

**Comment by tonydotgit** [comment]
> That's in fact a [flatpickr feature](https://flatpickr.js.org/mobile-support/). Just add `options.disableMobile = true`:

Gticha, tyvm Adam!
