### ISSUE TITLE
[QUESTION] Validate Single Field

### ISSUE THREAD

**Issue by skillcraft-io** [laraform/laraform#84]
### Prerequisites

* [X] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [X] Your question isn't already asked before.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 
* Laravel version: 
* Laraform Vue package version and type: 
* Laraform Laravel package version: 

### Description

I would like to validate each field, as the user fills it out, but not validate the entire field and display a red X or green (Check Mark) if the field passed the rules.

For example, a form with name, phone and email:

- When the field name is filled, validate it against the rules passed to it, but not phone and email.
- When field phone is filled, validate it against the rules passed to it, but not name and email.
- When the field email is filled, validate it against the rules passed to it, nut not, name and email.

As each field is validated, I would like to be able to update the class of that field to utilize the bootstrap is-valid/is-invalid class to display the check or X.

Now when the form is submitted, all the rules can run as expected and continue

The reasoning for this is it will not overwhelm users when they start to enter data and all the fields are marked invalid and also it will provide constructive feedback as they work through the form, generating less errors and quicker submissions.

Is there a current way to accomplish this?

**Comment by laraform** [comment]
When one field is filled out and it has invalid rules it shouldn't invalidate other fields, only if you try to submit a form with invalid fields - those will be marked as invalid. Or am I not getting the questions right?
