### ISSUE TITLE
[BUG] Laraform won't render (in fresh Laravel 7 app)

### ISSUE THREAD

**Issue by mikewuu** [laraform/laraform#85]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.2.29
* Laravel version: 7
* Laraform Vue package version and type:  1.0.9 / community
* Laraform Laravel package version:  1.0 / community

### Description

Does not render a form

### Steps to Reproduce

Fresh Laravel install, follow instructions on README

**Expected behavior:**

Renders a simple form at `/` from welcome view

**Actual behavior:** 

![image](https://user-images.githubusercontent.com/11449462/78843792-df3b7c00-7a3e-11ea-86ac-5876e1bad7ed.png)

**Comment by tonydotgit** [comment]
@sysdevmike change the `theme` in your `config/laraform.php` file to `bs4`.

**Comment by mikewuu** [comment]
Cool, that did it. Thanks @TonnyORG

**Comment by iSWORD** [comment]
This should be documented. I've been tearing my hair out because of this for the past 60 minutes.
