### ISSUE TITLE
[IDEA] Per page submit on wizard

### ISSUE THREAD

**Issue by tonydotgit** [laraform/laraform#86]
### Prerequisites

* [x] You've described your idea in a clean format with example.

### Description

Playing around with the wizard, I figured out there might be moments when I do require to submit step 1 to the backend and based on that, render a second and/or a third step. That might be cool if the wizard can handle submits based on steps as well.

### Example

I don't have a reference for this. Lmk if you would like to brainstorm around it.

### Additional Information

Any additional information, configuration or data that might be needed to understand the idea.

**Comment by laraform** [comment]
At this moment this is not possible, but will think about it. I've labelled it as `enchancement`.

**Comment by gabrielchavezme** [comment]
This would be great, it would add a lot of value to the logic of a business.

I have achieved this by creating several custom forms for each page, before going to the next step I store the information in the localstorage and when the form ends I collect the data and send it to the server.

It could be very good integration, it would make Laraform more interesting.

**Comment by tonydotgit** [comment]
bump!
