### ISSUE TITLE
[IDEA] Customizable loading "step"

### ISSUE THREAD

**Issue by tonydotgit** [laraform/laraform#87]
### Prerequisites

* [x] You've described your idea in a clean format with example.

### Description

It would be nice to have. way to customize the loader window during the submit process. Somehow customizable through a Static element or something.

### Example

I've not a sample for this but basically a custom HTML content for letting the user know that we are processing the data.

### Additional Information

Any additional information, configuration or data that might be needed to understand the idea.

**Comment by laraform** [comment]
You can access `submitting` property of the form to create a custom solution for this. Eg. adding a css class to the form which renders a loader above the whole form with a semi-transparent background when `submitting = true`.

**Comment by tonydotgit** [comment]
Gotcha, well that might works for now. ty @laraform !

**Comment by tonydotgit** [comment]
@laraform just to confirm, watching the `submitting` property on the front-end made the trick. TYVM!
