### ISSUE TITLE
[BUG] File onerror undefined variable

### ISSUE THREAD

**Issue by grantholle** [laraform/laraform#88]
### Prerequisites

* [ ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.3.16
* Laravel version: 7.3.0
* Laraform Vue package version and type: 1.1.16 pro
* Laraform Laravel package version: N/A

### Description

Here's the [flare error](https://flareapp.io/share/353MMWPW#F1). I think it's supposed to be

```
reader.onerror = error => {
  reject(error)
}
```

### Steps to Reproduce

The server threw a 413 error for the file component. The error didn't get handled correctly.

**Comment by laraform** [comment]
Thanks for reporting @grantholle. Fixed in latest `1.1.17`.
