### ISSUE TITLE
Exception "Attribute value must be an array or instance of Countable"

### ISSUE THREAD

**Issue by gmartinez** [laraform/laraform#9]
I have the following list defined in a form;

            '_props->notes' => [
                'type' => 'list',
                'label' => 'Notes',
                'object' => [
                            'label' => 'Entry',
                            'schema' => [
                                    'note' => [
                                        'label' => 'Note',
                                        'type' => 'textarea',
                                    ],
                                    'ts' => [
                                        'label' => 'TS',
                                        'type' => 'text',
                                        'columns' => 6
                                    ],
                                    'uid' => [
                                        'label' => 'UID',
                                        'type' => 'text',
                                        'columns' => 6
                                    ]
                                ],
                            ]
            ]

When I submit, the data gets saved but the /laraform/process returns with an an http error 500 and the following error message;

> exception: "UnexpectedValueException"
> file: {...}\vendor\laraform\laraform-laravel\src\Elements\ListObjectElement.php"
> line: 32
> message: "Attribute value must be an array or instance of Countable"

As I was saying data gets saved just fine...Thoughts ?

**Comment by laraform** [comment]
This also relates to a similar case as the previous one. As a quick fix, add the following to src\Elements\ListObjectElement.php:31-33:
```
if ($entity === null) {
    return;
}
```
So that your `storeFiles` method looks like this:
```
    public function storeFiles($entity)
    {
        if ($entity === null) {
            return;
        }

        if (!$entity instanceof \Countable && !is_array($entity)) {
            throw new \UnexpectedValueException('Attribute value must be an array or instance of Countable');
        }

        $updates = [];

        foreach ($this->children as $child) {
            $updates = array_merge($updates, $child->storeFiles($entity[$this->attribute]));
        }

        if (empty($updates)) {
            return $updates;
        }

        return [
            $this->name => $updates
        ];
    }
```
I haven't tested it throughly, but this should solve the problem.

**Comment by gmartinez** [comment]
Provided fix did the trick, guess you'll probably do some further test and apply for next patch. Closing.
