### ISSUE TITLE
[QUESTION] Counter on List Element

### ISSUE THREAD

**Issue by mike2410** [laraform/laraform#90]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 
* Laravel version: 
* Laraform Vue package version and type: 
* Laraform Laravel package version: 

### Description

Is there a way to count the elements added by the list component? For example given a list that contains "suggestions" I'd like for the user to see "sugeestion 1" and when he adds another "suggestion 2" etc.

**Comment by laraform** [comment]
The index of a list item can be accessed with `this.name`, then you can use this to render it somewhere when a new element is added.

Eg. for list object:
``` js
    data() {
      return {
        schema: {
          my_list: {
            object: {
              created() {
                this.label = this.label + ' ' + (this.name + 1)
              }
            }
          }
        }
      }
    },
```

**Comment by mike2410** [comment]
Oh great thanks a lot @laraform will give this a shot!

**Comment by mike2410** [comment]
is there any recommend way how to check how many sibblings a list itme has?

**Comment by laraform** [comment]
There's actually a [siblings$](https://laraform.io/docs/1.x/reference/frontend-form#method-siblings$) method or you can call `this.$parent.children$` in a list item to access all siblings relatively.
