### ISSUE TITLE
[QUESTION] Frontend only rendering

### ISSUE THREAD

**Issue by mikewuu** [laraform/laraform#91]
* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: none
* Laravel version: none
* Laraform Vue package version and type: 1.0.9 community
* Laraform Laravel package version: none

### Description

**Does the community edition support rendering via frontend only?**

Given the following component

```js
<script>
/* eslint-disable */
export default {
  mixins: [Laraform],
  data: () => ({
    schema: {
      name: {
        type: 'text',
      },
    },
  }),
}
</script>
```

I get the following error

![image](https://user-images.githubusercontent.com/11449462/79518590-75e5e980-808c-11ea-97e4-394ef9b995d9.png)

### Additional Information

If I render using the full form and the `<laraform>` component it works

```js
<template>
  <laraform :form="form"></laraform>
</template>

<script>
export default {
  data: () => ({
    form: {
      key:
        'eyJpdiI6IkRrU1FJbnBFSlpyaktTNXVsc3A3clE9PSIsInZhbHVlIjoieWozL0JPUE5kdWpQMXRHVDZyM2dVU1B6WFBiWFEvNENtSEw1UnU2YytLTT0iLCJtYWMiOiJkMzNmZTQ2NzZmYjI0MjMyNzM5NTUwYmI3YjE1MjA2ODdkNGE5NDEyOWY1M2YzYzk1NDJlMDBlNjc3NTQ1NGY3In0=',
      data: [],
      schema: {
        hello_world: {
          type: 'text',
          label: 'Hello',
          default: 'World',
          name: 'hello_world',
          component: 'text-element',
        },
      },
      theme: '',
      columns: {
        element: 12,
        label: 12,
        field: 12,
      },
      class: null,
      classes: null,
      labels: false,
      layout: 'horizontal',
      formErrors: true,
      buttons: null,
      with: [],
      messages: [],
      locale: 'en_US',
      endpoint: '/laraform/process',
      method: 'POST',
      validateOn: 'submit|change',
    },
  }),
}
</script>
```

If you could share an example with frontend only rendering that would be great.

Edit: Clarify I meant rendering from vue component only, without Laravel `{!!$form->render() !!}`

**Comment by tonydotgit** [comment]
@sysdevmike can you share your `app.js`?  you might be missing the `Vue.use(Laraform)` instruction there.

**Comment by mikewuu** [comment]
Sure, here you go.

```
import Vue from 'vue'
import App from './App.vue'
import vuetify from './plugins/vuetify'
import Laraform from 'laraform'

Vue.config.productionTip = false

Vue.use(Laraform)

new Vue({
  vuetify,
  render: (h) => h(App),
}).$mount('#app')
```

I think it's including it fine, as this works as expected

```
<laraform  class="lf-form" :form="form"></laraform>
```

_Side note: had to add `lf-form` class manually for the default theme to apply even though the theme in the form object was not set._

**Comment by laraform** [comment]
The error you are receiving might be because using the Laraform mixin / component before it is installed with `Vue.use` - I assume this by having `App.vue` imported first, which probably contains the form.

Also, you can refer to this section in the docs to see how you can use the frontend component only:
https://laraform.io/docs/1.x/how-tos/using-only-frontend

The one you've showed as an example is a bit anti-pattern as `:form` property should only be used with backend rendering. Without backend you are supposed to create a new component for a form instance and add `Laraform` as a mixin as seen in the docs example above, unless you are trying to create form dynamically.

**Comment by mikewuu** [comment]
Yep that was it, thanks! Of course, `Laraform` global mixin is provided by the import, ie. has to happen before `App.vue`; totally missed it.

Works as expected, I'm making a form builder and working directly with the `:form` prop.
