### ISSUE TITLE
[QUESTION] How to customize wizard's buttons

### ISSUE THREAD

**Issue by tonydotgit** [laraform/laraform#94]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.4
* Laravel version: 7.4
* Laraform Vue package version and type: 1.1.16
* Laraform Laravel package version: 1.1.16

### Description

I would like to customize the colors of "next", "previous" and "finish" buttons, I know adding a class might be enough; the problem is, I'm not sure how to add a class to the buttons in the wizard.

### Additional Information

I tried this already but didn't work:

```php
    public function wizard()
    {
        return [
            'step1' => [
                'label' => Step 1,
                'elements' => [],
                'buttons' => [
                    'previous' => false,
                    'next' => ['class' => 'btn-success']
                ],
                'labels' => ['next' => 'Move!',
            ],
```

**Comment by laraform** [comment]
You can overwrite any class being used in Laraform components in [`$classes`](https://laraform.io/docs/api-laraform#prop-classes) property:

``` php
  public $classes = [
    'formWizardControlPrevious' => '...',
    'formWizardControlNext' => '...',
    'formWizardControlFinish' => '...'
  ];
```

**Comment by tonydotgit** [comment]
@laraform that worked! tyvm
