### ISSUE TITLE
[QUESTION] How to handle the $key in a custom endpoint on submit?

### ISSUE THREAD

**Issue by tonydotgit** [laraform/laraform#95]
### Prerequisites

* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.4
* Laravel version: 7.4
* Laraform Vue package version and type: 1.1.16
* Laraform Laravel package version: 1.1.16

### Description

Basically I've a form with a custom submit endpoint defined and I would like to know how I can take advantage on this to decide which form class to use for validation or at least to store the value of $key in my submit request in the backend ($key comes encrypted, so I don't really know what to do with it).

**Comment by laraform** [comment]
The `$key` is an encrypted string as you say which contains the name of the backend form class. To produce the full backend class name with namespace Laraform uses this:

``` php
$form = app(config('laraform.path') . '\\' . decrypt($request->key));
```

You can also create a custom key by overriding `getFormKey` method in your backend form.

I'd recommend checking out current implementation at:
`vendor/laraform/laraform-laravel/src/Controllers/FormController.php@process`
`vendor/laraform/laraform-laravel/src/Laraform.php@getFormKey`

**Comment by tonydotgit** [comment]
@laraform excellent, tyvm sr
