### ISSUE TITLE
[QUESTION] Any type definitions available?

### ISSUE THREAD

**Issue by mikewuu** [laraform/laraform#96]
* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* Laraform Vue package version and type: 1.0.9 community 

### Description

Can't find types in `@types` for Laraform, are there any available? I've already manually written out the types I need, thought I'd ask in case it's already been done.

### Additional Information

Making a form builder in TS.

**Comment by laraform** [comment]
Currently we don't have `@types`. We have plans to implement Laraform in `TS` thought, but that will come later only.

**Comment by mikewuu** [comment]
Great, thanks!
