### ISSUE TITLE
[BUG] Display validation errors in custom form

### ISSUE THREAD

**Issue by gabrielchavezme** [laraform/laraform#97]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.4
* Laravel version: 6.2.1
* Laraform Vue package version and type: 1.1.8 / PRO
* Laraform Laravel package version: 1.1.9 PRO

### Description

I am integrating Laraform to develop a form that refreshes on a new page every time a form is completed.

I saw the documentation and saw that there was nothing about it and so I decided to develop my own form.

### Steps to Reproduce

I need to validate the form and show the alerts before reaching the submit method, but I have not found how to display it and it directly sends me to the submit event.

**Expected behavior:**

I hope that before the submit method is executed validation messages will be displayed in my custom form.

**Actual behavior:** 

It doesn't really show any errors and only sends the submit event without first validating or displaying the errors.

I think it is because I am not placing any component of Laraform but I have not found any information about it.
### Additional Information

My form:

https://gist.github.com/gabrielchavezme/d4575ae850aba537b94aa0ad9700e2ca

Is there any way to fix this?

**Comment by laraform** [comment]
Check out the original `submit` method at `@laraform/laraform/src/component/Laraform.vue`. You can see that this is what it contains:

``` js
      submit() {
        if (this.disabled) {
          return
        }

        if (this.fire('submit') === false) {
          return
        }

        if (this.$_shouldValidateOn('submit')) {
          this.validate()
        }

        this.proceed(() => {
          this.send()
        })
      },
```

The `this.validate()` is definitely required, and `this.proceed()` serves the purpose of waiting for any async validators to run and only call `this.send()` when they all run and the form has no invalid fields. You can play with these to have validation in place before submission.

(If you only want to overwrite the actual submission method only, I'd recommend overriding `send` method instead of `submit`)

**Comment by gabrielchavezme** [comment]
> Check out the original `submit` method at `@laraform/laraform/src/component/Laraform.vue`. You can see that this is what it contains:
> 
> ```js
>       submit() {
>         if (this.disabled) {
>           return
>         }
> 
>         if (this.fire('submit') === false) {
>           return
>         }
> 
>         if (this.$_shouldValidateOn('submit')) {
>           this.validate()
>         }
> 
>         this.proceed(() => {
>           this.send()
>         })
>       },
> ```
> 
> The `this.validate()` is definitely required, and `this.proceed()` serves the purpose of waiting for any async validators to run and only call `this.send()` when they all run and the form has no invalid fields. You can play with these to have validation in place before submission.
> 
> (If you only want to overwrite the actual submission method only, I'd recommend overriding `send` method instead of `submit`)

I verified it and it worked for me, now it is validated before proceeding with the shipment. 

I have one last question, I have tried to show the validation errors by adding the following component to my form:

`<FormErrors v-if = "formErrors && errors.length": errors = "errors" />`

I've also seen the `@laraform/laraform/src/component/Laraform.vue` component and try to replicate the code but still don't see the validation errors.

**Comment by gabrielchavezme** [comment]
I finally found the problem, I was reviewing the component `@laraform/laraform /src/component /Laraform.vue` and I realized that I was not including the necessary data so that Laraform knew when to show the errors.

Add the following to the data method:

```
formErrors: null,
validation: true,
loading: false,
elements $: {},
displayError: true,
```
And in the method array add the following:

```
validate() {
      _.each(this.elements$, element$ => {
        // only validate those which
        // have not been validated yet
        // or if the form still has
        // invalid fields
        if ((!element$.validated || this.invalid) && element$.available) {
          element$.validate();
        }
      });
    },
```
And lastly, leave my submit method like this which is called from the form you layout:

```
submit() {
      if (this.disabled) {
        return;
      }

      if (this.fire("submit") === false) {
        return;
      }

      if (this.$_shouldValidateOn("submit")) {
        this.validate();
      }

      this.proceed(() => {
        this.handleSubmit();
      });
    },
```
I guess the problem was because I was extending the component:

`<TextElement name = "denomination": schema = "schema.denomination" v-ref: elements $ />`

So what I did was directly extend the component:

`<FormElements: schema = "schema" ref = "elements $" />`

This now works :)
