### ISSUE TITLE
[IDEA] Algolia Support

### ISSUE THREAD

**Issue by gabrielchavezme** [laraform/laraform#98]
### Prerequisites

* [x] You've described your idea in a clean format with example.

### Description

I have been developing a complex form and one of the inputs must have Algolia integrated to auto-complete information to the user.

I am sure that integrating support for Algolia would give Laraform much more value as a library.

### Example

In order not to reinvent the wheel, I have integrated vue-places into my project, which saved me a couple of hours to integrate this functionality.

https://github.com/Gomah/vue-places

**Comment by laraform** [comment]
Definitely we're going to have this soon as a single field too!

Btw [Address](https://laraform.io/docs/1.x/reference/address-element) element is a bit similar and also using Algolia.
