### ISSUE TITLE
[IDEA] Catch "http codes !== 200" on.fail

### ISSUE THREAD

**Issue by tonydotgit** [laraform/laraform#99]
### Prerequisites

* [x] You've described your idea in a clean format with example.

### Versions

Laraform 1.1.16 (back and front)
PHP: 7.4

### Description

Basically I just noticed than a normal API response flow is not well supported by laraform. What do I mean by this?  Let's take a look at the example section.

### Example

Well, having a backend response like this:

```php
        return response()->json([
            'status' => 'fail', // Ideally this should be: 'status' => 'error',
            'messages' => [
                'Oops...'
            ],
            'payload' => [],
        ], 400); // Laraform will only recognize this error IF the status is 200, 201... or any other 200
```

That's a very common way to respond (using HTTP error codes for indicate bad request, internal server error, or whatever.

Current front-end behavior, having this:
```
      this.on('fail', (response) => {
            // This only works for 'status' = 'fail' and HTTP code in 200, 201... etc
      }

      this.on('error', (response) => {
            // This works for ANY non 200 error code (like 400, 500, etc)
            //  the problem is that "response" is not the actual response returned by the backend, it's a JS/axios or whatever object.
      }
```

### Additional Information

It would be nicer if we can simplify (and make more consistent) the `fail` and the `error` behaviors, merge them into a SINGLE one in the front-end (maybe the default `error`?), so `error` happens for responses with `status=fail` and `status=error` and ALSO it does supports any non-200 HTTP code, so we can actually respond in the backend with a REAL HTTP error code instead responding with 200 and with `status=fail` (which is like... non-consistent, it returned 200 but it has an error?).

**Comment by laraform** [comment]
Yes it kinda makes sense, thank you for the suggestion.
